### ISSUE TITLE
Allow VMPIDR_EL2 register to be set for VMs when CONFIG_MAX_NUM_NODES=1 

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/seL4#1015]
Currently the seL4_VCPUReg enum only defines the seL4_VCPUReg_VMPIDR_EL2 register when the kernel is configured for SMP. This register should be available for unicore systems too as otherwise a user level VMM is not able to control the value of MPIDR_EL1 that the guest VM reads.

```
#if CONFIG_MAX_NUM_NODES > 1
    /* Virtualisation Multiprocessor ID Register */
    seL4_VCPUReg_VMPIDR_EL2,
#endif /* CONFIG_MAX_NUM_NODES > 1 */
```

**Comment by axel-h** [comment]
Make sense to me, seem for ARMv7 and `seL4_VCPUReg_VMPIDR` it's a similar thing then. Could you make a PR?

**Comment by lsf37** [comment]
No blockers from the verification side, should be fine to include.
