### ISSUE TITLE
Does the SMMU support 32-bit S1 translations?

### ISSUE THREAD

**Issue by chrisguikema** [seL4/seL4#1071]
I've gotten a 32-bit guest working with the camkes-vm on a 64-bit Arm target. The guest needs access to a network device, which requires the SMMU to be configured. When configured, the network device will receive RX packets, but TX packets will never transmit. 

I've gotten around the issue by disabling the SMMU mapping the DMA buffers 1:1, but this isn't an ideal solution, since the SMMU is no longer protecting the system. 

Does the seL4 SMMU driver support 32-bit S1 translations?

**Comment by Indanz** [comment]
Assuming with 32-bit you mean a mapping with virtual addresses which fit in 32-bit:

seL4's SMMU kernel implementation is one-to-one with a vspace and can't be used to change what address the device sees. You need to do that by mapping your DMA memory in a vspace the way you want the hardware to see it. You can create a new vspace just for your network device to achieve this.

**Comment by chrisguikema** [comment]
No, this is a modification to the seL4 VCPU layer to configure a guest to run in 32-bit mode (HCR_EL2.RW).

**Comment by Indanz** [comment]
I looked up how SMMU works and how seL4 is using it. The current support seems very limited: SMMU can only be enabled for the TK1 and TK2 platforms and the code seems to be only tested with those, even though other platforms also have SMMU support. The SMMUv2 code seems to be originally TK2-only, considering the SMMU_BASE address is hard-coded. So the first challenge is to get SMMU support for your platform working at all.

What you seem to be asking about is nested translations, so both stage 1 and stage 2 translations, with the guest OS managing stage 1 tables and seL4 managing the stage 2 translations. The current seL4 code only supports type 0 and 1 translations, that is, only stage 1 or stage 2 translations, see `CBARn_TYPE_STAGE2` in the code.

To answer your question, currently seL4 does not support S1 translations at all when running in EL2 with hypervisor support. If support for this was added, whether the stage 1 translations are 32-bit or 64-bit seems like a minor detail and would be managed by the guest OS.

If you do not need nested translations and only want stage 2 translations, then those tables are 64-bit only. But as it's fully transparent to the guest OS, whether it's 32-bit or 64-bits shouldn't matter.

**Comment by Indanz** [comment]
> @Apave24 has added SMMU support for the zynqmp and has made PRs for it (not sure the current status).

The fix PR should be brought up-to-date with master and then it's probably almost ready for merging. The other one had some minor cosmetic feedback which needs to be done, but otherwise seems ready too.

> I'm not sure the S1 translation matter in this case, as the guest OS is using what it thinks is the physical address, so only the S2 mappings should work.

Looks like it. Can we close this issue or did you have any remaining questions?
