### ISSUE TITLE
aarch64 decodeARMFrameInvocation error reporting

### ISSUE THREAD

**Issue by lsf37** [seL4/seL4#1075]
Two things that just came up in the aarch64 refinement proof: 

In decodeARMFrameInvocation for aarch64: https://github.com/seL4/seL4/blob/8c9cf6c7db34a4f83aa9ab1b821ee9e8d8fdba8e/src/arch/arm/64/kernel/vspace.c#L2118-L2122
we report cap 0 as the invalid cap when ASIDs don't match, but aarch32 reports cap 1 in the same circumstances, which I think makes more sense. See: https://github.com/seL4/seL4/blob/8c9cf6c7db34a4f83aa9ab1b821ee9e8d8fdba8e/src/arch/arm/32/kernel/vspace.c#L2276-L2280

Similarly, for the `vaddr` comparison, aarch64 reports argument 2 as invalid, which is wrong (there is no argument 2). Aarch32 correctly report argument 0 as invalid, as does the overflow check in aarch64 that comes directly after:

https://github.com/seL4/seL4/blob/8c9cf6c7db34a4f83aa9ab1b821ee9e8d8fdba8e/src/arch/arm/64/kernel/vspace.c#L2124-L2135

**Comment by lsf37** [comment]
@kent-mcleod would you be happy to include these tweaks in PR #801 or should I make a separate one?

**Comment by kent-mcleod** [comment]
> @kent-mcleod would you be happy to include these tweaks in PR #801 or should I make a separate one?

Can do

**Comment by kent-mcleod** [comment]
> we report cap 0 as the invalid cap when ASIDs don't match, but aarch32 reports cap 1 in the same circumstances, which I think makes more sense.

But the definition of seL4\_InvalidCapability is Invalid capability argument number, and the VSpace cap is the first (0th) capability argument to the invocation.

**Comment by kent-mcleod** [comment]
> Similarly, for the vaddr comparison, aarch64 reports argument 2 as invalid, which is wrong (there is no argument 2). Aarch32 correctly report argument 0 as invalid, as does the overflow check in aarch64 that comes directly after:

I agree this should be 0, and I've updated it in the other PR.  I am confused what you mean by there is no argument 2 as there is (seL4_ARM_VMAttributes).

**Comment by Ivan-Velickovic** [comment]
Can this be closed now?

**Comment by lsf37** [comment]
Let me double check that we are in sync now

**Comment by lsf37** [comment]
I think that's not fully in sync yet:

@kent-mcleod wrote:
> > we report cap 0 as the invalid cap when ASIDs don't match, but aarch32 reports cap 1 in the same circumstances, which I think makes more sense.

> But the definition of seL4_InvalidCapability is Invalid capability argument number, and the VSpace cap is the first (0th) capability argument to the invocation.

That is correct, but this error is on the frame cap, which is cap 1. So I still think this should change from 0 to 1 in here:

https://github.com/seL4/seL4/blob/7221eba1b96c3c3b508345fee9a564c32375da0b/src/arch/arm/64/kernel/vspace.c#L1492-L1497

(And Kent was of course correct on the other, the VM attributes are argument 2, I was confusing that counter with the caps).

**Comment by lsf37** [comment]
I'm happy to make a PR for it if @kent-mcleod is happy that this is the right change.

**Comment by kent-mcleod** [comment]
> That is correct, but this error is on the frame cap, which is cap 1. So I still think this should change from 0 to 1 in here:

I think you're right that this update should happen as the seL4_InvalidCapability message uses 0 to refer to the service capability on other verified configurations.

 
But is the 0th capability argument the invoked "service" capability, or is it the 0th slot of the IPC buffer's extra cap references? The manual just states: "Invalid capability argument number". The libsel4 function seL4_SetCap() makes this a bit confusing because calling it with an argument 0 is actually setting the 2nd capability argument (assuming that the first capability is the service capability being invoked.). 

```
LIBSEL4_INLINE seL4_Error
seL4_ARM_Page_Map(seL4_ARM_Page _service, seL4_CPtr vspace, seL4_Word vaddr, seL4_CapRights_t rights, seL4_ARM_VMAttributes attr)
{
	seL4_Error result;
	seL4_MessageInfo_t tag = seL4_MessageInfo_new(ARMPageMap, 0, 1, 3);
	seL4_MessageInfo_t output_tag;
	seL4_Word mr0;
	seL4_Word mr1;
	seL4_Word mr2;
	seL4_Word mr3;

	/* Setup input capabilities. */
	seL4_SetCap(0, vspace);

	/* Marshal and initialise parameters. */
	mr0 = vaddr;
	mr1 = rights.words[0];
	mr2 = attr;
	mr3 = 0;

	/* Perform the call, passing in-register arguments directly. */
	output_tag = seL4_CallWithMRs(_service, tag,
		&mr0, &mr1, &mr2, &mr3);
	result = (seL4_Error) seL4_MessageInfo_get_label(output_tag);
...
```

**Comment by lsf37** [comment]
> That is correct, but this error is on the frame cap, which is cap 1. So I still think this should change from 0 to 1 in here:

Actually I was wrong in that sentence, we do treat the frame cap as 0 and the vspace cap as 1 everywhere else in that function. And the check here is for the frame cap (that part was not wrong). So in fact, the aarch64 code is right, and the aarch32 code is wrong, as is the x86 code.

Can someone (@corlewis?) double-check that I'm not confusing myself here?

The relevant functions are `decodeARMFrameInvocation` and `decodeX86FrameInvocation`, in particular the error reporting case where both `cap_frame_cap_get_capFMappedASID(cap) != asidInvalid` and `cap_frame_cap_get_capFMappedASID(cap) != asid` are true. `cap` in there refers to the service cap, i.e. cap 0 (at least the frame cap is definitely not cap 1, because report cap 1 for checks on the vspace cap in the other cases in the same function, and the vspace cap is the first `excap`).

The spec only catches that we've been inconsistent between aarch64 and aarch32, but can't say which one is right, since it's just a number we report to the user.

**Comment by kent-mcleod** [comment]
In this case it is the vspace that's the invalid argument though. The check is checking that the frame's ASID matches the VSpace ASID so it could go either way.  I'd say currently the object of the operation is the frame cap, so providing a vspace with a different ASID is providing an invalid cap in arg 1 for the target operation (mapping or remapping the frame cap).

**Comment by corlewis** [comment]
I agree that we treat the frame cap as 0 and the vspace cap as 1 in that function, and that aarch64 is reporting the error differently to aarch32. However, that check is comparing the ASIDs of both caps, so an argument could be made for reporting either one in the error. In my mind it doesn't really matter which one we go with, as long as we're consistent.

Talking of consistency and since I'm looking at both versions of the function, while we're here do we want to make it so that both aarch32 and aarch64 print the same messages as userErrors when catching equivalent cases?

**Comment by lsf37** [comment]
Ok, thanks both of you, you're right of course. I'm happy with Kent's logic that gives a slight preference to the vspace cap being the one that "wrong" in this comparison, so reporting cap 1 is what we should do and the other architectures are correct and to keep it consistent we should change the aarch64 version.

> Talking of consistency and since I'm looking at both versions of the function, while we're here do we want to make it so that both aarch32 and aarch64 print the same messages as userErrors when catching equivalent cases?

I don't think the strings need to be equal, as long as the error conditions are consistent I think that's fine. I'm open to arguments, though.

I'll do a PR for flipping the 0 to 1, and if we want to adjust the strings, we could open a separate cleanup issue for that.
