### ISSUE TITLE
Cannot build kernel for Rocketchip mapped to ZCU102

### ISSUE THREAD

**Issue by Ivan-Velickovic** [seL4/seL4#1078]
Trying to build the kernel/sel4test for the Rocketchip mapped to the ZCU102, following the instructions from https://docs.sel4.systems/Hardware/rocketchip-zcu102.html, fails with the below output:

```
loading initial cache file /tmp/test/projects/sel4test/settings.cmake
-- Set platform details from PLATFORM=rocketchip-zcu102
--   KernelPlatform: rocketchip-zcu102
-- Setting from flags KernelSel4Arch: riscv64
-- Found seL4: /tmp/test/kernel  
CMake Error at /tmp/test/kernel/configs/seL4Config.cmake:175 (message):
  Variable 'KernelArch' is not set.
Call Stack (most recent call first):
  /tmp/test/kernel/FindseL4.cmake:21 (include)
  settings.cmake:32 (sel4_configure_platform_settings)


-- Configuring incomplete, errors occurred!
```

Perhaps we should change the CI to at least build sel4test images for *all* supported platforms even if we do not have the physical hardware to test the image on?

**Comment by Indanz** [comment]
> Perhaps we should change the CI to at least build sel4test images for all supported platforms even if we do not have the physical hardware to test the image on?

Agreed, otherwise build errors after configuration or sel4test restructuring changes won't be caught. However, the permutation of supported platforms and configurations is quite large, so it needs to be limited somehow. Kernel-only builds are also an option, but not sure if that would have caught this particular issue.

**Comment by axel-h** [comment]
Seems, the common practical issue usually the missing `ltimer` implementation. Thing is, that seL4test needs this one, but you can also build systems that don't use it.

**Comment by Ivan-Velickovic** [comment]
In this case the kernel is not even building, I can try do a standalone kernel build but I would be surprised if the output was different.

**Comment by Furao** [comment]
I poked around at this, and it looks like during the upstream we missed a couple of changes that we needed to get seL4test to build and work:
- Need to add a platform alias here: https://github.com/seL4/seL4_tools/blob/master/cmake-tool/helpers/application_settings.cmake#L161
- Need to disable `Sel4testHaveTimer` for this platform in sel4test
- Seems like something needs to change with our opensbi or the building of it as well. I haven't solved this one yet. Once I figure it out, I will push up these changes as PRs.

**Comment by Ivan-Velickovic** [comment]
> I poked around at this, and it looks like during the upstream we missed a couple of changes that we needed to get seL4test to build and work:
> 
>     * Need to add a platform alias here: https://github.com/seL4/seL4_tools/blob/master/cmake-tool/helpers/application_settings.cmake#L161
> 
>     * Need to disable `Sel4testHaveTimer` for this platform in sel4test
> 
>     * Seems like something needs to change with our opensbi or the building of it as well. I haven't solved this one yet. Once I figure it out, I will push up these changes as PRs.

Cool, thanks for looking into it.

**Comment by Furao** [comment]
PRs here:

- https://github.com/seL4/sel4test/pull/102
- https://github.com/seL4/seL4_tools/pull/177

I updated our fork of opensbi, but that doesn't require any updates to the instructions. Just need to pull if you already have it cloned. 

This fixes the build issues and I tested the image with our [prebuilt bitstreams](https://github.com/dornerworks/Vivado-Prebuilts) and all the tests passed.
