### ISSUE TITLE
Use `-mtune` or `-mcpu` when compiling kernel?

### ISSUE THREAD

**Issue by Ivan-Velickovic** [seL4/seL4#1079]
I've come across `-mtune`/`-mcpu` (https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html#index-mtune) and have just realised that these optimisation arguments are not passed to the compiler when compiling the kernel.

I was wondering whether it is worth to actually use these or not, as I don't know if they actually make a difference on the kernel code. A quick test by passing `-mtune=cortex-a53` for the Odroid-C4 actually shows an increase in the size of `kernel.elf` from 149976 bytes without `mtune` to 151000 bytes with `mtune` passed in.

I have not run any serious benchmarks yet, but was wondering if anyone has any experience with whether these optimisations actually end up doing anything.

**Comment by Ivan-Velickovic** [comment]
Right, it looks like 836e802a599c7271f986670b878e5298e0373a4f removed it for ARM but no explanation as to why unfortunately.

**Comment by gernotheiser** [comment]
Two possible explanations: 
- More aggressive optimisation may not be beneficial for the kernel (a blowout in code size is certainly a red flag!)
- More aggressive optimisation may defeat the binary verification toolchain

**Comment by Ivan-Velickovic** [comment]
I considered the section option but BV doesn't work for ARM yet and based on the commit date, the optimisation was removed before BV was ever thing I think (commit is from 2017).

**Comment by Ivan-Velickovic** [comment]
Ah sorry, I completely forgot about AArch32.

**Comment by axel-h** [comment]
Can we close this for now or do you plan to dive into this?

**Comment by Ivan-Velickovic** [comment]
I was waiting to see if someone to respond whether it was because of BV or because of another reason but it looks like no-one knows for sure. I'll assume it was done because of BV due to the date of the commit.
