### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by hexabyte23** [seL4/seL4#108]
got this when try to compile

ning dependencies of target kernel_autoconf_Gen
[  0%] Built target kernel_autoconf_Gen
Scanning dependencies of target kernel_Gen
[  0%] Built target kernel_Gen
Scanning dependencies of target kernel_config_headers
[  0%] Built target kernel_config_headers
Scanning dependencies of target xml_headers_target
[  1%] Generate invocation header gen_headers/arch/api/invocation.h
usage: invocation_header_gen.py [-h] --xml XML --dest DEST [--libsel4]
                                [--arch | --sel4_arch]
invocation_header_gen.py: error: argument --dest: can't open 'gen_headers/arch/api/invocation.h': [Errno 2] No such file or directory: 'gen_headers/arch/api/invocation.h'
make[2]: *** [CMakeFiles/xml_headers_target.dir/build.make:66: gen_headers/arch/api/invocation.h] Error 2
make[1]: *** [CMakeFiles/Makefile2:462: CMakeFiles/xml_headers_target.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by pingerino** [comment]
Hi @hexabyte23, could you please provide your build commands? How are you trying to build the kernel? Please consider going through the [seL4 tutorials](https://docs.sel4.systems/Tutorials/) which have detailed instructions on how to build seL4 as part of a larger project.

**Comment by pingerino** [comment]
Closing due to no response from reported. Please reopen if the issue occurs again.
