### ISSUE TITLE
Possible regression with Polarfire SoC

### ISSUE THREAD

**Issue by Ivan-Velickovic** [seL4/seL4#1094]
The commit that I made https://github.com/seL4/seL4/commit/69040396083959df9bb7cdc193cdf3f13af5bde8 recently seems to have caused a regression when booting seL4, as assertions such as:
```
Booting all finished, dropped to user space
seL4 failed assertion 'refill_ready(thread->tcbSchedContext)' at /host/seL4/src/kernel/thread.c:447 in function switchToThread
halting...
Kernel entry via Interrupt, irq 0
```

are going off.

The reason I call this a *possible* regression is that I do not know whether it is an issue with QEMU or the commit itself. What is confusing to me is that I believe the Polarfire SoC has the *same* U54-MC CPU that the HiFive Unleashed has, which has no problems with this patch. I unfortunately do not have access to the hardware, so cannot confirm whether this is an issue with QEMU or not.

**Comment by Ivan-Velickovic** [comment]
This manual https://www.microsemi.com/document-portal/doc_view/1245725-polarfire-soc-fpga-mss-technical-reference-manual for the Polarfire (which I believe is the right manual to be looking at) states in Table 6-25 that `mtime` is at `0x0200_BFF8`, which matches with what the kernel ends up accessing to get the value of the register.

**Comment by Indanz** [comment]
Could you add an if-check before the assert with the same condition and print out what the actual values are?

Perhaps it just overflows because it's not initialised correctly.

**Comment by Indanz** [comment]
I think it got broken by [this](https://github.com/riscv-software-src/opensbi/commit/59a08cd7d632bb2394a29956497dfe7829099997) commit, which is part of [Split region permissions into M-mode and SU-mode](http://lists.infradead.org/pipermail/opensbi/2023-January/004127.html). Perhaps platforms are expected to add explicit S/U access to CLINT in their OpenSBI device tree since that patch, but not all platforms have done that?

I opened a new OpenSBI [issue](https://github.com/riscv-software-src/opensbi/issues/330), let's see what they say.

**Comment by Ivan-Velickovic** [comment]
I don't think it was broken by that commit since v1.2 of OpenSBI was released last year and that commit is from January this year.

**Comment by Ivan-Velickovic** [comment]
Thanks for posting that issue though, maybe it will give us some clarity.

**Comment by axel-h** [comment]
I think there was some concern, that write access to the timer compare register (`mtimecmp`) needs more control. Each hart should only be able to access its own compare register, but not these for the other harts. Writing the registers for other harts could be fatal, as they might run mutually distrusting software in S-Mode.
Seems the access permission should just be made more fine grained then, so the global time registers can be read directly at least.

**Comment by Indanz** [comment]
> I don't think it was broken by that commit since v1.2 of OpenSBI was released last year and that commit is from January this year.

I don't know then, it was the only commit I could find that seemed relevant.

> Each hart should only be able to access its own compare register, but not these for the other harts.

Surely they each have their own 4k page, so they can be mapped differently per core?

If seL4 had direct access to `mtimecmp` it wouldn't need an SBI call to set the next timer interrupt.

**Comment by Ivan-Velickovic** [comment]
@Indanz it doesn't look like the OpenSBI GitHub issues get responded to very much, maybe try the mailing list as well?

**Comment by axel-h** [comment]
> Surely they each have their own 4k page, so they can be mapped differently per core?

Unfortunately, no. It's more like shown here: https://marz.utk.edu/wp-content/uploads/2021/08/image-9-768x524.png

**Comment by Indanz** [comment]
> @Indanz it doesn't look like the OpenSBI GitHub issues get responded to very much, maybe try the mailing list as well?

I'll give it a few days and then post to the mailing list.

> Writing the registers for other harts could be fatal, as they might run mutually distrusting software in S-Mode.

Surely the same applies to each other's physical memory. What stops one OS from mapping the other OS's memory and mess that up?

Also, that seems like a niche use case. If there is no VM monitor other than M-mode, then for those you want to indeed disable CLINT access. But it seems like a bad default, especially if SBI isn't using the CLINT timer itself.

**Comment by axel-h** [comment]
> > Writing the registers for other harts could be fatal, as they might run mutually distrusting software in S-Mode.
> Surely the same applies to each other's physical memory. What stops one OS from mapping the other OS's memory and mess that up?

M-Mode programming the PMP ensures all the isolation.

**Comment by axel-h** [comment]
It seem we should also consider adding a config option for using the `Sstc` Extension in the long run. See https://wiki.riscv.org/display/HOME/Recently+Ratified+Extensions, spec for frozen version v0.54 is at https://drive.google.com/file/d/1O0ogDHijAc7gM58Byb0BRqIRGYsdOt2D/view

**Comment by Indanz** [comment]
Reading that it seems we're not supposed to use any of the `m*` registers when in S-mode. Maybe we should wait at least 5 more years before doing any performance optimisations for RISC-V. If they don't care, why should we bother? :-(

Considering seL4 is compiled per platform anyway, perhaps it could support M-mode. Not sure what the SBI is doing after bootup.

**Comment by Ivan-Velickovic** [comment]
According to https://github.com/riscv/riscv-profiles, `Sstc` is optional for RVA22 CPUs but will be mandatory for RVA23. So yea we are probably at least a couple of years away from having the instructions available given that I don't think that any CPUs available support RVA22 yet let alone RVA23.

**Comment by Ivan-Velickovic** [comment]
It's been a couple of months without any response from the OpenSBI maintainers. What should we do now?

It seems that either we make the direct `mtime` access an opt-in option so that seL4 works for at least newer OpenSBI versions, or seL4 pins a specific version of OpenSBI?

We could leave things as they are now, but I imagine it would be quite annoying to have seL4 fail to boot in some cases with no feedback at all, making it fairly hard to debug.

**Comment by nspin** [comment]
> I think it got broken by [this](https://github.com/riscv-software-src/opensbi/commit/59a08cd7d632bb2394a29956497dfe7829099997) commit, which is part of [Split region permissions into M-mode and SU-mode](http://lists.infradead.org/pipermail/opensbi/2023-January/004127.html). Perhaps platforms are expected to add explicit S/U access to CLINT in their OpenSBI device tree since that patch, but not all platforms have done that?

It is actually this patch, between v0.9 and v1.0, which broke `KernelRiscvUseClintMtime=ON`:

https://github.com/riscv-software-src/opensbi/commit/8b569803475e130b85987b97fdd47c19e900bf82

**Comment by Indanz** [comment]
There was some noise on the [issue](https://github.com/riscv-software-src/opensbi/issues/330) I opened, but there doesn't seem to be much interest in giving back access to MTIME. My personal stand now is that if RISC-V doesn't care about performance on their hardware, neither will I.
