### ISSUE TITLE
.gitignore file doesn't do what you want

### ISSUE THREAD

**Issue by taralx** [seL4/seL4#110]
The .gitignore file uses **.ext, but that's not valid according to the git manual. You want **/*.ext instead.

(This causes ripgrep to throw a bunch of errors, but git silently treats the asterisks as literal characters.)

**Comment by lsf37** [comment]
You are right, `**` is not the right syntax.

We could write `**/*.ext` instead, but according to <https://git-scm.com/docs/gitignore> a pattern already matches at any directory level if it doesn't contain `/`, so I'll do that instead.
