### ISSUE TITLE
When is the thread's ipc_buffer 0

### ISSUE THREAD

**Issue by CtrlZ233** [seL4/seL4#1101]
https://github.com/seL4/seL4/blob/61a8ccef44eeb08ecd20ad40296340c8319adee5/include/api/syscall.h#L38-L46

I found that some syscall path (such as TCB read register syscall path) won‘t check the `ipc_buffer != 0` before invoke `getSyscallArg ` function. I would like to know under what circumstances the ipc_buffer address of a thread would become invalid.

**Comment by kent-mcleod** [comment]
At the start of every invocation, the calling TCB's ipc buffer is looked up in `handleInvocation()`. If the ipc buffer is null then the message length for the invocation is adjusted to be no larger than n_msgRegisters: 
```
    /* Syscall error/Preemptible section */
    length = seL4_MessageInfo_get_length(info);
    if (unlikely(length > n_msgRegisters && !buffer)) {
        length = n_msgRegisters;
    }
```

**Comment by CtrlZ233** [comment]
> At the start of every invocation, the calling TCB's ipc buffer is looked up in `handleInvocation()`. If the ipc buffer is null then the message length for the invocation is adjusted to be no larger than n_msgRegisters:
> 
> ```
>     /* Syscall error/Preemptible section */
>     length = seL4_MessageInfo_get_length(info);
>     if (unlikely(length > n_msgRegisters && !buffer)) {
>         length = n_msgRegisters;
>     }
> ```

OK, get it, thanks! : )
