### ISSUE TITLE
Incorrect documentation for behaviour of Signal with a 0 badge

### ISSUE THREAD

**Issue by philipderrin** [seL4/seL4#112]
The manual's chapter on notifications includes the following statement:

> If no thread is waiting, the `seL4_Signal` operation with an unbadged capability has no effect.

https://github.com/seL4/seL4/blob/468d1c55059a7b5950e4718c2620f663776bd908/manual/parts/notifications.tex#L60

On inspecting the kernel code, there does not appear to be any behaviour in `seL4_Signal` that is conditional on the badge value. So, signalling a notification with a 0 badge _does_ have an effect when there are no waiting threads: it sets the notification state to `Active`, and sets the notification message to 0 if the state was previously `Idle` (leaving it unchanged otherwise).

I suggest either removing this entire paragraph, or replacing it with a note that `seL4_Wait` can return 0 if signalled with an unbadged cap.

**Comment by pingerino** [comment]
Thanks for reporting this. Fixed in c08b8543ae9911232c8b32f43db78ddf68ef9541.
