### ISSUE TITLE
Can uart_drv_getchar(void) be removed from the serial drivers

### ISSUE THREAD

**Issue by andybui01** [seL4/seL4#1131]
The wrapper that calls `uart_drv_getchar()`, `kernel_getDebugChar()`, is never called within the kernel, and there is no syscall equivalent to `SysDebugPutChar`.

It seems as if any serial recv handling by the kernel would have to buffer characters, which is un-ideal anyways. I think serial drivers can be refactored to be purely printing only. This lowers the expectation of future ports to not have to worry about uart getchar implementations.

**Comment by andybui01** [comment]
Ah, I believe this was used to debug capDL in the past, which got removed at some point (https://github.com/seL4/seL4/commit/658e110622375542c4a27782ccc4bb119cd3f071), and now the getchar implementations remain unused, although in the future we might need them for a similar purpose again.

**Comment by Indanz** [comment]
Future ports can just add a dummy function, but I think removing it altogether is fine too.

**Comment by Indanz** [comment]
Closing this as the question has been answered.
