### ISSUE TITLE
Please help to create a repo manifest including toolchains and all these verified os services and componets.

### ISSUE THREAD

**Issue by shangzuoyan** [seL4/seL4#1139]
Dear SeL4,
Why not create a repo manifest to manage all these git repositories? 
This would make it more convenient for an integrated system including all these os services and componets.

Thanks
Roy

**Comment by Indanz** [comment]
Closing this until @shangzuoyan makes it clearer what's currently missing.

**Comment by shangzuoyan** [comment]
Dear Indan,

Thanks a lot,
I have got the right manifest to sync the project sources.

Thanks,
Zuoyan


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
