### ISSUE TITLE
Are there measures in seL4 to deal with Meltdown and Specter vulnerabilities?

### ISSUE THREAD

**Issue by CtrlZ233** [seL4/seL4#1149]
When I read the code I found that seL4 still uses the same page table for kernel and user programs, I wonder if seL4 has a method like KPTI to mitigate this kind of hardware vulnerability?

**Comment by lsf37** [comment]
> When I read the code I found that seL4 still uses the same page table for kernel and user programs, I wonder if seL4 has a method like KPTI to mitigate this kind of hardware vulnerability?

Wether seL4 uses the same page table or not depends on architecture and configuration. For x86, you can configure `KernelSkimWindow` to force a separate kernel page table if you are on a processor that is vulnerable to the Meltdown attack.
