### ISSUE TITLE
is MAX_IRQ correct for tqma8xqp1gb?

### ISSUE THREAD

**Issue by lsf37** [seL4/seL4#1155]
The current value of `MAX_IRQ` for the `tqma8xqp1gb` [is 512](https://github.com/seL4/seL4/blob/ed613d7d490be91f7f164ff98e09d9098de64d6e/src/plat/tqma8xqp1gb/config.cmake#L23). Should it be 511?

The boot code expects to be able to set the irq state of `maxIRQ`, which in this case would mean that the IRQ CNode has to have 2^10 slots with 511 unused slots instead of 2^9.

We're also currently claiming that the `irq` type has 9 bits on aarch64. 512 doesn't fit that, i.e. we'd need to do something about that on the verification side. (All other current platforms fit in 9 bit)

**Comment by lsf37** [comment]
@Indanz do you know more about the `tqma8xqp1gb` setup?

**Comment by Indanz** [comment]
> The current value of `MAX_IRQ` for the `tqma8xqp1gb` [is 512](https://github.com/seL4/seL4/blob/ed613d7d490be91f7f164ff98e09d9098de64d6e/src/plat/tqma8xqp1gb/config.cmake#L23). Should it be 511?

Yes, it should. The highest defined interrupt in the datasheet is `543 - 32 = 511`. The highest non-reserved IRQ is 470.
