### ISSUE TITLE
`physBase` isn't aligned properly on `ARM_HYP`

### ISSUE THREAD

**Issue by nspin** [seL4/seL4#1186]
`physBase` is required to be aligned to `seL4_SuperSectionBits`:

https://github.com/seL4/seL4/blob/c9989664e312d971048f687895d4917758fcfd3b/include/arch/arm/arch/32/mode/hardware.h#L98-L100

On `ARM_HYP`, `seL4_SuperSectionBits = 25`:

https://github.com/seL4/seL4/blob/c9989664e312d971048f687895d4917758fcfd3b/libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/constants.h#L195

However, in `hardware/config.py` the value of `SUPERSECTION_BITS` is hard-coded to `24`, its value on `ARM`:

https://github.com/seL4/seL4/blob/c9989664e312d971048f687895d4917758fcfd3b/tools/hardware/config.py#L48-L51

While this bug may not have caused issues for currently supported platform, I noticed it when testing https://github.com/seL4/seL4/pull/976 on `ARM_HYP`. In this case, `physBase` is set to `2**24` by `hardware/config.py` and the assertion in `hardware.h` fails.

**Comment by lsf37** [comment]
Nice find, and I'm glad that the assert catches it, because that would have been super hard to find at runtime. The value in `config.py` is just wrong, it needs to depend on whether hyp mode is on or not.
