### ISSUE TITLE
document `cmake install` target on docsite

### ISSUE THREAD

**Issue by lsf37** [seL4/seL4#1189]
Should mentioned which files are installed and where to expect them.

**Comment by Ivan-Velickovic** [comment]
Since it's new in the release should it also go somewhere around here? https://docs.sel4.systems/projects/buildsystem/

**Comment by lsf37** [comment]
Yes, good idea. But only when the release comes out -- i.e. we could prepare a PR now, but should not merge it yet.

**Comment by lsf37** [comment]
The CHANGES part is done in #1283, but we should still add some thing to <https://docs.sel4.systems/projects/buildsystem/>. This can be after the release, so I'll leave the issue here open, but mark it as "done" in the release project.

I'll assign it to both of us, so we don't forget about it.

**Comment by lsf37** [comment]
In fact, the sub page <https://docs.sel4.systems/projects/buildsystem/standalone.html> is probably the right location.
