### ISSUE TITLE
Is it possible to port musl directly from libsel4?

### ISSUE THREAD

**Issue by mttbx** [seL4/seL4#1204]
I find that sel4_libs and util_libs contain many things I don't need. Is it possible to just port musl directly from libsel4?
And I noticed that in libsel4muslcsys from sel4_libs there's some callbacks don't be implemented, like sys_set_thread_area. Is it possible to implement it?
I think it will makes sel4 cleaner and easier to be port. Without these, the user can create there own layers.

**Comment by mttbx** [comment]
That's complicated, I'll close this.

**Comment by Indanz** [comment]
This is the seL4 kernel Github repo, please open issues in the appropriate project, in this case probably [seL4/musllibc](https://github.com/seL4/musllibc). User space libraries other than the kernel provided libsel4 are separate projects from the seL4 kernel.

At my previous work, what I did was use the startup task as a bootloader and monitor task which loads our own ELF file which uses standard, unmodified Newlibc (however, we didn't use threading, if you do you'll run into seL4's non-standard TLS register on ARM). That way we could also update our application without restarting the whole system. But other than in the startup task, I didn't use any seL4 user space libraries other than libsel4.

In my opinion, using a heavily modified musl libc which doesn't support embedded use and is written specifically for Linux is a bad idea. Don't get me wrong, it's a good C library, but it isn't a good fit for a different kernel like seL4.

That said, it's a lot of work doing everything yourself and it only makes sense if you have specific system requirements that aren't met by the existing frameworks. I recommend having a look ate [Microkit](https://docs.sel4.systems/projects/microkit/).

As for `sys_set_thread_area()`, you can probably achieve the same with `seL4_TCB_SetTLSBase()`.

**Comment by mttbx** [comment]
Thank you for your reply.
