### ISSUE TITLE
ESR in UserException on AArch64

### ISSUE THREAD

**Issue by philipderrin** [seL4/seL4#123]
Currently, `seL4_Fault_UserException` on ARM has the two data words hard-coded to 0:

https://github.com/seL4/seL4/blob/63ed19c9b7d972eb4af73c666484e277b0d4cf83/src/arch/arm/c_traps.c#L52

This makes sense for 32-bit ARM where this fault is generated by an undef abort, for which the CPU provides no further information.

For AArch64, this fault is used as a catch-all for synchronous aborts that are not otherwise handled (either by the kernel or by generating a different kind of fault). In this case the CPU _does_ provide additional information, in `ESR_ELx`. This is especially useful for trapped system register accesses, where ESR provides enough information for the fault handler to emulate the access.

So, on AArch64, one of the arguments to `handleUserLevelFault` should be changed from 0 to `getESR()`.

This will not change the behaviour for undefined instructions, as the ESR encoding for those is 0.

**Comment by pingerino** [comment]
Done!

https://github.com/seL4/seL4/commit/222b7448c11fbd3b1eb0dfaaad28a0b8f799b45b
