### ISSUE TITLE
priority checks in seL4_TCB_SetSchedParams()

### ISSUE THREAD

**Issue by hexcoder-** [seL4/seL4#1254]
While doing a small review on the user manual, I saw in section 10.3.7.13 (seL4_TCB_SetSchedParams) that parameters `mcp` and `priority` are checked against `authority`, which is fine. But the relation `mcp >= priority` is not enforced, so for example the call would be accepted with authority->priority=10, priority=10, and mcp=9,  thus yielding an inconsistent internal state (i think), where `priority > mcp`.

I consulted the source code for `decodeSetSchedParams` (https://github.com/seL4/seL4/blob/503ad776bcf056f0d2bd1976e2c7cc6b323487d8/src/object/tcb.c#L1326 and the next lines). There are two calls for `checkPriority()`, each against `authority`.

`invokeTCB_ThreadControl`, which is called at the end of `seL4_TCB_SetSchedParams` seems to have the precondition that these values (`mcp` and `priority`) are already checked.

**Comment by Indanz** [comment]
There is nothing wrong with a state where `priority > mcp`, it just means a task is allowed to drop the priority, but not to increase it back to the original level.

**Comment by hexcoder-** [comment]
Thanks, this issue can than be closed.
