### ISSUE TITLE
How to enable smp support on sabre?

### ISSUE THREAD

**Issue by chengshuyi** [seL4/seL4#126]
I followed the [Configuring and building an seL4 project](https://docs.sel4.systems/Developing/Building/Using) and run command `../init_build.sh -DPLATFORM=sabre -DAARCH32=1 -DSMP=1`. However, the `gen_config.h` file which locate at `cbuild/kernel/gen_config/kernel` directory does not include the `ENABLE_SMP_SUPPORT` field but include `#define CONFIG_MAX_NUM_NODES 4`. 

It's weird. Because `config.h` file which locate at `kernel/inlcude` directory define a rule:

```
#if CONFIG_MAX_NUM_NODES > 1 
#define ENABLE_SMP_SUPPORT
#endif
```

Thanks for any advice!

**Comment by kent-mcleod** [comment]
Hi @chengshuyi,
`config.h` is used as a header file in the kernel.  The include structure is that kernel source files can include `config.h`, which then includes `autoconf.h` which then includes `gen_config.h`.  `ENABLE_SMP_SUPPORT` is not defined as a `CONFIG_*` option, but will get set if `CONFIG_MAX_NUM_NODEX > 1` as seen in `config.h`.  To detect SMP support at user level, the test used is normally `CONFIG_MAX_NUM_NODEX > 1`.  Therefore if CONFIG_MAX_NUM_NODES is 4, then SMP support will be enabled on sabre.

**Comment by chengshuyi** [comment]
> Hi @chengshuyi,
> `config.h` is used as a header file in the kernel. The include structure is that kernel source files can include `config.h`, which then includes `autoconf.h` which then includes `gen_config.h`. `ENABLE_SMP_SUPPORT` is not defined as a `CONFIG_*` option, but will get set if `CONFIG_MAX_NUM_NODEX > 1` as seen in `config.h`. To detect SMP support at user level, the test used is normally `CONFIG_MAX_NUM_NODEX > 1`. Therefore if `CONFIG_MAX_NUM_NODES` is `4`, then SMP support will be enabled on sabre.

Thank you! I see.
