### ISSUE TITLE
Does sel4 support cortex-a53 hypervisor?

### ISSUE THREAD

**Issue by chengshuyi** [seL4/seL4#129]
From [sel4 hardware](https://docs.sel4.systems/Hardware/), we can see that it support cortex-a53 arm hyp. However, file `config.cmake` locating at `sel4_test/kernel/src/arch/arm` has a rule for KernelArmHypervisorSupport. Below is the details info.

```
config_option(KernelArmHypervisorSupport ARM_HYPERVISOR_SUPPORT
    "Build as Hypervisor. Utilise ARM virtualisation extensions to build the kernel as a hypervisor"
    DEFAULT OFF
    DEPENDS "KernelArmCortexA15 OR KernelArmCortexA57"
)
```

Thanks for any advice!

**Comment by yyshen** [comment]
Hi, we are integrating an external PR from DornerWorks to enable hypervisor support for A53, and the integration will be done soon.

**Comment by chengshuyi** [comment]
> Hi, we are integrating an external PR from DornerWorks to enable hypervisor support for A53, and the integration will be done soon.

Thanks, Looking forward to that!
