### ISSUE TITLE
x86 VM + FPU Question

### ISSUE THREAD

**Issue by chrisguikema** [seL4/seL4#1307]
I'm in the process of porting a new guest Operating System to run with the camkes-vm on a 64-bit x86 processor. Linux seems to always default to using the x87 FXSAVE FPU settings, while this OS needs to use the newer XSAVE instructions.

Reviewing the Intel manual, the VCPU exits when the guest calls the `xsetbv` instruction. Just to get the guest booting, I basically just jumped to the next instruction in the VMM, and let the guest call the `xsave` and `xrestore` functions, knowing the applications aren't going to use the FPU. 

But now that I have the new OS running, I think I actually need to tackle this problem.

Would the seL4 VCPU implementation have a problem with a guest using the XSAVE instructions?

**Comment by Indanz** [comment]
It shouldn't: XSAVE is an unprivileged instruction, you can do it even in user space. Just make sure `CR4.OSXSAVE[bit 18] = 1`, see [here](https://www.felixcloutier.com/x86/xsave).
