### ISSUE TITLE
sel4-kernel-loader-add-payload drop symbol information

### ISSUE THREAD

**Issue by BDUG** [seL4/seL4#1313]
After the usage of sel4-kernel-loader-add-payload all object information for later debugging is gone. Is there any way to debug my rust program, using sel4-rust?

**Comment by Indanz** [comment]
There's a chance that binaries with debug symbols are left in the build directory, try using those.

```
find build -name '*.elf'
```

**Comment by BDUG** [comment]
@Indanz many thanks for your feedback. Let me go into details.

In my understanding the gdb remote debugging requires certain sections of the ELF file to map on client side the source code. with `objdump -h ELF-file` I checked the kernel.elf as well as my application specific ELF file. both list section I expect for the debug. After the call of `sel4-kernel-loader` in correlation with `sel4-kernel-loader-add-payload` the resulting ELF-file no longer contains respective sections. Is there a way to keep the information necessary for later debugging?

**Comment by nspin** [comment]
I've addressed this issue in https://github.com/seL4/rust-sel4/issues/179
