### ISSUE TITLE
Arm FVP DTB Issue

### ISSUE THREAD

**Issue by userid0x0** [seL4/seL4#1320]
Hi,

I tried to boot SeL4 on a ARM FVP model. I noticed a inconsistency of the DTS/DTB shipped with SeL4 and the code. On top the DTB of the Kernel/TF-A is much different than the DTS/DTB part of SeL4.

Basically the code [2,3] references `/soc/timer@1c110000` & `/soc/timer@1c120000` but this path doesn't exist in the DTS/DTB [1]. For testing I patched `/timer@1c110000` & `/timer@1c120000` .

[1] https://github.com/seL4/seL4/blob/master/tools/dts/fvp.dts
[2] https://github.com/seL4/util_libs/blob/master/libplatsupport/src/plat/fvp/ltimer.c#L98
[3] https://github.com/seL4/util_libs/blob/master/libplatsupport/plat_include/fvp/platsupport/plat/sp804.h#L17

**Comment by Indanz** [comment]
There seem to be many ARM FVP models, the one is seL4 is derived from an intermediate build stage of Linux kernel and is based on foundation-v8-gicv3.dts.

According to [Fast Models Fixed Virtual Platforms (FVP) Reference Guide](https://documentation-service.arm.com/static/5f4d2d54ca7b6a3399375e89), Version 11.4, page 30:

```
Dual-Timer 0, SP804 0x00_1C11_0000 64KB 0x00_1C11_FFFF S/NS
Dual-Timer 1, SP804 0x00_1C12_0000 64KB 0x00_1C12_FFFF S/NS
```

And according to the [ARM website](https://developer.arm.com/documentation/100961/1127/Programming-Reference/Foundation-Platform-memory-map), it's also:

```
0x00_1C11_0000	0x00_1C11_FFFF	Dual-Timer 0, SP804	64KB	S/NS
0x00_1C12_0000	0x00_1C12_FFFF	Dual-Timer 1, SP804	64KB	S/NS
```

Which exact variant of all the FVP models were you trying to use? If it's not the Foundation Model, you can use the `KernelCustomDTSOverlay` config option to tweak the seL4's DTS input according to your exact platform and use case.

**Comment by userid0x0** [comment]
I am using the AEM (Architecture Envelope Model), but this is not the problem here.
The code in [2,3] does not work with the SeL4 internal DTB [1] as the path (I hope I use the correct term) is incompatible. Please note the leading `/soc` which doesn't exist in [1].

**Comment by Indanz** [comment]
Ah, yes, you're right, that seems plain wrong. It's broken by [this util_libs](https://github.com/seL4/util_libs/commit/ef1dfb7da52b8324281ee6999951bf603d44bdd7) commit. It mentions:

> All platforms pass build
> - Except for fvp which doesn't have a machine handy,
>   the other 3 platforms pass sel4test

So it hasn't been tested for fvp and no one noticed it breaking for 4 years. :-(

Can you create a PR for util_libs? I'll should see it pop up and then I'll merge it over there. Give me a ping if I miss it.
