### ISSUE TITLE
GICV3: ‘volatile struct gic_dist_map’ has no member named ‘sgi_control’

### ISSUE THREAD

**Issue by chengshuyi** [seL4/seL4#136]
https://github.com/seL4/seL4/blob/051d32beab6753eb9cc3f61b91467bd612b72408/src/arch/arm/machine/gic_v3.c#L344

https://github.com/seL4/seL4/blob/051d32beab6753eb9cc3f61b91467bd612b72408/src/arch/arm/machine/gic_v3.c#L349

struct gic_dist_map of gicv3 has no member named `sgi_control`. And i think it should be `sgir`.

**Comment by kent-mcleod** [comment]
Fixed in https://github.com/seL4/seL4/pull/142
