### ISSUE TITLE
Compile failed for RPi3

### ISSUE THREAD

**Issue by dr-bonez** [seL4/seL4#156]
Running ninja on Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-55-generic x86_64)
init-build was run with `-DPLATFORM=rpi3` and `-DAARCH32=1`.

[error.log](https://github.com/seL4/seL4/files/3664643/error.log)

Any idea what I'm missing?

**Comment by nomadeel** [comment]
From looking at the logs, it seems you're building for sel4test. Just to confirm, you are using the latest version of the manifest from [here](https://github.com/seL4/sel4test-manifest) right?

Also, have you downloaded all the Ubuntu and Python related dependencies listed [here](https://docs.sel4.systems/HostDependencies)? From the error log, it seems that our Python hardware header generation scripts aren't working as intended.

**Comment by nomadeel** [comment]
Also, could you direct any other additional questions that are similar to this to the [seL4 mailing list](https://docs.sel4.systems/HostDependencies)?
