### ISSUE TITLE
Dead links in README.md

### ISSUE THREAD

**Issue by watbe** [seL4/seL4#17]
Nothing major -- links 2, 3 reference dead pages on the sel4.systems website, and link 5 is actually a redirect. 

For your convenience here's a patch to correct the links.

Patch: https://github.com/watbe/seL4/commit/74276ce9ccd7489a06bc8cfd90aa0fc4a3d429cc.patch

**Comment by lsf37** [comment]
Thanks for spotting and reporting that.

For some reason we seem to have missed the email notification on this issue, but the links are fixed now in the internal repo. We're working on a merge for version 1.4 at the moment, so it might be another day or two until it is pushed out.

**Comment by lsf37** [comment]
The fixes are now pushed out. Thanks again for reporting the dead links.
