### ISSUE TITLE
Bug report: x86_64 PCID feature test wrong

### ISSUE THREAD

**Issue by laokz** [seL4/seL4#174]
Merry Christmas!

https://github.com/seL4/seL4/blob/master/src/arch/x86/64/head.S#L135 used wrong mask 0x800000 to test x86_64 PCID feature.

According to Intel® 64 and IA-32 ArchitecturesSoftware Developer’s Manual Table 3-10(https://software.intel.com/sites/default/files/managed/ad/01/253666-sdm-vol-2a.pdf), bit 17 is PCID flag, its mask is 0x20000. So the above statement should be:
```
    andl $0x20000, %ecx
```

Regards.

**Comment by yyshen** [comment]
@laokz Nice catch. Thanks!

**Comment by yyshen** [comment]
#209
