### ISSUE TITLE
Bug report: low level console io error

### ISSUE THREAD

**Issue by laokz** [seL4/seL4#176]
Happy New Year again :-)

Some low level console io functions like printf have bugs in file https://github.com/seL4/seL4/blob/master/src/machine/io.c.

1.  print_unsigned_long_long() will print leading 0s of lower(right) 4 bytes after printing upper(left) 4 bytes. When all lower parts are 0s, it will break out in line 136 after testing shifts == 8. That means all lower parts have been done. But line 142 print_unsigned_long(lower, ui_base) will still be executed-printing another 0. Wrong. Line 136 should be:
```
    if (shifts == 7) {    // at least left 1 number to allow the next statement to deal
```

2. Like "%4d" format, vprintf() will print padding spaces after printing the argument value in line 268:
```
    n += print_spaces(nspaces - n);
```
But as nspaces counting padding request and n counting total printed, (nspaces - n) has no means. And most likely nspaces will be less than n. To patch this, it should append a temporary varible to record original n just after getting nspaces, then after printing the arg value:
```
    n += print_spaces(nspaces - (n - orig_n));
```
Here, print_spaces() should also be fixed.

3. In line 32 of print_spaces(), it should return i instead of n(declare i outside for loop). Thus, whenever n>=0 or n<0, the return value will all be the correct result.

4. In x86_64, sizeof(long)==8. When printf("%lu",l), the biggest value will be 20 decimals long. Now in line 72 of print_unsigned_long(), it just gives the buffer size sizeof(unsigned long) * 2 + 3 == 19.  So buffer maybe overflow.

Wish these helpful.

Regards.

**Comment by kent-mcleod** [comment]
Hi @laokz, this issue could be generalised to reporting that the kernel's printf implementation is considered incomplete, IE it doesn't support certain common modifiers such as `%c` also.  We could consider using an external baremetal implementation of sprintf instead that would also fix many other formatting edge cases such as the ones that you have identified.

**Comment by laokz** [comment]
Thanks. Yes, kernel's printf only supports partial standard format. As an auxiliary debug/log api, maybe it is easy to do a little fixes to make it work well.

**Comment by laokz** [comment]
This file changed a lot. I think the issues should not exist.
