### ISSUE TITLE
Bug report: exceeded memory maps warning typos

### ISSUE THREAD

**Issue by laokz** [seL4/seL4#177]
Hi,

In boot stage, when memory map entries exceed limitation, https://github.com/seL4/seL4/blob/master/src/arch/x86/kernel/boot_sys.c#L572 will give a warning. The warning used a false format "%zd", it could be "%d".

And the preceding alternation to multiboot_mmap_length is too early, for the printf wants its original value. Thus line 571 should follow the printf statement.

Regards.

**Comment by axel-h** [comment]
Thanks. Are you willing to make a PR with a fix for this?

**Comment by laokz** [comment]
My pleasure. I'll try. It seeds that "%zd" formatter already worked.
