### ISSUE TITLE
Understand PPTR_USER_TOP on x64

### ISSUE THREAD

**Issue by xoofx** [seL4/seL4#183]
Hello,
I'm a bit confused by the comment and the const address of PPTR_USER_TOP:

https://github.com/seL4/seL4/blob/0e62bc3a81c5f3c74e9615d990eaa95a19800b21/include/plat/pc99/plat/64/plat_mode/machine/hardware.h#L53-L60

Why is it saying that it is 1 before sign extension, as I would expect `0x7FFFFFFFFFFFFFFF` for 64 bits and not `0x7FFFFFFFFFFF` in that case. Am I missing something?

**Comment by xurtis** [comment]
Hi Alexandre,

x86_64 only supports a 48-bit (9+9+9+9+12) address space rather than an address space where all 64 bits can be used to refer to virtually mapped memory.

The case is similar for 64-bit RISC-V with 39-bit address spaces and aarch64 with a pair of 48-bit address ranges.

**Comment by kent-mcleod** [comment]
Here is some extra background in case it's helpful:

On x86_64 the 48 bit virtual address space can be thought of as ranging from [-128TB, (128TB-1)], or from 0 to (128TB -1), and then from (2^64 - 128TB) to 2^64.  Any address outside this range is considered invalid, or non-canonical.  In practice this means that when an address increases from 128TB-1 to 128TB, the hardware sign extends from the 47th bit and the value becomes -128TB. This typically ends up also being the point where User addressable virtual memory stops, and protected/kernel addressable memory starts.  One of the benefits of this strategy is that as new hardware supports larger virtual address ranges, the additional addressable memory grows inwards and special addresses in the (2^64 - 128TB) to 2^64 range don't need to be changed.  See this document (https://www.kernel.org/doc/Documentation/x86/x86_64/mm.txt) for an example of the Linux memory map for both 48bit and 56bit ranges.  seL4 only supports 48bit virtual memory translations for x86_64 at the moment.

**Comment by xoofx** [comment]
Oh right, makes complete sense, thank you for the details!
