### ISSUE TITLE
reference manual of 'CSpace Addressing' better clear off confusing

### ISSUE THREAD

**Issue by laokz** [seL4/seL4#187]
https://github.com/seL4/seL4/blob/master/manual/parts/cspace.tex#L430 gives a good example to explain CSpace addressing. It is clear enough to introduce the addressing concept, but with coding practice it's better to make them more precise.

When passing address arguments in multi-level CNodes, the index field, i.e. its _address_, must right aligned the significant bits according its depth. In above example, **L2 CNode Cap**'s _address_ should be 0x00F along with depth 12, **L3 CNode Cap**'s should be 0x00F000 along with depth 24. Otherwise lookup will fail. Further, all  _addresses_ are relative to the base CNode, so be variable.

**Comment by kent-mcleod** [comment]
This issue was finally resolved by https://github.com/seL4/seL4/pull/320.  Feel free to reopen or open a new issue if you feel that this section in the manual is still confusing.
