### ISSUE TITLE
x86 asm no rule to make.

### ISSUE THREAD

**Issue by gdisneyleugers** [seL4/seL4#19]
make: *** No rule to make target `src/arch/x86/machine_asm.S', needed by `src/arch/x86/machine_asm.s'.

**Comment by AdrianDanis** [comment]
Hi @gdisneyleugers 

Can you please provide some context or steps to reproduce this issue.

Thanks,
Adrian

**Comment by zhicheng** [comment]
@gdisneyleugers I might has same problem, i wrote a patch. try update master branch.
