### ISSUE TITLE
Mutual exclusion violation due to WMM bugs

### ISSUE THREAD

**Issue by JonasOberhauser** [seL4/seL4#207]
We have found two separate WMM bugs in the seL4 BKL which each lead to mutual exclusion violations.

The first is that the `sel4_atomic_exchange` which publishes the node in `clh_lock_acquire` must ensure that the initialization of the node to value `CLHState_Pending` is visible by using release ordering.
This is fixed in #199 

The second is that `try_arch_atomic_exchange` on ARM ignores the release ordering passed to it. The problem is that the release barrier is inserted after the `ST_EX`, which is too late; to ensure that the release ordering is correctly implemented, the `ST_EX` needs to be performed after a release barrier.
We suggest two alternative fixes for this. 
1. The first is #205, which simply fixes the barrier placement inside `try_arch_atomic_exchange` on ARM.
2. The second is #206 which makes the weak behavior of `try_arch_atomic_exchange` explicit by removing the (anyways not correctly implemented) memory order arguments and turns it fully relaxed. The memory ordering is accounted for in `sel4_atomic_exchange`, which means that the barriers are pulled out of the loop. This should provide better latency for handling interrupts while the `try_arch_atomic_exchange' fails.

**Comment by yyshen** [comment]
#206 merged.
