### ISSUE TITLE
Real performance comparisons

### ISSUE THREAD

**Issue by fresheneesz** [seL4/seL4#21]
I imagine this isn't the right place for this, but i can't find a better one.

I see the performance comparisons at http://l4hq.org/docs/performance.php are run on all different processors. In its current form, the performance numbers here are completely useless. It would be very informative to have real performance benchmarks where the exact same processor is used for every OS in comparison. Otherwise, what am I supposed to do with those number?

**Comment by lsf37** [comment]
Please see the response on the seL4-devel mailing list: http://sel4.systems/pipermail/devel/2016-April/thread.html

It's the right place to continue the discussion, so will close here on the tracker. (You can subscribe from https://sel4.systems/lists/listinfo/devel )
