### ISSUE TITLE
issue when building for tegra k1

### ISSUE THREAD

**Issue by sei-jdelange** [seL4/seL4#22]
Hi,

When trying to build for the Tegra K1, I got the following issue. To reproduce the issue:
1. make beagle_debug_xml_defconfig
2. make oldconfig
3. make menuconfig edit the platform and select the Tegra
4. make

In file included from /home/sel4/tegra-test/stage/arm//include/platsupport/io.h:24:0,
                 from /home/sel4/tegra-test/stage/arm//include/platsupport/timer.h:17,
                 from /home/sel4/tegra-test/libs/libplatsupport/src/arch/arm/generic_timer.c:18:
/home/sel4/tegra-test/stage/arm//include/platsupport/clock.h:27:36: fatal error: platsupport/plat/clock.h: No such file or directory
compilation terminated.

**Comment by AdrianDanis** [comment]
Hi @sei-jdelange,

The user space support for the TK1 did not get fully pushed out yet (hence there is no direct config for it in sel4test). It is completed and working internally, just our regressions are failing so changes haven't been pushed out. This should get fixed up in a day or two.

**Comment by AdrianDanis** [comment]
@sei-jdelange as far as I can tell this has been fixed. Can you confirm and close this if it is fixed for you?

**Comment by sei-jdelange** [comment]
I confirm!
