### ISSUE TITLE
enum multiple definitions reported by gcc 10

### ISSUE THREAD

**Issue by yyshen** [seL4/seL4#239]
gcc 10 reports multiple enum definition errors for the ones in constants.h files. riscv64 and x86 gcc 10 were used. aarch64 gcc 10 is like to have the same issue.

**Comment by mbrcknl** [comment]
I believe this should be fixed by https://github.com/seL4/seL4/pull/231, which will hopefully be merged soon.

**Comment by mbrcknl** [comment]
> I believe this should be fixed by #231, which will hopefully be merged soon.

Sorry, I meant https://github.com/seL4/seL4/pull/230.

**Comment by yyshen** [comment]
Just had a look at that PR. It includes arm, x86, and riscv. I thought it was for riscv only. Please close this when that PR is merged.
Thanks

**Comment by mbrcknl** [comment]
Closing, since #230 has effectively been merged.

**Comment by walle-whale** [comment]
Might be a bit late, was there any discussion about doing something like this instead?
```
enum seL4_DebugException_Msg {
    seL4_DebugException_FaultIP,
    seL4_DebugException_ExceptionReason,
    seL4_DebugException_TriggerAddress,
    seL4_DebugException_BreakpointNumber,
    seL4_DebugException_Length,
    SEL4_FORCE_LONG_ENUM(seL4_DebugException_Msg)
};
```
