### ISSUE TITLE
Manual references "system criticality" without defining it

### ISSUE THREAD

**Issue by sorear** [seL4/seL4#240]
https://github.com/seL4/seL4/blob/master/manual/parts/threads.tex#L338-L341

**Comment by lsf37** [comment]
Indeed. I think we might actually have removed that concept of system criticality, which means this is just left over. @pingerino can you confirm?

**Comment by pingerino** [comment]
Yes, criticality was removed. Sorry I thought I'd culled all the left over manual references.

**Comment by lsf37** [comment]
No worries, will remove the paragraph in #241.
