### ISSUE TITLE
Serial output on x86 version 3.1.0

### ISSUE THREAD

**Issue by alex-ab** [seL4/seL4#27]
I compiled the sel4 3.1.0 kernel [0]

```make ARCH=x86 PLAT=pc99 SEL4_ARCH=ia32 DEBUG=y```

and started afterwards it by

```qemu-system-i386 -kernel kernel.elf -serial stdio```

but get no output at all.

Doing the same with sel4 2.1.0 [1] and 3.0.1 leads to some kernel messages.

Also on native x86 hardware I get on 2.1.0 and 3.0.1 output, but nothing for the
3.1.0 kernel. Also tried with recent git master [2]. 

Additionally I git bisected between 3.0.1 and 3.1.0 and beginning with commit 541289a32603cee8242b5360b05e8f0c52795433 there is no output anymore.

[0] git 8150e914c377bb2d94796c6857d08f64973a7295
[1] git 0115ad1d0d7a871d637f8ceb79e37b46f9981249
[2] git 13709e5ac16fc0ce711bfe99b411408c66e7b268

**Comment by AdrianDanis** [comment]
The commit you have identified separates out the idea of a generic 'debug' build from other either debug or performance monitoring facilities. In this case to enable output you could be with

```make
make ARCH=x86 PLAT=pc99 SEL4_ARCH=ia32 DEBUG=y CONFIG_KERNEL_EXTRA_CPPFLAGS="-DCONFIG_PRINTING=y -DCONFIG_USER_STACK_TRACE_LENGTH=16"
```

This is a somewhat awkward invocation, but the kernel Makefile is not exactly targeted at doing stand alone compilation.

**Comment by alex-ab** [comment]
I see. For Genode we want to compile just the kernel. After the initial steps to upgrade to 3.1.0 there was no output anymore, and I just wondered what I could have done wrong ;-). Now I get the messages again. Maybe the README.md should be adjusted, to reflect the change or describe what/that "DEBUG=y" encompasses (so, no serial output ;-). Thanks!

**Comment by AdrianDanis** [comment]
Yes that is a good point on the README, I will update this
