### ISSUE TITLE
x86: support to read out serial i/o ports from BIOS data area

### ISSUE THREAD

**Issue by alex-ab** [seL4/seL4#28]
On Genode/x86 we use for all of our 7 supported x86 micokernels the BIOS data area to read out the serial configuration. This eliminates for us the need to manually finding out the I/O ports, which is especially handy on native machines you don't have next to you. Also the support of external users becomes comfortable since most the time the serial output 'just' works. We combine this mechanism with a small chained bootloader like bender [0, 1] that scans for PCI serial cards or/and Intel AMT SerialOverLine, writes it to the BIOS data area and then starts the actual microkernel.

What is your opinion about adding this BDA feature to seL4  in general ?

https://github.com/alex-ab/genode/commit/4c1fe8b2dbe4d7fed4c9f60bfa00822621e3f333 depicts the required changes, we currently apply manually to our Genode/seL4 version. (I decided for now to add extra cmdline options, which however are not strictly necessary for us.)

[0] https://github.com/genodelabs/genode/issues/768
[1] https://github.com/genodelabs/genode/issues/1625

**Comment by AdrianDanis** [comment]
Adding support for reading from the BDA sounds like something we should definitely do. In regards to specifics of implementation I would probably just make the value from the BDA to be the default and treat the console_port cmdline as an override.

**Comment by alex-ab** [comment]
Ok, please try/review d95f10a416dfa240257e35742e5d3589162afd71. The signed CLA has been sent to your licensing email some minutes ago.

**Comment by AdrianDanis** [comment]
This commit looks great to me. I'll pull it in and it should appear once it gets through CI
