### ISSUE TITLE
Remove redundant code line

### ISSUE THREAD

**Issue by berkus** [seL4/seL4#285]
[This line](https://github.com/seL4/seL4/blob/79da079239af8ac55c3e2d8f944c3f352ee52a68/src/object/untyped.c#L286) seems unused.

**Comment by lsf37** [comment]
That does indeed look unused. Let me check the proofs if it is used for anything there, but I doubt that it is.

**Comment by lsf37** [comment]
I can confirm that it's fine to remove this line, and have put up a corresponding set of seL4 and proof PRs, which should show up once they are through the pipeline.

**Comment by lsf37** [comment]
Line now removed!

**Comment by lsf37** [comment]
Thanks again for spotting this and reporting it!

**Comment by berkus** [comment]
🙇
