### ISSUE TITLE
[virt] Renamed intc device tree node for qemu-arm-virt platfom

### ISSUE THREAD

**Issue by adrianastancu471** [seL4/seL4#292]
Hello,

In commit [Updated to qemu 3.1](https://github.com/seL4/seL4/commit/a1d1124de9dc6a2559157d04b72821942313ea3a) the device tree node /intc was changed and now the init_build script throws the following error: 
`build-qemu-virt/kernel/kernel.dtb: ERROR (path_references): Reference to non-existent node or label "/intc@8000000"`
Shouldn't this be only `/intc` instead of `/intc@8000000`?

**Comment by kent-mcleod** [comment]
The qemu-arm-virt seL4 platform uses a device tree generated by first calling a command like: `qemu-system-aarch64 -machine virt,dumpdtb=foo.dtb,virtualization=off -m 1024 -cpu cortex-a53 -nographic`.  qemu, with a version >= 3.1, names the interrupt controller node `/intc@8000000` and so the name was updated in the overlay dts.

Which version of Qemu are you using? If the node names that are used for `virt` aren't consistent then we may need a better way of constructing the overlay.

**Comment by adrianastancu471** [comment]
You are right, I have 2.11.1 version so that's why I needed the name of the node without the address.
