### ISSUE TITLE
Building Hello-World tutorial on MacOS X 10.15.7

### ISSUE THREAD

**Issue by jhu960213** [seL4/seL4#295]
Hello,

I'm following along with the tutorial for building a simple sel4 hello-world project. This is the tutorial I'm following: https://docs.sel4.systems/Tutorials/hello-world.html 

When I try to perform ./init --tut hello-world in another folder to try to build this tutorial with CMake I encountered the following error. Please see attached image below. 

![Screen Shot 2021-01-25 at 6 03 51 PM](https://user-images.githubusercontent.com/20133323/105777071-b76ac580-5f37-11eb-95ac-4c769594e1e5.png)

I typed $cmake CMakeLists.txt in the hello-world folder for the above error to show up. Also, this was after I had fixed the CMAKE_C_COMPILER & CMAKE_CXX_COMPILER errors from the first invocation of ./init --tut hello-world. I simply just added two lines at the top of CMakeLists.txt like this and I think it fixed those:

set(CMAKE_C_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc")
set(CMAKE_CXX_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++")

Here is the attached photo of how I added those two lines:
![Screen Shot 2021-01-25 at 6 14 44 PM](https://user-images.githubusercontent.com/20133323/105777923-4af0c600-5f39-11eb-8124-625c93e80a14.png)

I'm not sure if this broke something else but cmake didn't generate anymore "couldn't find c compiler errors". I'm stuck at the error shown in the screen shot. Can someone please advise on what to trouble shoot next? Thanks!

**Comment by lsf37** [comment]
Sorry, this has been sitting here unanswered for quite a while. Building seL4 on MacOS directly is not supported by the current build systems.

It's probably not far off, but currently it doesn't work yet. My recommendation would be to use [docker] and one of the [docker images] we provide to build on MacOS (that's what I'm using personally). The other option is to run Linux in a VM and build there.

[docker]: https://www.docker.com/products/docker-desktop
[docker images]: https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles
