### ISSUE TITLE
Test Hypervisor support with Cortex-A72

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#299]
We are about to add RasPi4 support, which has a Cortex-A72. It still needs to be tested that seL4 Hypervisor support with Cortex-A72 works as expected, that is why we hesitate to add `KernelArmCortexA72` at `config_option(KernelArmHypervisorSupport ARM_HYPERVISOR_SUPPORT ...)`. Has anybody testest this on a Cortex-A72 already?

**Comment by nspin** [comment]
I have been running seL4 as a hypervisor on the RPi 4 without issues.

(using [this branch](https://gitlab.com/arm-research/security/icecap/sel4))

**Comment by axel-h** [comment]
great! Do you plan to make a PR from this branch?

**Comment by nspin** [comment]
From what I can tell, our branch doesn't have any changes that the one in #293 doesn't already have.

The [project](https://gitlab.com/arm-research/security/icecap/icecap/) that our branch is for doesn't make use of the rest of the seL4 software ecosystem, so we haven't gone to the length of adding the Raspberry Pi 4 support to sel4test and its supporting libraries. I figured that a PR adding support for a new platform to the kernel would be unwelcome without the corresponding additions to sel4test's dependencies.

However, I'm happy to do whatever with our branch that would be useful upstream!

**Comment by sethlei** [comment]
I've been trying to get seL4test and seL4bench to run on my RPi4 for about two weeks now. I haven't been able to get it to work. So, I'm really curious about what @nspin did to make his version work. When I checked out his project, I got a build error with the Docker container.

I believe @nspin  did not use the EFI version produced by the current build system. If you did, which EFI environment did you use for the RPi4? Is there an official EFI environment seL4 recommends using?

Alternatively, is there a way to build something like seL4test without making into an EFI, and instead use an ELF like the RPi3 version did? U-boot would then work, and the documentation for getting the RPi4 version to work would be similar to the RPi3 version.

**Comment by nspin** [comment]
We are using U-Boot. [This](https://gitlab.com/arm-research/security/icecap/icecap/-/blob/3c8cee4a4351a2228f9d8719b50c49815ecd54a6/nix/scope/plat-utils/rpi4/default.nix) build system file contains the relevant details and configuration. I'm happy to answer any questions about our setup.

I'm also curious about the build failure you observed. If you'd like to build our project as a reference, feel free to raise an issue [over there](https://gitlab.com/arm-research/security/icecap/icecap) or reach out directly and we can get you up and running.

**Comment by ProdigyYanng** [comment]
I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.

**Comment by ProdigyYanng** [comment]
> We are using U-Boot. [This](https://gitlab.com/arm-research/security/icecap/icecap/-/blob/3c8cee4a4351a2228f9d8719b50c49815ecd54a6/nix/scope/plat-utils/rpi4/default.nix) build system file contains the relevant details and configuration. I'm happy to answer any questions about our setup.
> 
> I'm also curious about the build failure you observed. If you'd like to build our project as a reference, feel free to raise an issue [over there](https://gitlab.com/arm-research/security/icecap/icecap) or reach out directly and we can get you up and running.

I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.

**Comment by Ivan-Velickovic** [comment]
I've successfully run sel4test with the following configurations:
```
../init-build.sh -DPLATFORM=rpi4 -DAARCH64=1 -DRPI4_MEMORY=4096 -DARM_HYP=1
../init-build.sh -DPLATFORM=rpi4 -DAARCH64=1 -DRPI4_MEMORY=4096 -DARM_HYP=1 -DRELEASE=1
```

I would add them to CI but the following issue needs to be resolved first https://github.com/seL4/util_libs/issues/171.

I know that TII has done a bunch of virtualisation work using the RPi4.

I think that means that this issue can be closed.

**Comment by Indanz** [comment]
Cortex A72 was added to the config_option list by commit 84e850999725c1c56735859752e0b920f932c471 in July 2021.

**Comment by axel-h** [comment]
> Cortex A72 was added to the config_option list by commit [84e8509](https://github.com/seL4/seL4/commit/84e850999725c1c56735859752e0b920f932c471) in July 2021.

This commit added A55, the A72 was added there in [2a0e5a2a](https://github.com/seL4/seL4/commit/2a0e5a2a1fbbb6706e79cf12d0efd7f1004b3389)

**Comment by Indanz** [comment]
I was a bit hasty when going through git blame, I just checked if A72 was there. That commit was in March, so even earlier.
