### ISSUE TITLE
master branch does not compile with fastpath disabled and hypervisor enabled on ARM

### ISSUE THREAD

**Issue by agacek** [seL4/seL4#31]
Compiling the seL4 kernel on ARM with hypervisor support and fastpath disabled produces a linker error about the function slowpath missing. The definition of this function is guarded by an #ifdef FASTPATH:

  https://github.com/seL4/seL4/blob/master/src/arch/arm/32/hyp_traps.S#L286

If I move it out of the #ifdef block, everything compiles and links.

**Comment by heshamelmatary** [comment]
Hi agacek. 
Thanks for reporting this issue. There is already a fix for this, hopefully will get it merged next week.

**Comment by heshamelmatary** [comment]
Fixed in 778043a73ceeaa250b1cf11187f28127e76a2e83
