### ISSUE TITLE
CI action license-check fails in python setup.py egg_info

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#315]
When rebasing my branches, I get the CI action `license-check` failing in `python setup.py egg_info`, see https://github.com/axel-h/seL4/actions/runs/617323145
```
Run seL4/ci-actions/license-check@master
  with:
    action_name: license-check
/home/runner/work/_actions/seL4/ci-actions/master/js/../license-check/steps.sh
Setting up
  Installing python 3.8
  update-alternatives: using /usr/bin/python3.8 to provide /usr/bin/python (python) in auto mode
  update-alternatives: using /usr/bin/python3.8 to provide /usr/bin/python3 (python3) in auto mode
  Python 3.8.0
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fkzj7b0d/launchpadlib/
  Error: Action license-check failed.
```

**Comment by lsf37** [comment]
That is a very strange error. You'd think that either it installs under python 3.8 or it doesn't.

Is this intermittent or does it always happen? Have you tried rerunning the job?

**Comment by axel-h** [comment]
Could the issue be that this run was triggered by updating the master branch on my fork to the latest master from upstream? I've not seen this error anywhere else. So let's see what happen when I fetch ne next update from master.

**Comment by axel-h** [comment]
Here is happened again when updating master in my fork: https://github.com/axel-h/seL4/actions/runs/621171410

**Comment by kent-mcleod** [comment]
This error doesn't seem to have reoccurred? So I'll close this issue for now.
