### ISSUE TITLE
Idle thread runs with async aborts enabled

### ISSUE THREAD

**Issue by philipderrin** [seL4/seL4#33]
The idle thread uses the hard-coded CPSR value `PMODE_IDLE`, which does not mask FIQs or async aborts. If an async abort is pending, the kernel will fault as soon as the system becomes idle.

I see this fault happening on i.MX6Q, presumably triggered by a bad device register access in either the loader or the kernel's serial or timer drivers. Depending on the platform it may also be possible to deliberately trigger it from a user thread that has device registers mapped.

This was fixed before by commit a5f61c7, but it looks like the fix was lost in a merge with the hyp support branch. Also, the `CPSR_IDLETHREAD` value added by that commit has not been updated for hyp; it should use `PMODE_IDLE` instead of `PMODE_SYSTEM`.

**Comment by AdrianDanis** [comment]
Thanks for noticing @philipderrin. Will fix this up

**Comment by jdub** [comment]
Just in case anyone hits this and has also stumbled upon the ["Wandaboard port"](https://sel4.systems/pipermail/devel/2015-March/000324.html) thread on the devel@ list… this looks like the same issue. The referenced fix was committed two days after that thread.

I brought those fixes back to the hyp-ed up 3.2.0 tag with this change:

```diff
diff --git a/include/arch/arm/arch/32/mode/machine/registerset.h b/include/arch/arm/arch/32/mode/machine/registerset.h
index 87abb58..75891f1 100644
--- a/include/arch/arm/arch/32/mode/machine/registerset.h
+++ b/include/arch/arm/arch/32/mode/machine/registerset.h
@@ -34,7 +34,7 @@
                              | CPSR_EXTRA_FLAGS   )

 #define CPSR_IDLETHREAD      ( PMASK_FIRQ         \
-                             | PMODE_SYSTEM       \
+                             | PMODE_IDLE         \
                              | CPSR_EXTRA_FLAGS   )

 /* Offsets within the user context, these need to match the order in
diff --git a/src/arch/arm/32/kernel/thread.c b/src/arch/arm/32/kernel/thread.c
index 44ccdb8..a9af577 100644
--- a/src/arch/arm/32/kernel/thread.c
+++ b/src/arch/arm/32/kernel/thread.c
@@ -26,7 +26,7 @@ Arch_switchToThread(tcb_t *tcb)
 BOOT_CODE void
 Arch_configureIdleThread(tcb_t *tcb)
 {
-    setRegister(tcb, CPSR, PMODE_IDLE);
+    setRegister(tcb, CPSR, CPSR_IDLETHREAD);
     setRegister(tcb, LR_svc, (word_t)idleThreadStart);
 }

```

However, I'm still seeing the same issue as in that old Wandaboard thread, but on my element14 i.MX6Q:

```
## Starting application at 0x20000100 ...

ELF-loader started on CPU: ARM Ltd. Cortex-A9 r2p10
  paddr=[20000100..2029441f]
ELF-loading image 'kernel'
  paddr=[10000000..10033fff]
  vaddr=[e0000000..e0033fff]
  virt_entry=e0000000
ELF-loading image 'sel4test-driver'
  paddr=[10034000..103aefff]
  vaddr=[10000..38afff]
  virt_entry=1ccfc
Enabling MMU and paging
Jumping to kernel-image entry point...

Bootstrapping kernel
Caught cap fault in send phase at address 0x0
while trying to handle:
vm fault on data at address 0x1380004 with status 0x1c06
in thread 0xffdfad00 "rootserver" at address 0x1ccfc
With stack:
0x0: INVALID
...
```

**Comment by jdub** [comment]
Hold on.

```
#ifdef DEBUG
#define CPSR_EXTRA_FLAGS 0
#else
#define CPSR_EXTRA_FLAGS PMASK_ASYNC_ABORT
#endif
```

Should async abort always be masked for the idle thread? Would the following change be wholly inappropriate?

```diff
#define CPSR_IDLETHREAD      ( PMASK_FIRQ         \
                             | PMODE_IDLE         \
-                             | CPSR_EXTRA_FLAGS   )
+                             | PMASK_ASYNC_ABORT  )
```

**Comment by jdub** [comment]
Hmph, doesn't seem to help with my suspiciously similar looking problem though, even after a `make clean` cycle.

**Comment by jdub** [comment]
\*facepalm\* Using the ERTOS u-boot *just like the documentation told me to do* sorted me out. I'll have to figure out why. (It's handy to have a fresh u-boot in order to boot recent Linux kernels.)

I see the CPSR_IDLETHREAD changes landed in master, but async aborts remain unmasked for DEBUG kernels.

**Comment by philipderrin** [comment]
I think it's reasonable to leave async aborts enabled by default for debug kernels, because it's useful to know that they are happening — they are often caused by a real bug in a driver. It might make sense to have a config option to temporarily disable them, though.

**Comment by jdub** [comment]
That makes sense.

What's troubling me is that release builds of 3.2.0 and the rt branch are fine with the latest u-boot. The rootserver boots, all tests pass. Debug builds only work if I use the old ERTOS u-boot.

**Comment by AdrianDanis** [comment]
@philipderrin this is precisely why we left the aborts enabled in debug mode. If aborts are being 'spuriously' triggered due to u-boot or some other reason that is not that fault of the system you're building, then we could definitely add a config option to also disable them even in debug mode.

**Comment by jdub** [comment]
Leaving aside my little incursion (which we can deal with in #35), it looks like this is resolved.
