### ISSUE TITLE
KernelPaddrUserTop set incorrectly for ARM 64-bit platforms

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#347]
A full discussion on the topic is available on discourse: https://sel4.discourse.group/t/device-region-untypeds/328

Given the current implementation for ARM 64-bit expects KernelPaddrUserTop to be exclusive, and changes will not impact verification I propose a very quick and easy fix to the config script in the short term.

This can be followed by a fix to the source to treat KernelPaddrUserTop to be inclusive (and ensures consistency across platforms) as possible.

**Comment by lsf37** [comment]
👍
