### ISSUE TITLE
x86: boot hangs due to unstable serial-console output

### ISSUE THREAD

**Issue by chelmuth** [seL4/seL4#36]
On our test machine, nightly tests are unstable since we connected a custom USB-HID test device that acts rather dynamically with periodic connect-disconnect cycles. The symptom is that the kernel boot just hangs during PCI scan. I traced this down to `console_putchar()` in  *src/plat/pc99/machine/io.c* which produces the hang by not returning, and for me the following code looked suspicious
```C
while (!(in8(port + 5) & 0x60));
```
The implementation checks if the THRE 0x20 or TEMT 0x40 flag was set in the UART. If I remove TEMT from the check all tests work as expected. Also, most other UART drivers I know of just check for THRE as the flag is defined as *the UART is ready to accept a new character for transmission* (from http://archive.pcjs.org/pubs/pc/datasheets/8250A-UART.pdf).

**Comment by AdrianDanis** [comment]
I cannot guess why this was written this way originally. I would agree that it should just be checking THRE

**Comment by chelmuth** [comment]
Please consider af576aa for merge.

**Comment by AdrianDanis** [comment]
Yep, I'll pull this in. Thanks.
