### ISSUE TITLE
URL for seL4-manual-latest.pdf in readme is broken

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#371]
In `README.md` the URL https://sel4.systems/Info/Docs/seL4-manual-latest.pdf returns a 404 error. Has this moved recently?

**Comment by wom-bat** [comment]
It's back again

On 29 May 2021 3:21:02 am AEST, Axel Heider ***@***.***> wrote:
>In `README.md` the URL
>https://sel4.systems/Info/Docs/seL4-manual-latest.pdf returns a 404
>error. Has this moved recently?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/seL4/seL4/issues/371

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lsf37** [comment]
Can confirm it works again.

**Comment by lsf37** [comment]
And it has stopped working again..

**Comment by wom-bat** [comment]
It's working for me ...

**Comment by lsf37** [comment]
You're right, the check was old. On re-run it worked. So this is reliable now and the issue should be closed?
