### ISSUE TITLE
seL4 fails to compile, circular_includes_valid fails

### ISSUE THREAD

**Issue by Ellis2781** [seL4/seL4#374]
```
FAILED: kernel/circular_includes_valid 
cd ~/Sel4/root/build/kernel && /home/kc/Sel4/root/kernel/tools/circular_includes.py --ignore kernel_all_copy.c < kernel_all.i && touch circular_includes_valid
Traceback (most recent call last):
  File "~/Sel4/root/kernel/tools/circular_includes.py", line 74, in <module>
    sys.exit(main(args))
  File "~/Sel4/root/kernel/tools/circular_includes.py", line 61, in main
    while file_stack[-1] != header:
IndexError: list index out of range
[126/263] Building C object apps/sel4test-driver/seL4_libs/libsel4allocman/CMakeFiles/sel4allocman.dir/src/bootstrap.c.obj
ninja: build stopped: subcommand failed.
```

**Comment by axel-h** [comment]
What command line are you executing and what is you environment?

**Comment by Ellis2781** [comment]
This happens after I do  “../init-build.sh -DPLATFORM=x86_64 -DSIMULATION=TRUE” compiling from arch Linux, using cmake, and ninja build.

**Comment by axel-h** [comment]
I assume you are not using the docker containers?

**Comment by Ellis2781** [comment]
Yes, no container

**Comment by Ellis2781** [comment]
Solved, using docker

**Comment by axel-h** [comment]
Would still be interesting to see what failed here. Seems the python script can't come with some (potentially faulty) input and should do more sanity checks before blindly assuming some things.

**Comment by kent-mcleod** [comment]
Getting more information about the input would require looking at the contents of `kernel_all.i` as the error indicates that the input file had a sequence of preprocessor linemarkers that didn't match the behavior it assumed.

**Comment by wom-bat** [comment]
I'm seeing the same issue trying to build riscV version using gcc 11.

**Comment by wom-bat** [comment]
The fix for me was this patch:
```diff --git a/tools/circular_includes.py b/tools/circular_includes.py
index 1f7059ce..d3d448d5 100755
--- a/tools/circular_includes.py
+++ b/tools/circular_includes.py
@@ -28,7 +28,7 @@ def main(parse_args):
     if ignore_args and len(ignore_args):
         ignore_args = [re.escape(ignore) for ignore in ignore_args]
         ignore_re_string = '(' + '|'.join(ignore_args) + ')'
-        ignore_re = re.compile(r'^# 1 ".*' + ignore_re_string + '"')
+        ignore_re = re.compile(r'^# [01] ".*' + ignore_re_string + '"')
 
     header_re = re.compile(r'^# (\d+) "(.*\..)"')
 ```

**Comment by kent-mcleod** [comment]
This should have been fixed by https://github.com/seL4/seL4/pull/535

**Comment by GooTal** [comment]
Oh, I was trying to build the kernel for riscv64 using seL4-12.1.0 and got the same error. This patch works for me too. Lucky me.
