### ISSUE TITLE
seL4_NBSend should provide indication that something was sent.

### ISSUE THREAD

**Issue by RichardHabeeb** [seL4/seL4#38]
There are times when IPC needs to happen, but a sending process cannot wait around for another process to be receiving. seL4_NBSend is basically the system call for this, but it never provides any feedback whether or not IPC took place.

**Comment by gernotheiser** [comment]
On 24 Sep 2016, at 5:00 , Richard <notifications@github.com> wrote:
> There are times when IPC needs to happen, but a sending process cannot wait around for another process to be receiving. seL4_NBSend is basically the system call for this, but it never provides any feedback whether or not IPC took place.

That’s a feature, not a bug. If you only have a send cap, you can’t receive info back. An acknowledgment would create a back channel, which would violate information flow.

Gernot

**Comment by RichardHabeeb** [comment]
So returning information that the EP had a wait queue with > 0 (with a bool of something) qualifies as receiving info back? I mean you always infer the same information from seL4_Send when it unblocks right? I do realize that this is a fairly significant kernel change, since the system call touches many functions. 

Anyways, I am rethinking through my design after reading through the mailing list and talking to some others. I'll keep thinking this though, because it seems like NBSend is in a pretty bad place.

**Comment by gernotheiser** [comment]
On 25 Sep 2016, at 4:04 , Richard <notifications@github.com> wrote:
> 
> So returning information that the EP had a wait queue with > 0 (with a bool of something) qualifies as receiving info back? I mean you always infer the same information from seL4_Send when it unblocks right? I do realize that this is a fairly significant kernel change, since the system call touches many functions. 
> 
> Anyways, I am rethinking through my design after reading through the mailing list and talking to some others. I'll keep thinking this though, because it seems like NBSend is in a pretty bad place.
> 
You may be interested in my post to the developers list, which explains things further and also discusses an alternative (which requires additional functionality but doesn’t change any existing functionality): https://sel4.systems/pipermail/devel/2016-September/000995.html
