### ISSUE TITLE
Using the scanf function returns 'Assertion failed: !"not implemented" (/host/projects/seL4_libs/libsel4muslcsys/src/sys_io.c: sys_readv: 3)' using simulate

### ISSUE THREAD

**Issue by Ellis2781** [seL4/seL4#382]
Mapping kernel window is done
Booting all finished, dropped to user space
Assertion failed: !"not implemented" (/host/projects/seL4_libs/libsel4muslcsys/src/sys_io.c: sys_readv: 3)
Input:

**Comment by axel-h** [comment]
Basically this error is right, it is not implemented. The kernel does not provide an input channel, there is just an output channel for debug logs. If your user application wants to get input, it needs to implement an input channel (serial port, keyboard...) or use a driver that provides one. Then muslc's `scanf()` needs to be connected to this input channel. 

Please see https://docs.sel4.systems/projects/available-user-components.html and https://docs.sel4.systems/projects/camkes/status.html for a list of available components and examples. Some of these also deal with handling input. 

Closing this, as it is not a kernel issue.

**Comment by Ellis2781** [comment]
Thanks axel!

**Comment by Ellis2781** [comment]
How would you connect the input to the IO stream?

**Comment by axel-h** [comment]
Frankly, I'm not sure what you are trying to achieve in the end and what to make of this very generic question. If all you want to getting input, you could just map an UART and then read from it. There seL4 tutorials show how to map devices, and drivers for various platforms are available. If you have more specific questions, please consider asking them on the mailing list (https://lists.sel4.systems) or the Discourse board (https://sel4.discourse.group).
