### ISSUE TITLE
delete merged branches

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#386]
Delete these branches, they have been merged:
- `clz`
- `cmillar/save-when-disabled`
- `kent/gicv3`
- `alyons-aarch64-addr`

**Comment by axel-h** [comment]
Seems https://github.com/seL4/seL4/pull/122 shopuld get a rebase then. Otherwise this can't be merged anyway

**Comment by lsf37** [comment]
Fair enough, I'll leave this open until that is done.

**Comment by kent-mcleod** [comment]
> Seems #122 should get a rebase then. Otherwise this can't be merged anyway

I changed the target for #122
