### ISSUE TITLE
kernel boot create untypeds for region overflow

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#389]
When adding debug output on the zynq7000 platform in QEMU there are some strange things happening on kernel boot when the untypeds are created:
 
```
init_freemem n_reserved=4
  reserved[0]: 0xe0000000 - 0xe003c000
  reserved[1]: 0xe003c000 - 0xe003f000
  reserved[2]: 0xe003f000 - 0xe0188000
  reserved[3]: 0xff000000 - 0xff100000
init_freemem n_available=1
  available[0]: 0x0 - 0x40000000
  create_device_untypeds start
  num ndks_boot.reserved=2
    ndks_boot.reserved[0]: 0x0 - 0x1ff00000
    create_untypeds_for_region: 0xfff00000 - 0xd8f00000
 ```
This looks odd, start is smaller than end after some translation of the addresses happened
```
     provide_untyped_cap: 0xfff00000 - 0x0
      provide_untyped_cap: 0x0 - 0x20000000
      provide_untyped_cap: 0x20000000 - 0x40000000
```
This looks odd again, there is an overflow. It this supposed to happen? There is an `is_region_empty()` check, but there is no check if the region is sane.

**Comment by kent-mcleod** [comment]
This is because the types being printed are pptr_t which are virtual addresses corresponding to physical addresses translated into the kernel window.  On zynq7000 PPTR_BASE = 0xe0000000.  So a physical address of 0x20000000 is 0x0 when translated to a pptr_t. That's also why reserved is starting from 0xe0000000 as that corresponds to the lowest physical address.

**Comment by axel-h** [comment]
When `create_device_untypeds()` is doing 
```
    if (start < CONFIG_PADDR_USER_DEVICE_TOP) {
        region_t reg = paddr_to_pptr_reg((p_region_t) {
            start, CONFIG_PADDR_USER_DEVICE_TOP
        });
```
on RISC-V/spike64 we have
- `start = 0x17ff00000`
- `CONFIG_PADDR_USER_DEVICE_TOP = 0x7fffffffff` 
-  `PPTR_BASE_OFFSET = 0xffffffc000000000` 
and `paddr_to_pptr_reg()` calculates `CONFIG_PADDR_USER_DEVICE_TOP + PPTR_BASE_OFFSET` which is overflowing:
```
    0000007fffffffff
 +  ffffffc000000000
---------------------
 = 10000003fffffffff 
```
Since this exceeds the 64 bit range, `create_device_untypeds()` is now trying to process a region from 'ffffffc17ff00000' to ''3fffffffff', which seem somehting that is not supposed to happen. Initially I found this while extending `is_reg_empty()` to do a region sanity `assert(reg.start <= reg.end)`

Woudn't it all be much simpler if physical addresses are passesd everywhere? Seems `cap_untyped_cap_new()` masks things out in the end anyway. I consider the debug log from my current patch much to understand then also, as there is no mix of virtual and physical addresses.

**Comment by kent-mcleod** [comment]
The overflow isn't a bug.  The way to think about it is that for address spaces where both `-0x1` and `0x0` are valid virtual addresses (when cast to unsigned) then a region of memory being converted into device untypeds is allowed to cross this boundary.  Although a single untyped is not allowed to cross this boundary and so there can never be a single kernel object that crosses this boundary.  However for address spaces where `-0x1` is not a valid address, then it is not allowed for an untyped range to cross an invalid address.  https://github.com/seL4/seL4/pull/590 addresses this for aarch64-hyp mode when the kernel's EL2 address space has an invalid address region at the top.
