### ISSUE TITLE
Caught cap fault in send phase at address 0

### ISSUE THREAD

**Issue by Ellis2781** [seL4/seL4#398]
Booting all finished, dropped to user space
Hello, World!
Caught cap fault in send phase at address 0
while trying to handle:
vm fault on data at address 0 with status 0x4
in thread 0xffffff801fe08400 "rootserver" at address 0
With stack:
0x41ce98: 0x401740
0x41cea0: 0x0
0x41cea8: 0x401100
0x41ceb0: 0x41cef0
0x41ceb8: 0x40121b
0x41cec0: 0x0
0x41cec8: 0x41cf30
0x41ced0: 0x41cf20
0x41ced8: 0x41cf10
0x41cee0: 0x1
0x41cee8: 0x4010f2
0x41cef0: 0x41cff0
0x41cef8: 0x401394
0x41cf00: 0x0
0x41cf08: 0x525000
0x41cf10: 0x41201c

**Comment by kent-mcleod** [comment]
This is probably happening because your main function is returning after printing, and the default runtime environment terminates itself with that fault you see.
Here is more context: https://github.com/seL4/sel4runtime/issues/10

**Comment by Ellis2781** [comment]
Solved! 
What you said about the sel4runtime was true. Without adding 

#include <sel4utils/thread.h>
seL4_TCB_Suspend(seL4_CapInitThreadTCB);

into your main file, you will get a cap error.
