### ISSUE TITLE
polarfire platform doesn't set KernelOpenSBIPlatform and causes cmake configuration error

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/seL4#405]
What should this setting be? Other platforms have: "fpga/ariane", "sifive/fu540" or "generic".

```
CMake Error at /tmp/tmp.piK7QMRi8A/tools/seL4/cmake-tool/helpers/rootserver.cmake:102 (message):
  KernelOpenSBIPlatform not set.
Call Stack (most recent call first):
  apps/sel4test-driver/CMakeLists.txt:88 (DeclareRootserver)
```

**Comment by axel-h** [comment]
https://github.com/seL4/seL4/pull/365 contains a commit that addresses this. Feel free to cherry-pick it if you want to close this issue. Unfortunately I have the PR still in daft mode, still as I need to find a way to add the SBI reserved memory as real reserved memory that has no caps for it are created. Not sure when I finish this.

**Comment by axel-h** [comment]
merged with https://github.com/seL4/seL4/pull/507
