### ISSUE TITLE
Confusing instructions when following the 'threads' tutorial

### ISSUE THREAD

**Issue by Ellis2781** [seL4/seL4#418]
The tutorial says "Fix the seL4_Untyped_Retype call (shown below) using the capabilities provided above, such that a new TCB object is created in tcb_cap_slot"

seL4_Untyped_Retype(seL4_CapNull, seL4_TCBObject, seL4_TCBBits, seL4_CapNull, 0, 0, seL4_CapNull, 1);

It doesn't give any info on how to do so.

**Comment by mbrcknl** [comment]
I guess you should do the Untyped tutorial first:
https://docs.sel4.systems/Tutorials/untyped.html

BTW, this was the first result when I googled "seL4_Untyped_Retype tutorial".

We would accept a pull request to add the Untyped tutorial as a prerequisite to the Threads tutorial.
