### ISSUE TITLE
License check complains about missing owner for manual logo PDFs

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#430]
The bamboo license check complains about missing owner for PDFs, seen e.g. for https://github.com/seL4/seL4/pull/379 
```
22-Jun-2021 15:34:35	+ python license-tool/check_license.py seL4 --spdx
22-Jun-2021 15:34:36	ERROR:root:seL4/manual/logos/blacktriangle.pdf: seL4/manual/logos/blacktriangle.pdf: no owner found
22-Jun-2021 15:34:36	ERROR:root:seL4/manual/logos/seL4-Foundation-logo.pdf: seL4/manual/logos/seL4-Foundation-logo.pdf: no owner found
```

**Comment by lsf37** [comment]
@nomadeel, can you please manually delete/disable the license check plan for seL4 in Bamboo (the old licence check only, the `reuse` plan should stay on).

**Comment by mbrcknl** [comment]
It's already disabled for the main plan, but was still enabled for the branch corresponding to #379. Would that be because the branch was created while the main plan was still enabled?

I've disabled the branch for #379, but that might not be enough to solve the problem, so I'll dig some more...

**Comment by lsf37** [comment]
> It's already disabled for the main plan, but was still enabled for the branch corresponding to #379. Would that be because the branch was created while the main plan was still enabled?
> 
> I've disabled the branch for #379, but that might not be enough to solve the problem, so I'll dig some more...

You might need to remove the PR trigger or something like that.

**Comment by mbrcknl** [comment]
Ok, I've disabled automatic branch creation as for #431. Now I'm wondering how the bot will deal with that.

**Comment by lsf37** [comment]
> Ok, I've disabled automatic branch creation as for #431. Now I'm wondering how the bot will deal with that.

Cool. The bot should be fine, IIRC it just grabs whatever is there.

**Comment by lsf37** [comment]
License check now runs exclusively on GitHub and is working, so I'll close the issue.
