### ISSUE TITLE
CI checks need cmake-format

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#431]
The bamboo license check complains about missing `cmake-format` , seen e.g. for #379
```
22-Jun-2021 15:34:39	style-cmake.sh: fatal error: need version 0.4.5 of cmake-format; Traceback (most recent call last):
22-Jun-2021 15:34:39	  File "/usr/local/bin/cmake-format", line 33, in <module>
22-Jun-2021 15:34:39	    sys.exit(load_entry_point('cmake-format==0.4.5', 'console_scripts', 'cmake-format')())
22-Jun-2021 15:34:39	  File "/usr/local/bin/cmake-format", line 22, in importlib_load_entry_point
22-Jun-2021 15:34:39	    for entry_point in distribution(dist_name).entry_points
22-Jun-2021 15:34:39	  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
22-Jun-2021 15:34:39	    return Distribution.from_name(distribution_name)
22-Jun-2021 15:34:39	  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
22-Jun-2021 15:34:39	    raise PackageNotFoundError(name)
22-Jun-2021 15:34:39	importlib.metadata.PackageNotFoundError: cmake-format is installed 
```

**Comment by lsf37** [comment]
It looks like something in the runtime environment of the test changed. `cmake-format` should be available. @nomadeel, can you have a look at what it going on there on Bamboo?

It would also be Ok to disable the style check on Bamboo, since these are now fully replicated on Github.

**Comment by mbrcknl** [comment]
The most recent success I can find is 13 May (on #361), and the earliest failure I could find was 4 June (#372), so something changed in that timeframe.

I've disabled the style check plan, and also turned off automatic branch creation on the plan. AFAICT, existing branches need to be disabled separately, so I've done that for #379. (But I've only disabled things in the UI, not in configascode.)

**Comment by lsf37** [comment]
Excellent, thanks. I've removed the old license check in `configascode` already, but removing them there doesn't delete the existing plans on Bamboo. But at least they shouldn't come back now.

**Comment by lsf37** [comment]
When the configascode PR is merged, we should probably do a test invocation on a PR. After that we should be able to close this issue.

**Comment by mbrcknl** [comment]
> When the configascode PR is merged, we should probably do a test invocation on a PR. After that we should be able to close this issue.

Yep, makes sense.

**Comment by lsf37** [comment]
Bamboo is now out of commission, so this should no longer haunt us..
