### ISSUE TITLE
CI link check fails due to missing https://seL4.systems/security.asc

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#434]
Since https://github.com/seL4/seL4/pull/424 is merged now, the automated check fail because https://seL4.systems/security.asc is still missing. Please either put a key there or some placeholder that says the key will come soon - just to silences the URL checker.

**Comment by lsf37** [comment]
The key was there before we merged, so something must be going wrong. Will investigate.

**Comment by lsf37** [comment]
It is indeed gone now..

**Comment by lsf37** [comment]
Hey @wom-bat, the key is in `content/security.asc` in the website directory (I had uploaded it manually as well to the live site to speed up the merge).

Should it be sitting somewhere else or be marked somewhere to be included?

**Comment by lsf37** [comment]
Ok, thanks got @wom-bat things are back in a consistent state. My manual speed-up turned out to be very temporary only..
