### ISSUE TITLE
init build error for rpi

### ISSUE THREAD

**Issue by neil1899** [seL4/seL4#471]
hi all: 
when i run "../init-build.sh -DPLATFORM=rpi3 -DAARCH32=1"

found error:
-- Detecting cached version of: musllibc
--   Not found cache entry for musllibc - will build from source
CMake Error at /home/niewei/z-ssd-miui/seL4/sel4test/projects/seL4_libs/libsel4muslcsys/CMakeLists.txt:82 (target_link_options):
  Unknown CMake command "target_link_options".

**Comment by yyshen** [comment]
@neil1899 It looks like a CMake version issue. Are you using the docker image for the building environment?

**Comment by neil1899** [comment]
my cmake version:
 cmake --version
cmake version 3.12.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

i don't use docker image for building.

i try update cmake to 3.15?

**Comment by yyshen** [comment]
Your version is probably a bit old. See https://cmake.org/cmake/help/git-stage/command/target_link_options.html. 3.15 probably will work.

**Comment by neil1899** [comment]
thanks a lot
