### ISSUE TITLE
handleInterruptEntry() should call getActiveIRQ() after CONFIG_KERNEL_MCS checks

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#472]
Out of curiosity, is there a reason why `handleInterruptEntry()` calls `getActiveIRQ()` before doing the `CONFIG_KERNEL_MCS` handling?
```
    irq = getActiveIRQ();
#ifdef CONFIG_KERNEL_MCS
    if (SMP_TERNARY(clh_is_self_in_queue(), 1)) {
        updateTimestamp();
        checkBudget();
    }
```
Shouldn't the MSC handling happen first to avoid billing the thread too much? Checking which interrupt is pending can also wait a few more cycles.

**Comment by axel-h** [comment]
There is a similar thing in `handleSyscall()` in various places, e.g. for `SysSend`.
```
irq = getActiveIRQ();
mcsPreemptionPoint(irq);
if (IRQT_TO_IRQ(irq) != IRQT_TO_IRQ(irqInvalid)) {
    handleInterrupt(irq);
}
```

Why is `getActiveIRQ()` called to get the interrupt, then it is passed to `mcsPreemptionPoint(irq)`, but this does not use the `ìrq` parameter at all. Nor does any handling of the interrupt happen. All this will happen eventually in `handleInterrupt(irq)`.

**Comment by lsf37** [comment]
It does look like it's a left-over, yes. @michaelmcinerney and @mktnk3 do you remember why `mcsPreemptionPoint` has an `irq` parameter? It seems to be unused inside.

**Comment by axel-h** [comment]
Based on the comment I'll make a PR then to clean thus up. But from last time I remember this breaks the proofs, so this trivial C code cleanup may need some proof engineering help then also.

**Comment by kent-mcleod** [comment]
> There is a similar thing in `handleSyscall()` in various places, e.g. for `SysSend`.
> 
> ```
> irq = getActiveIRQ();
> mcsPreemptionPoint(irq);
> if (IRQT_TO_IRQ(irq) != IRQT_TO_IRQ(irqInvalid)) {
>     handleInterrupt(irq);
> }
> ```
> 
> Why is `getActiveIRQ()` called to get the interrupt, then it is passed to `mcsPreemptionPoint(irq)`, but this does not use the `ìrq` parameter at all. Nor does any handling of the interrupt happen. All this will happen eventually in `handleInterrupt(irq)`.

`mcsPreemptionPoint` used to call updateTimestamp if the IRQ was a timer interrupt. https://github.com/seL4/seL4/pull/327 refactored the preemption point check to unconditionally call updateTimestamp which removed the need for the parameter.

**Comment by lsf37** [comment]
The `irq` parameter question is tracked separately in #991 now, but I think it would still make sense to move the [getActiveIRQ line](https://github.com/seL4/seL4/blob/a7fcda426754091f66351942e18d964943016153/src/api/syscall.c#L41) to just before `irq` [is needed](https://github.com/seL4/seL4/blob/a7fcda426754091f66351942e18d964943016153/src/api/syscall.c#L49) before the structure is baked in to verification.

@michaelmcinerney do you think would need any spec/ainvs/refine changes? I assume we haven't reached this function yet in CRefine.

**Comment by michaelmcinerney** [comment]
> @michaelmcinerney do you think would need any spec/ainvs/refine changes? I assume we haven't reached this function yet in CRefine.

The `irq` bit has already been removed from the aspec. It's still in Refine, but removing that is easy too. If we fix the C up and put `getActiveIRQ` where you suggest, then I can align all functions to the C and it'll be fine

**Comment by lsf37** [comment]
Ok, great. Let's do both of these. I'll put up PRs for C. Can I leave the Isabelle side to you?

**Comment by michaelmcinerney** [comment]
> Ok, great. Let's do both of these. I'll put up PRs for C. Can I leave the Isabelle side to you?

Yes!
