### ISSUE TITLE
some unexpected phenomenon about scheduling

### ISSUE THREAD

**Issue by lydmcu** [seL4/seL4#478]
Hi :
Recently, I found some unexpected phenomenon about scheduling on our project.
My environment as follows:
    I run linux guest on seL4, Linux guest has 8 vcpu on 8 Arm PE from core0 ~ core7.
    WFI is not trap, seL4 is master kernel not mcs kernel
    I think seL4 idle task will not be run on core1, it will always run vcpu task.
    But the truth is the idle task will be run.
I found when the maintenance and timer interrupt of Linux guest came, it will switch to idle,
Because above interrupts handle will call handleFault, the sendIPC will set the ksCurThread(vcpu task) block on send, and the ksReadyQueuesL1Bitmap is empty.
The idle task wille be run. But the recv task maybe run on core0, now core1 is in idle, is it reasonable?
             Thank you very much 
@yyshen

**Comment by nspin** [comment]
If I understand your observations correctly, I believe they are a result of the design of the VMM you are using. Ideally, the VMM would assign to each vCPU thread a distinct fault handling thread with a matching affinity.

**Comment by yyshen** [comment]
> If I understand your observations correctly, I believe they are a result of the design of the VMM you are using. Ideally, the VMM would assign to each vCPU thread a distinct fault handling thread with a matching affinity.

That is one way to go, which probably also reduces the contentions on the handling thread.

**Comment by kent-mcleod** [comment]
In theory, the MCS kernel supports a migrating vmm thread handler if it was configured as a passive thread (without a scheduling context). This still means that only one vcpu fault can be processed at a time, but there isn't cross core IPC occurring that leads to cores becoming idle as the fault will be processed on the same core.

**Comment by yyshen** [comment]
> In theory, the MCS kernel supports a migrating vmm thread handler if it was configured as a passive thread (without a scheduling context). This still means that only one vcpu fault can be processed at a time, but there isn't cross core IPC occurring that leads to cores becoming idle as the fault will be processed on the same core.

The vtimer and maintenance interrupts are relatively frequent, so migrating a VMM handler thread frequently across cores might introduce some overheads (i.e., re-establish working set)?

**Comment by Indanz** [comment]
Only extra overhead should be minor cache line bouncing between cores, but only for written cache lines like the stack. That's probably negligible.

However, as far as I understand this only works for vCPU events delivered as a fault, not normal IRQ handling, which is done via notifications. To handle notifications as a passive server there needs to be a scheduling context bound to it. As only one notification object can be bound to a TCB, this would practically force all IRQ delivery via one CPU core, which is probably undesired.

With passive servers with MCS it makes sense to support binding one notification object per CPU core to a TCB. Or, alternatively, support binding one scheduling context per CPU core to a notification object. (But then there is no easy work-around for the max 64 IRQs limit per VM.)

For most drivers that support a service it makes sense to write them as a passive server with a scheduling object bound to the IRQ notification object. But some hardware has multi-queue support for which it can make sense to spread the load over multiple cores. MCS does not support this use-case very well currently.

**Comment by kent-mcleod** [comment]
> With passive servers with MCS it makes sense to support binding one notification object per CPU core to a TCB. Or, alternatively, support binding one scheduling context per CPU core to a notification object. (But then there is no easy work-around for the max 64 IRQs limit per VM.)

I think having a mechanism for allowing a single thread to block on multiple notification objects (potentially also required for supporting a larger max IRQ limit) would be a good way to enable migrating TCBs while also allowing other thread senders to select the core the receiver executes on via the notification cap.

Closing this as the original question has been answered.

**Comment by Indanz** [comment]
> allowing other thread senders to select the core the receiver executes on via the notification cap.

For IRQs the core selection is currently not flexible enough, as the core needs to be chosen when making the IRQHandler, while it would be useful if the core would depend on where the receiver is (for bound notifications) or at least could be changed later.

**Comment by kent-mcleod** [comment]
I don't quite follow sorry.  Do you want a passive thread to migrate to the core the irq is delivered on or for the irq to be delivered to the core the passive thread is currently on without migration?

**Comment by Indanz** [comment]
I was mostly talking about non-passive threads handling IRQs. If the IRQ notification is bound to a TCB, the IRQ should move to the same core for non-passive threads. If the TCB gets migrated, the IRQ should migrate with it (this could be done on-demand). Having a system call that sets the core for IRQHandlers after creation would be sufficient, that way user space can take care of this itself.

For passive threads the thread's current core shouldn't affect on which core the IRQ is delivered, the current behaviour is fine: A bound notification has a scheduling context with a core configured, and that core will be used to handle IRQs. For IRQ delivery it is not different than a non-passive thread.

**Comment by kent-mcleod** [comment]
Doing it automatically wouldn't be very easy because a TCB can have it's SC removed and then a different one bound while it's still blocked on the same notification object so the kernel would need to do too much back tracking to find if the TCB was blocked on the notification that it was bound to and then find and update all IRQ handlers that refer back to the notification.

Changing the affinity of an existing handler cap should be fine, but would probably require the irq control cap authority also.

**Comment by Indanz** [comment]
Doing it automatically on-demand would be easy enough though: If an IRQ arrives on a different core than the TCB where the notification is bound to, the IRQ is reconfigured for the correct core.

> would probably require the irq control cap authority also

That's very impractical, as the IRQ control cap can't be copied and gives too much rights. The IRQHandle gives the right to handle the IRQ, it would make more sense to have a mask of which cores may handle the IRQ, and then having the IRQHandle would be sufficient.

It never makes any sense to handle IRQs on another core than the receiver though, if the receiver's core is known: Doing cross-core notifications is more expensive, as that usually requires an IPI. So to me it seems obvious that you don't need additional rights to get the IRQ on the correct core, you already had all the rights to get the thread handling it on that core, why require extra permissions to avoid cross-core IRQ notifications? Also, ACKing IRQs cross-core is probably also very expensive.
