### ISSUE TITLE
Null caps vs Non-existent caps

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#488]
I'm in deeper to the kernel than normal, so I could be wrong with this analysis.

It appears that there is a difference between an 'invalid capability' which raise a cap fault to a thread's exception handler, and a 'null capability' which does not.

This is specifically seen when attempting a `seL4_Signal` call.
When calling `seL4_Signal` on part of the CSpace that is covered by a CNode, but notionally `empty` no cap fault is raised.
However, the same call reference a non-existent part of the CSpace will generate a cap fault.
(Which is not detectable as `seL4_Signal` does not return a value).

`decodeInvocation` is passed a cap.

It performs this check:

```
    case cap_null_cap:
        userError("Attempted to invoke a null cap #%lu.", capIndex);
        current_syscall_error.type = seL4_InvalidCapability;
        current_syscall_error.invalidCapNumber = 0;
        return EXCEPTION_SYSCALL_ERROR;

```

However, the faulting case appears to be handled previously in `handleInvocation`:

```
    /* faulting section */
    lu_ret = lookupCapAndSlot(thread, cptr);

    if (unlikely(lu_ret.status != EXCEPTION_NONE)) {
        userError("Invocation of invalid cap #%lu.", cptr);
        current_fault = seL4_Fault_CapFault_new(cptr, false);

        if (isBlocking) {
            handleFault(thread);
        }

        return EXCEPTION_NONE;
    }
```

My understanding is that a `null cap` is not a real thing as such, and instead is simply a marker that indicates an empty cap slot.
As such, I'd expect an attempt to invoke a null cap would be the same as a lookup that fails.

It doesn't appear that the code implements this, so I'm a bit confused (and quite possibly I misunderstand the intended behaviour or I've got a bug somewhere in my user test code).

So I guess:

1: Is it intended that passing a CSpace address that maps to an empty cap slot is different to passing a CSpace address that simply doesn't map to any slot?
2: Assuming it is intended, what's the rationale there?
3: Assuming it is not intended is it a bug in the existing code, or am I misreading it (and have some bug in my user code that appears to exhibit different behaviours).

Thanks!

**Comment by lsf37** [comment]
There is no attempt in the design to make NullCap behave the same as a lookup for a slot that does not exist. It’s not immediately clear to me what the benefit of it would be. 

One is simply an empty slot, the other is a slot that does not exist. Both can happen.

**Comment by gernotheiser** [comment]
Conceptually it's unclean at best, it's not the kernel's job to educate users on how they stuffed up ;-)

More concerning, I think it's wrong that the kernel gives the user different information depending on whether they tried to use a non-existing cap or an invalid cap. Both are fundamentally the same thing: user attempted an operation with a cap reference that does not point to a cap that authorises said operation. That's all the user should be able to learn.

**Comment by bennoleslie** [comment]
Thanks for the replies Gerwin and Gernot.

I guess I'm still confused.

In terms of the `concepts` admitted into the design we appear to have:

1: A `capability address`; which as described by the manual is simply an integer.

2: A `capability slot`; exists within a CNode, can be referenced by one (or more) capability address.

3: A `capability`; occupies exactly one capability slot, but might be referenced by multiple capability addresses.

There is a `capability address lookup` concept. This procedure takes a capability address and returns a capability slot (or fails in the case where a capability address does not refer to a  capability slot).

So relationship are:

cap_address:cap_slot is N:1

  with the caveat that a cap address may not reference any cap slot

cap_slot:capability is 1:1

So far, so good. 

Where we now run into trouble though is that we appear to have two distinct concepts that are not well defined (within the English language user manual; I assume they are well defined within the sepc, and hoping someone with that depth can clarify!)

In 3.3 a CNode is described as a *table of slots, where each slot can either be empty, or contain a capability*.

Other parts of the manual: 

* 3.1.3 - Capabilities to Newly-Retyped Objects
* 4.2.3 - Errors
* 10.3.1.8 - Rotate

Refer to 'empty slots' in some manner.

However, the kernel implementation does not appear to have any concept of an 'empty slot'. From the kernel point of view every 'cap slot' contains a capability, but there are some special capability types which are considered 'invalid' (specifically a null and zombie cap).

Of course, a capability can also be invalid for other reasons (it might be the wrong type of object when a specific type is required, or it may have the wrong permissions for the operation being requested).

So, for any given cap address it seems like there are in fact four cases (ignoring zombie cap for now)

1: It refers to a cap slot containing a cap of the correct type and correct permissions (no problem).
2: It refers to a cap slot containing a cap to either the incorrect type or incorrect permissions (a problem, 'InvalidCapability').
3: It refers to a cap slot containing a null cap (/ slot is considered empty).
4: It does *not* refer to a cap slot (which causes a CapFault).

I guess my intuition was that `#3` would be the same as `#4`.

However, I guess it equally makes sense for it to behave as `#2`.

Is this the right mental model for one to think in?

So, assuming I have the mental model right, back to the practical issue at hand.

What is the motivation/rationale for `seL4_Signal` not returning an error when an InvalidCapability is passed?

It does not seem to me as though it can be a info flow / security issue: I can perform a call instead and discover that it is an InvalidCapability since that returns an error.

I accept that the kernel doesn't *have* to provide the user with information on exactly why something went wrong, however, I think from a practical point of view it would be good to let the user at least *know* something went wrong. It seems perverse that the kernel knows there is a problem but doesn't communicate this to the user. (Although I certainly accept I could be missing something).

**Comment by pingerino** [comment]
I believe seL4_Signal is intended to be fire and forget. That said, I've noted before that the error handling in the kernel api isn't always consistent. It could make sense to add an error code here. 

Look at it from the other way, which is how the system can respond to these issues:

1. error: can be ignored or handled by the caller
2. cap fault: you need a fault handler or your thread dies, and is intended for where you might be virtualising the cspace or populating it in demand
3. nothing, can only be detected by some other user level protocol

A null cap suggested it needs to be populated, a completely invalid cap is an error, which makes total sense.

**Comment by bennoleslie** [comment]
Apologies; at this point I think I've split this initial issue into two related, but distinct discussions. Possibly should have been in Discourse not GitHub, but anyway. Pressing on here unless anyone else feels strongly otherwise.


1: How should errors on seL4_Signal be handled.

As far as I can tell the possible incorrect usages are:

* specifying a cap address that doesn't map to a cap slot (causes a Cap Fault, don't think anyone disagrees here).
* specifying a cap address that maps to a cap slot holding a null cap (is silently ignored; *I* don't like this behaviour, but could be convinced otherwise)
* specifying a cap address that maps to a cap slot holding a notification cap, but without the send permission (is also silently ignored, and I also think this isn't the best).
* specifying a cap address that maps to a valid object that isn't a notification cap; I'm not really sure what happens here, something weird / bad.

@pingerino is certainly right, options for any of these case are cap fault, return an error, or do nothing.

I think it's beneficial for practical purposes that seL4_Signal (and therefore seL4_Send) should return an error in the cases where it is able to. I don't think this provides for any increase in functionality though, it's strictly to make life easier for the developer (which I know is not necessarily the remit of the kernel, but I think it should unless there is a good reason not to).

I guess the question is: is there any motivation to *not* return an error (and do nothing, or perhaps raise a cap fault).


2: What's the right terminology?

I think it would be beneficial to clarify the terminology. I don't have a strong opinion as to what is "right". But I think we should either refer to "null capabilities" or to "empty cap slots".

To some extent just using "null cap" is compelling. In such a conception one no longer needs to reference "cap slots" (I think). A cap address either passes lookup and refers to a capability, or it fails lookup (generating a cap fault). There are no empty slots (so cap and cap slot are now a 1:1 concept). But we do need to speak explicitly about what happens when various system calls are invoked on a null cap. At this point empty slot is redundant (I think).

I feel like most of the time "caps" are referred to in (informal) documentation there is a blurring between "cap address" / "cap slot' and "cap". Being able to ignore the "cap slot" concept for the most part would (I think) aid in communicating these things.

If we really prefer "empty cap slot" and the concept is just that a "null cap is an internal implementation detail to mark an empty slot" the I feel like we should make that clear in documentation and debug messages from the kernel.

**Comment by kent-mcleod** [comment]
Just referring to the seL4_Signal and error returning part here:
seL4_Signal is an alias of seL4_Send and is conventionally used only on notification objects.  If you perform seL4_Call on a notification endpoint, then you would see the kernel return an error if the CPtr referred to is a null capability.
Because the design tries to treat capability invocations as "IPC with the kernel", using seL4_Send for invocations is possible, but the kernel does not provide any return values.  One place to see this distinction is in `handleInvocation`, where `replyFromKernel_error` is called if the system call is a seL4_Call, but not called if it's only seL4_Send.
So another question could be whether seL4_Signal should be changed to an alias of seL4_Call and return errors, or whether using seL4_Send for capability invocations should still return a potential error message back to the user, (this would have an impact on cap virtualization though).

**Comment by lsf37** [comment]
> To some extent just using "null cap" is compelling. In such a conception one no longer needs to reference "cap slots" (I think). A cap address either passes lookup and refers to a capability, or it fails lookup (generating a cap fault). There are no empty slots (so cap and cap slot are now a 1:1 concept). But we do need to speak explicitly about what happens when various system calls are invoked on a null cap. At this point empty slot is redundant (I think).

I completely agree with this view and that is what the spec also formalises. The informal use "empty cap slot" should really be "resolves to a NullCap". As long as that is clear the two could be used equivalently, but the user manual is sloppy with language in many places.


> I feel like most of the time "caps" are referred to in (informal) documentation there is a blurring between "cap address" / "cap slot' and "cap". Being able to ignore the "cap slot" concept for the most part would (I think) aid in communicating these things.

I'm not entirely sure the concept of cap slot can be completely erased (it's a bit hard to talk about what a CNode provides if you just use cap resolution as language), but at least it could can say "slot with NullCap" instead of "empty slot", and it probably can be erased in much of the rest of the manual

**Comment by lsf37** [comment]
>  or whether using seL4_Send for capability invocations should still return a potential error message back to the user, (this would have an impact on cap virtualization though).

Some of this has come up a few times in the past and also touches on the discussion in #477.

It'd be good to think through error reporting again and make this a bit more consistent. Some of the things that are problematic at the moment, as I understand it from the discussion so far:

 - no cap faults come out of `NBSend`-like calls. I currently see no problem with that being removed. 
 - no error reply comes out of `Send`, because we're expecting this to be a one-way IPC that does not send a reply. Maybe the fault handler should get a message in that case? Would that make sense? This would generalise fault handlers somewhat and make them responsible for more cases.
 - NullCap invocation is different from cap fault and might make sense to unify. Would that already be achieved by the two above? Unifying them would remove information that could be useful to the user (it can now be distinguished at least in Call, but could not any more if unified).

Changing all this could be quite a bit of verification work, but if it makes things clearer and simpler to use, I think it'd be worth it.

**Comment by lsf37** [comment]
A slightly more radical departure from the current API would be to say "everything is a syscall", not "everything is an IPC with the kernel". Then it would make sense to always expect an error reply from the kernel to the invoking user. We'd have to think through how this interacts with cap virtualisation, but maybe it can be made to work. (It's not like cap virtualisation actually works, currently)

I don't think this would break anything fundamental in the spec, it'd more be a shift in concepts.

**Comment by bennoleslie** [comment]
> Just referring to the seL4_Signal and error returning part here:
> seL4_Signal is an alias of seL4_Send and is conventionally used only on notification objects. If you perform seL4_Call on a notification endpoint, then you would see the kernel return an error if the CPtr referred to is a null capability.
> Because the design tries to treat capability invocations as "IPC with the kernel", using seL4_Send for invocations is possible, but the kernel does not provide any return values. One place to see this distinction is in `handleInvocation`, where `replyFromKernel_error` is called if the system call is a seL4_Call, but not called if it's only seL4_Send.
> So another question could be whether seL4_Signal should be changed to an alias of seL4_Call and return errors, or whether using seL4_Send for capability invocations should still return a potential error message back to the user, (this would have an impact on cap virtualization though).

Thanks Kent. I think for my exact purpose right now my wrapper can directly call seL4_Call (rather than seL4_Signal) and then check the return value and on failure explicitly invoke the the TCBs fault handler. This would give me the semantics that I want in practise, so that's a win.

**Comment by bennoleslie** [comment]
> A slightly more radical departure from the current API would be to say "everything is a syscall", not "everything is an IPC with the kernel". Then it would make sense to always expect an error reply from the kernel to the invoking user. We'd have to think through how this interacts with cap virtualisation, but maybe it can be made to work. (It's not like cap virtualisation actually works, currently)
> 
> I don't think this would break anything fundamental in the spec, it'd more be a shift in concepts.

This is intriguing. To what extent does invoking kernel objects today actually look like an IPC? It seems perhaps not? For example, if you do a seL4_Send + seL4_Recv to a kernel object will you get the error response? I don't think you do (but maybe I've misread the code).

**Comment by lsf37** [comment]
> To what extent does invoking kernel objects today actually look like an IPC? 

To be honest, I don't know if any of that ever properly worked (just like cap virtualisation for this API in general). It was just one of those guiding concepts. It'd be nice to actually properly analyse this and make it actually work or if it can't work for some reason to properly abandon it. In any case, to make a conscious decision about it instead of a nebulous guideline.

**Comment by gernotheiser** [comment]
To @bennoleslie's question: call() is not just send();receive(), it does more, incl setting up the reply channel: the object you send to is not the object you receive from (although it might just work that way on objects other then EPs...) This is much more explicit in the MCS model.

**Comment by bennoleslie** [comment]
> To @bennoleslie's question: call() is not just send();receive(), it does more, incl setting up the reply channel: the object you send to is not the object you receive from (although it might just work that way on objects other then EPs...) This is much more explicit in the MCS model.

I guess my point was here that if you are interacting with an endpoint you can do a send, and then later a recv to retrieve the result (I think? Or is this impossible with MCS?). But you can't do the same with a kernel object. The point being (to further what  @lsf37 mentioned previously) it's not really like you are "doing an IPC to a kernel provided service" you are really "using a system call on a kernel object".

**Comment by bennoleslie** [comment]
Further on the *what should the behaviour of seL4_Send on a null cap be* question.

I again don't have a strong opinion (other than not 'nothing'), but I feel it should likely be consistent with what would happen if you did an seL4_Recv on the same cap.

My understanding (from reading the code, so I could be wrong here) is that the `handleRecv` function raises a cap fault unless the cap type is actually an endpoint or a notification cap. Additionally, if it is an endpoint or a notification cap, if the cap does not hold the appropriate permission this will also raise a cap fault.

Assuming I'm reading the code correctly, wouldn't it make sense for both send and recv to operate in a similar way?

**Comment by gernotheiser** [comment]
> I guess my point was here that if you are interacting with an endpoint you can do a send, and then later a recv to retrieve the result 
Nope, you generally need two endpoints for two-way communication. If you did NBSend() followed by Receive() on the same EP you'd get your own message back (unless someone else snatched it before you get it it).

Call()+rely_way() create the reply EP on the fly (upgraded to a first-class kernel object with less magic in MCS), thus call() cannot be simulated with send()+receive().

**Comment by lsf37** [comment]
> Assuming I'm reading the code correctly, wouldn't it make sense for both send and recv to operate in a similar way

Yes, I think that would make sense.

In fact, the logic required to *not* send error replies or cap faults in specific situations looks like it needlessly complicates the code (explicit tests for `isCalling` and `isBlocking`). I had a look and at least the whole `isBlocking` thing goes back to at least 2006 (the fact that the kernel does not send a cap fault for a non-blocking send).

I am pretty sure we did not think about strict one-way infoflow back then. What might have been a motivation is having an operation that you can safely use and not be blocked in any way, e.g. if you don't have a fault handler set up. If we raised a cap fault, we would have to block the thread that raised the fault so that the fault handler can do something about it. 

It's not clear to me that this is a good motivation (and it's really just speculation on my part that it even was the motivation).

Some previous Jira items on this are [SELFOUR-1393] and [SELFOUR-279], but neither very enlightening.

**Comment by canarysnort01** [comment]
> My understanding is that a `null cap` is not a real thing as such, and instead is simply a marker that indicates an empty cap slot.

While the CNode's usage of a null cap in this way may be a private implementation detail of the CNode, note that a null cap is a real thing from the perspective of the user and it is expected to be used in arguments to the kernel API.

A null cap is one of the caps that the kernel explicitly provides to the initial thread:

https://github.com/seL4/seL4/blob/12.1.0/libsel4/include/sel4/bootinfo_types.h#L13

For example, `seL4_TCB_SetSpace` and `seL4_TCB_SetTimeoutEndpoint` will clear the respective fault endpoint if the user passes a CPtr to a null cap for the endpoint argument:

https://github.com/seL4/seL4/blob/12.1.0/src/object/tcb.c#L1020

**Comment by canarysnort01** [comment]
> A slightly more radical departure from the current API would be to say "everything is a syscall", not "everything is an IPC with the kernel". Then it would make sense to always expect an error reply from the kernel to the invoking user. We'd have to think through how this interacts with cap virtualisation, but maybe it can be made to work. (It's not like cap virtualisation actually works, currently)

Even though cap virtualization doesn't work currently, would you agree the ideal that the current API is working towards is:

1. A server could give a client a capability to its endpoint
2. The client could use that capability in exactly the same way that it could use a kernel-implemented capability, using the same libsel4 functions, without (easily) being able to detect that it is talking to a server instead of the kernel
3. The server could faithfully implement the kernel object API on the endpoint

How do you see cap virtualization working outside of that model?

**Comment by lsf37** [comment]
> > A slightly more radical departure from the current API would be to say "everything is a syscall", not "everything is an IPC with the kernel". Then it would make sense to always expect an error reply from the kernel to the invoking user. We'd have to think through how this interacts with cap virtualisation, but maybe it can be made to work. (It's not like cap virtualisation actually works, currently)
> 
> Even though cap virtualization doesn't work currently, would you agree the ideal that the current API is working towards is:
> 
> 1. A server could give a client a capability to its endpoint
> 2. The client could use that capability in exactly the same way that it could use a kernel-implemented capability, using the same libsel4 functions, without (easily) being able to detect that it is talking to a server instead of the kernel
> 3. The server could faithfully implement the kernel object API on the endpoint
> 
> How do you see cap virtualization working outside of that model?

I agree, this is how I think cap virtualisation should work. I think this can be made to work in both view points ("everything is an IPC" or "everything is a syscall"), as long as the server can faithfully produce whatever the kernel would produce (including errors).
