### ISSUE TITLE
bingup the new platform not in Linux repository

### ISSUE THREAD

**Issue by neil1899** [seL4/seL4#497]
hi @lsf37 
about porint doc：
“You may need to add device nodes depending on what Linux uses and what is required by seL4. For example, in the port of the Rockpro64 a memory node and an extra timer node were needed so these had to be defined manually.”

how can I get the required by seL4? have any doc about it?

**Comment by lsf37** [comment]
Sorry, no idea, I don't know much about Linux. I'm not the right person for that kind of question. Maybe someone on the [mailing list](https://lists.sel4.systems/postorius/lists/devel.sel4.systems/) or [discourse](https://sel4.discourse.group) can help.

**Comment by neil1899** [comment]
OK thanks
