### ISSUE TITLE
(minor) Fan-out limit Retype error not documented

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#508]
Section 10.3.8.1 does not mention that there is a limit on the number of objects that can be created in a single retype operation (as limited by the fan out limit).

**Comment by lsf37** [comment]
Thanks for reporting these. Please keep them coming.

**Comment by Indanz** [comment]
That limit is exported as seL4_UntypedRetypeMaxObjects to user space.

The only purpose of this limit is to limit WCET.

**Comment by lsf37** [comment]
This is now documented in the epic PR #528
