### ISSUE TITLE
ARMv8 aarch64 boot failure with MCS

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#521]
2f358738850502e7a3d94d1641f7157eada8dc2a introduced a check that ensure `getCurrentTime()` returns reasonable values.

It seems that, on at least some ARMv8 aarch64 platforms, `getCurrentTime()` does not return reasonable values.

Unhelpfully it does return reasonable values when configured to support hypervisor mode. I had previously only tested with hypervisor mode enabled (as that is usually more of a stress test than without).

Pull request #520 let me to test with hypervisor mode disabled, which exposed this problem.

`getCurrentTime()` is implemented by reading from the `CNT_CT` register.

`CNT_CT` is defined as `cntvct_el0` for non hypervisor mode and `cntpct_el0` for hypervisor mode.

`cntpct_el0` is defined as holding the 64-bit *physical count value* (ARM ARM D13.8.20).

The actual value read depends on the EL, when running at EL2 (as we are in hypervisor mode) this just contains the raw value.

When running EL1 things are a little tricky. It will either return the value, or trap to EL2 depending on whether or not EL2 is enabled (and the CNTHCTL_EL2 register setting).

`cntvct_el0` holds the virtual count value. (ARM ARM D13.8.29).

The value here is defined as the physical count value minus the offset which is stored in `CNTVOFF_EL2`.

As with cntpct_el0 this may trap when reading from EL1. 

I'm not sure if it makes sense for the kernel to rely on timer counting up from zero or not. From memory Linux intentionally sets the timer to be a few second before rollover to ensure rollover logic 'works'. Maybe with a 64-bit timer this is unnecessary?

It appears that ELF loader should attempt to set cntvoff_el2 to zero, so it may be a bug for the specific platform I'm testing on where cntvoff_el2 is not being reset.

I guess the question is: is there an intentional assumption that the timer (be it virtual or physical) counts up from zero?

**Comment by kent-mcleod** [comment]
> It appears that ELF loader should attempt to set cntvoff_el2 to zero, so it may be a bug for the specific platform I'm testing on where cntvoff_el2 is not being reset.
> I guess the question is: is there an intentional assumption that the timer (be it virtual or physical) counts up from zero?

Yes.  I'm not sure if there was an issue describing this, but a PR (https://github.com/seL4/seL4_tools/pull/73) updating the elfloader to ensure that all platforms reset cntvoff_el2 before starting the kernel was merged at around the same time as https://github.com/seL4/seL4/commit/2f358738850502e7a3d94d1641f7157eada8dc2a

**Comment by kent-mcleod** [comment]
Here is a Jira issue describing it: https://sel4.atlassian.net/browse/SELFOUR-2596

**Comment by bennoleslie** [comment]
OK. So it seems like we've gone for the *workaround in ELF loader* to ensure time starts at zero as opposed to *be able to deal with the timer wrapping*? Seems reasonable, 64-bit isn't going to overflow any time soon.

**Comment by kent-mcleod** [comment]
> OK. So it seems like we've gone for the _workaround in ELF loader_ to ensure time starts at zero as opposed to _be able to deal with the timer wrapping_? Seems reasonable, 64-bit isn't going to overflow any time soon.

Yes.  The commit message in https://github.com/seL4/seL4/commit/2f358738850502e7a3d94d1641f7157eada8dc2a and the comment (https://github.com/seL4/seL4/blob/master/include/kernel/sporadic.h#L39) explain it somewhat.  It was deemed not worthwhile to try and verify a scheduler where the time could wrap around when a 64bit nanosecond timestamp would take tens or hundreds of years to get to that point.
