### ISSUE TITLE
seL4 License Implications

### ISSUE THREAD

**Issue by tsoutsman** [seL4/seL4#524]
Hi, I was looking into using seL4 for a small educational project. I was concerned about the license, but I came across [this helpful article](https://microkerneldude.wordpress.com/2019/12/09/what-does-sel4s-license-imply/) by Gernot Heiser. From what I gather, he's one of the leads(?) of the project, and I think the repository should include this link in either the README or LICENSE as it directly relates to seL4 and is very informative.

**Comment by lsf37** [comment]
Adding a link to the explainer sounds like a good idea, yes. I can look in to that.

Can I ask what concerns you had about the license? Is there anything different to Linux or other standard open source software?

**Comment by tsoutsman** [comment]
@lsf37 I want to ***try*** and use Rust to build something for a school project on seL4. As with most of my projects, I just want to slap an MIT license on it but, if you have GPL dependencies, you usually aren't allowed to do this (I think). Obviously, seL4, like Linux, includes an exception for user mode applications which, in the case of seL4, means that pretty much everything built on seL4 can have its own license regardless of GPL. As far as I can tell, GPL is quite common everywhere other than Rust, which is primarily dominated by MIT and Apache. 

I'm just a high school student, so I'm not very familiar with licensing, which is why I found the article very helpful.

**Comment by lsf37** [comment]
Cool, thanks for the explanation that makes sense.

One more question to figure out where I should put the link -- when you were looking for the license, did you find [LICENSE.md](https://github.com/seL4/seL4/blob/master/LICENSE.md) and the note there was too unclear or was it that you didn't see the file? (or something else)

Also: major props for using seL4 in a school project! 👍

**Comment by tsoutsman** [comment]
> when you were looking for the license, did you find LICENSE.md

Yes.

> the note there was too unclear

I think the note is clear if you understand licensing, particularly because it draws parallels to the Linux syscall exception. The article is helpful if you're new to open source in general.

> Also: major props for using seL4 in a school project!

Thanks!

**Comment by lsf37** [comment]
Cool, all good. Thanks for reporting this, I'll add the link to the license file.
