### ISSUE TITLE
Missing error code in ARMIRQIssueIRQHandlerTrigger

### ISSUE THREAD

**Issue by canarysnort01** [seL4/seL4#529]
Should this return path be setting an error code?

https://github.com/seL4/seL4/blob/12.1.0/src/arch/arm/object/interrupt.c#L52

**Comment by lsf37** [comment]
Yes, I think it should.

**Comment by lsf37** [comment]
`seL4_IllegalOperation` would make sense here. Do you want to put up a PR for it? (Happy to do it myself as well.)

**Comment by canarysnort01** [comment]
Hello @lsf37, sure I will make a PR.
