### ISSUE TITLE
Bug in invocation_header_gen.py on ia32?

### ISSUE THREAD

**Issue by cl91** [seL4/seL4#53]
In file `tool/invocation_header_gen.py`, around line 80:

```
enum sel4_arch_invocation_label {
    {{for label, condition in invocations}}
    ...
    {{label}} = nInvocationLabels,
    ...
    {{endfor}}
    nSeL4ArchInvocationLabels
}
```

On ia32, becasue `seL4_arch_invocations` is an empty list, this will cause `nSeL4ArchInvocationLabels` to be declared as 0, rather than `nInvocationLabels` as intented.

**Comment by cl91** [comment]
Any comments?

**Comment by AdrianDanis** [comment]
Hi @cl91 

Basically everyone at Data61 has been on Christmas holidays until this morning.

Definitely the generation is incorrect, seems to have come about as an unintended side effect of [this](https://github.com/seL4/seL4/commit/cf8be6639ff95484b9a0e89c58c1a1c784911460) change.

Thanks for letting us now

**Comment by cl91** [comment]
:+1: Thanks!

**Comment by cl91** [comment]
Do you guys accept patches from outside your company? If yes I have fixed this in [this pull request](https://github.com/seL4/seL4/pull/54) and tested it on both x86_64 and ia32.

**Comment by AdrianDanis** [comment]
We do accept patches, although unfortunately you need to [sign a CLA first](http://sel4.systems/Community/Contributing/). In this case I wasn't expecting a patch and so already did the change internally it just hasn't been pushed out here yet, although should be here by tomorrow.

**Comment by cl91** [comment]
Sure glad to hear! I'll close the pull request.
