### ISSUE TITLE
seL4_TCB_SetSpace is not documented for MCS

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#558]
The `SetSpace` call for MCS has different parameters than non-MCS kernels, however the documentation does not mention this.

**Comment by bennoleslie** [comment]
My understanding is that `fault_ep`  on non-MCS is an `seL4_Word` and is a cap address in the context of the `cspace_root`, while on MCS `fault_ep` is an `seL4_CPtr` and is a cap address in the caller's CSpace. Maybe for most cases this doesn't matter as libsel4 hides the difference. It definitely matter if you are making your own system call bindings.

**Comment by pingerino** [comment]
The documentation does have it (you can see it in the source) but it's probably not being generated properly: https://github.com/seL4/seL4/blob/master/libsel4/include/interfaces/sel4.xml#L259

**Comment by bennoleslie** [comment]
I have no idea how the documentation generator works, but could it be because the `manual_name` attribute is the same as for the non-MCS `manul_name` ? The other methods with variations for MCS have ` (MCS)` suffix. For example: https://github.com/seL4/seL4/blob/master/libsel4/include/interfaces/sel4.xml#L197

**Comment by pingerino** [comment]
Possibly, unfortunately I don't have time to get my hands dirty with code at the moment to check. Just emptying the contents of my head in the hope that it is useful :).

**Comment by bennoleslie** [comment]
Very helpful thanks! Someone with more knowledge of how the manual is built (perhaps @canarysnort01 ) might be able to take a look with that point.

**Comment by canarysnort01** [comment]
> I have no idea how the documentation generator works, but could it be because the `manual_name` attribute is the same as for the non-MCS `manul_name` ?

I haven't looked at the root cause yet but I think this is very likely. This is similar to #530.

**Comment by lsf37** [comment]
We figured out in #530 what to do for this, so hopefully the fix there will also resolve this issue.
