### ISSUE TITLE
kernel/boot.c nitpick

### ISSUE THREAD

**Issue by berkus** [seL4/seL4#56]
in allocate_bi_frame():

```
    /* create the bootinfo frame object */
    pptr = alloc_region(BI_FRAME_SIZE_BITS); <--allocated BI_FRAME_SIZE_BITS
    if (!pptr) {
        printf("Kernel init failed: could not allocate bootinfo frame\n");
        return 0;
    }
    clearMemory((void*)pptr, PAGE_BITS); <-- clear PAGE_BITS
```

It allocates one size, but clears another. Per chance they are the same so the whole thing didn't blow up.

**Comment by AdrianDanis** [comment]
Currently yes they are [defined to the same thing](https://github.com/seL4/seL4/blob/master/include/bootinfo.h#L20). The `clearMemory` should be made to use the same constant name though. Thanks for noticing
