### ISSUE TITLE
Why do we have seL4_Uint32 and not use uint32_t instead?

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#561]
What is there reason to have these custom integer type definitions:
- `seL4_Uint8`
- `seL4_Uint16`
- `seL4_Uint32`
- `seL4_Uint64`
and not use the std C types here? Is there a fear this might conflict with some std lib definitions somewhere?

**Comment by bennoleslie** [comment]
FWIW, I also have the same question. It seems like `stdint.h` would be available (and correct) in any compilers to be used with seL4, and `stdint.h` is need even in freestanding versino of the C environment.

**Comment by kent-mcleod** [comment]
All external header dependencies were removed to avoid any possible conflicts from the rest of the compilation environment.  I believe that the change that removed all standard-lib dependencies came from this mailing list thread [1].  The topic of conversation was libc of which stdint.h is a very small subset, but I think the arguments would still be made for not having a dependency on stdint.h too.

[1]: https://lists.sel4.systems/hyperkitty/list/devel@sel4.systems/thread/Q2MR4LC3LTZQX245TLQ34KQMYN55O6UE/

**Comment by bennoleslie** [comment]
Thanks for doing the mailing list archeaology @kent-mcleod 

I'll need to read more carefully, but we already include stdint.h in the kernel. And I would consider stdint.h (at least) to be part of the *compiler* and not the C library.

4.6 of the C99 standard (draft available here: http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf) indicates that in freestanding you have access to the contents of `float.h`, `iso646.h`, `limits.h`, `stdarg.h`, `stdbool.h`, `stddef.h`, and `stdint.h`

We already include `stdint.h` and `stdarg.h` in many files inside the kernel.

**Comment by kent-mcleod** [comment]
> We already include `stdint.h` and `stdarg.h` in many files inside the kernel.

These are kernel include files that the kernel controls though: https://github.com/seL4/seL4/blob/master/include/stdint.h

The kernel also controls it's own environment.  The kernel is compiled with -std=c99 but doesn't require this of userlevel.

**Comment by bennoleslie** [comment]
Ahh OK. I was misunderstanding the issue. `seL4_Uint*` is primarily a `libsel4` thing rather than a kernel thing. Makes more sense, but still seems unnecessary. I didn't find the linked thread particularly convincing (because I believe stdint.h should be provided by the compiler not the libc). But I certainly don't think there is any value in changing this now. If we've already gone to the trouble of dealing with all those edge cases, no need to rip it out.

**Comment by nspin** [comment]
I have been including parts of libsel4 in the Linux kernel for paravirtualization. I see the ability to include libsel4 anywhere without collisions to be another benefit of the current approach.
