### ISSUE TITLE
cap_get_capType(cap) ==    vs cap_capType_equals

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#567]
It seems there are two different ways of checking whether or not a cap is a of a given type.

In some places: `cap_capType_equals(cap, cap_type)` is used, while in other `cap_get_capType(cap) == cap_type` is used.

Is there a reason for having the two different approaches used?

**Comment by lsf37** [comment]
I think (but might be wrong) that `cap_capType_equals` is used only in the fastpath and might be making some assumptions about what has already been checked, potentially not using `cap_get_capType(cap)` internally.

The standard form to use is `cap_get_capType(cap) == cap_type`

**Comment by bennoleslie** [comment]
Thanks @lsf37 . I did see it only used on the fast path. The implementation (on aarch64 at least) appears identical to me:

```static inline uint64_t CONST
cap_get_capType(cap_t cap) {
    return (cap.words[0] >> 59) & 0x1full;
}

static inline int CONST
cap_capType_equals(cap_t cap, uint64_t cap_type_tag) {
    return ((cap.words[0] >> 59) & 0x1full) == cap_type_tag;
}```

But not everything is aarch64, so perhaps it is different elsewhere.

**Comment by lsf37** [comment]
There is probably some trickery on 32-bit platforms, because we don't have enough bits in all caps to encode all types

**Comment by lsf37** [comment]
Yes, things like:
```c
static inline uint32_t CONST
cap_get_capType(cap_t cap) {
    if ((cap.words[0] & 0xe) != 0xe)
        return (cap.words[0] >> 0) & 0xfu;
    return (cap.words[0] >> 0) & 0xffu;
}
```
