### ISSUE TITLE
Analyze c89 dependencies in the proofs

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#576]
In `src/object/interrupt.c` the code 
```
    switch (intStateIRQTable[IRQT_TO_IDX(irq)]) {
    case IRQSignal: {
        cap_t cap;
        cap = intStateIRQNode[IRQT_TO_IDX(irq)].cap;
```
can't be changed into declaring and initializing the variable in the same statement
```
    switch (intStateIRQTable[IRQT_TO_IDX(irq)]) {
    case IRQSignal: {
        cap_t cap = intStateIRQNode[IRQT_TO_IDX(irq)].cap;
```
without the proofs complaining. Analyze why this is the case, maybe there are c89 assumption that cold be dropped.

**Comment by lsf37** [comment]
It's likely something about the exact syntactic structure of the statement in the proof. The proofs never made assumptions about C89, it was always for C99 (only the source was more conservative in the beginning).

**Comment by lsf37** [comment]
Closing this one, since this is just regular proof sensitivity towards code structure.
