### ISSUE TITLE
Remove support for ARMv6 and KZM/imx31

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/seL4#578]
This has been advertised for over a year now:
- https://lists.sel4.systems/hyperkitty/list/devel@sel4.systems/thread/EQ27WYPJIN3KKRGB4VNXUZKJYL65IZ6J/
- https://sel4.discourse.group/t/should-we-continue-to-support-armv6-and-kzm-imx31/46

This platform is unavailable to purchase anywhere for many years now, and the KZM/ArmV6 specific parts of the kernel make it harder to understand the existing code and can be a maintenance burden (Eg the globals frame). 

For the kernel this involves removing:
- The KZM/imx31 platform
- kernel drivers only used by this platform
- Arm1136JF_S CPU
- ArmV6 architecture

We will also remove any KZM platform support from user level libraries.

**Comment by lsf37** [comment]
I would be in favour. @seL4/tsc any comments? (anyone else is welcome to comment as well, of course)

**Comment by pingerino** [comment]
I've wanted to do this for years :)

**Comment by axel-h** [comment]
Fine for me

**Comment by gernotheiser** [comment]
Yes, please!

**Comment by Xaphiosis** [comment]
Fine by me.

**Comment by corlewis** [comment]
Sounds good to me as well.

**Comment by gernotheiser** [comment]
Hmm, this went a bit fast, and strictly in violation of policy: https://sel4.atlassian.net/browse/RFC-1

It's probably ok as there may not be any of these left in the community, but we shouldn't simply ignore our own policies.

**Comment by kent-mcleod** [comment]
> Hmm, this went a bit fast, and strictly in violation of policy: https://sel4.atlassian.net/browse/RFC-1

It hasn't been removed yet.  I did announce intention to remove it over a year ago on the mailing list on the discourse discussion 2 years before that everyone confirmed that they weren't using it.  So does this have to go through an RFC process if it won't actually have any impact on the community?

**Comment by lsf37** [comment]
Nothing has happened yet, these are open pull requests. The only ones that get merged are github tests.

**Comment by lsf37** [comment]
> So does this have to go through an RFC process if it won't actually have any impact on the community?

I guess Gernot is right. We do say

> Examples of changes that must follow the RFC process include:
>
> * Removing support for a platform

We also say 

> All substantial changes to the seL4 ecosystem must be made using the RFC process. Substantial changes are those that that impact a large number of users of seL4 in a way that may require them to change their own projects, changes the operation of toolchain used to build projects on seL4, changes the underlying model of one or more software components within the ecosystem.

where the 1 year call kinda does make clear nobody is affected

But just to make sure we haven't missed anyone, let's put up a short RFC for removal of the platform and armv6.

**Comment by lsf37** [comment]
We can in the meantime still put up all necessary pull requests etc, and the RFC doesn't have to be open forever either.

**Comment by kent-mcleod** [comment]
> - Removing support for a platform

This isn't stated on https://sel4.atlassian.net/browse/RFC-1 and so I missed it.  It does seem to be described here: https://docs.sel4.systems/processes/rfc-process.html#when-to-follow-the-rfc-process

I agree with the principle.  People choosing a platform likely want to know that if support for that platform is ever ended it will first go through an RFC process.  Is there anyone who wants to help me write up an RFC for this :)?

**Comment by mbrcknl** [comment]
> Is there anyone who wants to help me write up an RFC for this :)?

✋

**Comment by kent-mcleod** [comment]
Ok I think I've found and removed all of the places in the various code repositories.  There's still https://github.com/sel4/docs and the manual: https://github.com/seL4/seL4/blob/master/manual/parts/intro.tex#L18

**Comment by mbrcknl** [comment]
RFC draft is up: https://sel4.atlassian.net/browse/RFC-8

Let me know if there are any issues with it. I'll post to the mailing list and original discourse thread later this evening.

**Comment by lsf37** [comment]
Thanks for doing that, it looks good from my side.

**Comment by lsf37** [comment]
> Ok I think I've found and removed all of the places in the various code repositories. There's still https://github.com/sel4/docs and the manual: https://github.com/seL4/seL4/blob/master/manual/parts/intro.tex#L18

Happy to do the manual tomorrow.

**Comment by mbrcknl** [comment]
How long should we allow for comments on the RFC before putting this to the TSC? Consensus is already reasonably clear, but we still want it to be a genuine RFC process. Is two weeks too short?

**Comment by lsf37** [comment]
> How long should we allow for comments on the RFC before putting this to the TSC? Consensus is already reasonably clear, but we still want it to be a genuine RFC process. Is two weeks too short?

Given that multiple calls have gone out already and that's been going on for over a year, 2 weeks is fine, I would say. If there is a comment that anyone needs more time, we can extend.

> How long should we allow for comments on the RFC before putting this to the TSC? Consensus is already reasonably clear, but we still want it to be a genuine RFC process. Is two weeks too short?

Now done

**Comment by kent-mcleod** [comment]
Everything's merged now.
