### ISSUE TITLE
lex.py broken with recent changes

### ISSUE THREAD

**Issue by podhrmic** [seL4/seL4#61]
This line https://github.com/seL4/seL4/blob/master/tools/lex.py#L46 causes this error:

```
# make
[KERNEL]
 [MKDIR] arch/object
 [PBF_GEN] arch/object/structures.pbf
 [PBF_GEN] plat/32/plat_mode/machine/hardware.pbf
 [PBF_GEN] 32/mode/api/shared_types.pbf
 [BF_GEN] arch/object/structures_gen.h
Traceback (most recent call last):
  File "/home/podhrad/Workspace/sel4/test_default/kernel/tools/bitfield_gen.py", line 29, in <module>
    import lex
  File "/home/podhrad/Workspace/sel4/test_default/kernel/tools/lex.py", line 46, in <module>
    from past.builtins import cmp
ImportError: No module named past.builtins
/home/podhrad/Workspace/sel4/test_default/kernel/Makefile:699: recipe for target 'arch/object/structures_gen.h' failed
make[1]: *** [arch/object/structures_gen.h] Error 1
tools/common/project.mk:258: recipe for target 'kernel_elf' failed
make: *** [kernel_elf] Error 2

```

After commenting out line 46 compilation works as before.

**Comment by heshamelmatary** [comment]
Hi,

There are new python dependencies required. You can add them by running:
`sudo pip install sel4-deps`

Please see https://github.com/seL4/seL4/commit/7333e97c65c9bf6c3545fc45eb5c4e424d3f8994 for more details

**Comment by podhrmic** [comment]
Ah, thanks for the info @heshamelmatary . Is this change reflected in the install pages? Such as https://github.com/SEL4PROJ/sel4-tutorials/blob/master/Prerequisites.md and http://sel4.org/Info/GettingStarted/DebianToolChain.pml

**Comment by stevebob** [comment]
Thanks for pointing those out. I'll update them today.

**Comment by lsf37** [comment]
closing this one as done.
