### ISSUE TITLE
asid_map may not get initialized when CONFIG_VTX is not set

### ISSUE THREAD

**Issue by mokshasoft** [seL4/seL4#62]
Compilation error generated by clang:
~/seL4test/kernel/src/arch/x86/64/kernel/vspace.c:786:9: error: variable 'asid_map' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
    if (cap_get_capType(vspaceCapSlot->cap) == cap_pml4_cap) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/seL4test/kernel/src/arch/x86/64/kernel/vspace.c:798:59: note: uninitialized use occurs here
    poolPtr->array[asid & ((1ul << (asidLowBits))-1ul)] = asid_map;
                                                          ^~~~~~~~
~/seL4test/kernel/src/arch/x86/64/kernel/vspace.c:786:5: note: remove the 'if' if its condition is always true
    if (cap_get_capType(vspaceCapSlot->cap) == cap_pml4_cap) {
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/seL4test/kernel/src/arch/x86/64/kernel/vspace.c:785:5: note: variable 'asid_map' is declared here
    asid_map_t asid_map;
    ^

Problematic code from ~/seL4test/kernel/src/arch/x86/64/kernel/vspace.c:
exception_t 
performASIDPoolInvocation(asid_t asid, asid_pool_t *poolPtr, cte_t *vspaceCapSlot) 
{ 
    asid_map_t asid_map; 
    if (cap_get_capType(vspaceCapSlot->cap) == cap_pml4_cap) { 
        cap_pml4_cap_ptr_set_capPML4MappedASID(&vspaceCapSlot->cap, asid); 
        cap_pml4_cap_ptr_set_capPML4IsMapped(&vspaceCapSlot->cap, 1); 
        asid_map = asid_map_asid_map_vspace_new(cap_pml4_cap_get_capPML4BasePtr(vspaceCapSlot->cap)); 
    } else { 
#ifdef CONFIG_VTX 
        assert(cap_get_capType(vspaceCapSlot->cap) == cap_ept_pml4_cap); 
        cap_ept_pml4_cap_ptr_set_capPML4MappedASID(&vspaceCapSlot->cap, asid); 
        cap_ept_pml4_cap_ptr_set_capPML4IsMapped(&vspaceCapSlot->cap, 1); 
        asid_map = asid_map_asid_map_ept_new(cap_ept_pml4_cap_get_capPML4BasePtr(vspaceCapSlot->cap)); 
#endif 
    } 
    poolPtr->array[asid & MASK(asidLowBits)] = asid_map; 
    return EXCEPTION_NONE; 
}

**Comment by AdrianDanis** [comment]
Hi @mokshasoft it should be noted that this case cannot actually happen. If `CONFIG_VTX` is not set then the only valid cap that can be passed to this function is a `cap_pml4_cap`. This is already enforced prior to the call site of `performASIDPoolInvocation` in [`decodeX86MMUInvocation#1448`](https://github.com/seL4/seL4/blob/master/src/arch/x86/kernel/vspace.c#L1448)

**Comment by mokshasoft** [comment]
Hi @AdrianDanis I can see that now. I'll close the issue.
