### ISSUE TITLE
As a hypervisor,the guest os system performs poorly

### ISSUE THREAD

**Issue by Makebug** [seL4/seL4#663]
we run a linux system on the hypervisor which use sel4, and we found the guest os  performs poorly.
The relevant performance data can only reach 70% ~ 80% of the original.
Like the read and write rate for qspi 
every interrupt that occurs,is handled by the sel4 kernel, dispatched to the VMM and then injected into the  guest os .
Under the normal load condition , the whole process consumes more than 10 subtleties .
With a higher load , the whole process takes much more time.
![irq](https://user-images.githubusercontent.com/16549608/143409911-6cbb15ca-3faf-4b24-bd7e-24f7aef9cf8a.png)

Do we have a better optimization plan ?

Sorry, it is unknown whether the question can be raised here !
Hope to get a reply
thanks!

hardware platform:armv8 a55

**Comment by Indanz** [comment]
70-80% of original performance with high IRQ or latency sensitive loads (small transactions) seems pretty good to me.

Step 3 can be optimised away by letting the VMM handle guest IRQs directly.

**Comment by Makebug** [comment]
@Indanz 
thanks for your reply

**1. 70-80% of original performance with high IRQ or latency sensitive loads (small transactions) seems pretty good to me.**
-->:really? What are the performance data that you test? 
**2. Step 3 can be optimised away by letting the VMM handle guest IRQs directly.**
-->: you mean direct call **_irq_server_node_handle_irq_** in irq_server_thread?.
![image](https://user-images.githubusercontent.com/16549608/143512492-90e84399-c523-45a6-9e9a-2d75fdd08692.png)
-->:yes ,I have tried it already .  it will cause new issues,
-->:it will cause maintance irq notification loss when the load of the guest os is high
![image](https://user-images.githubusercontent.com/16549608/143513528-41592fba-f76f-4ce0-bb28-968e403540bc.png)

i'm working on this issue, have u meet the similiar issue?

**Comment by gernotheiser** [comment]
On 26 Nov 2021, at 12:30, ZhaZhaGang ***@***.******@***.***>> wrote:

1. 70-80% of original performance with high IRQ or latency sensitive loads (small transactions) seems pretty good to me.
-->:really? What are the performance data that you test?

I assume your 70–80% refers to throughput? Networking performance is a bit of a complex beast and in general you need to look at throughput, CPU utilisation and latency. Throughput alone is only a good measure when the CPU is maxed out (100%) in both configurations.

I agree with @Indanz<https://github.com/Indanz> that a 20–30% degradation in a virtualised system isn’t bad, particularly with small packets (assuming that’s the full story, i.e. CPU maxed out in both configurations).

Having said that, we’re aware that our CAmkES-level communication layer isn’t as optimised as it could be (while still competitive with most other systems I’ve seen). We’re about to start a major project on a device virtualisation framework, but it’ll take some time until this produces usable outcomes.

Gernot

**Comment by Indanz** [comment]
> really? What are the performance data that you test?
@Makebug: Personal experience with performance testing in general and just common sense really. 

Without more information what performance you are measuring it's impossible to say if 70%-80% loss is a lot or not. Are you using DMA or transferring qspi data byte-by-byte? If the qspi is very fast, you may need bigger transactions to improve performance. Or is it just general filesystem performance? What kind of load? Details matter a lot.

But considering your measurements my guess is that the guest OS takes 40 us per transaction to handle, which seems like a very latency sensitive load to me.

If this is networking you really should enable interrupt coalescing (NAPI in Linux).

> you mean direct call irq_server_node_handle_irq in irq_server_thread?
We use a custom VMM, I'm not familiar with the code of the one you use. But it only speeds things up if the overhead is in the IPC at step 3, if it's the irq handling code then merging them doesn't help much of course. If it's only one specific interrupt that's performance critical you could add special code to handle that first.

For what we're doing the virtualisation overhead is negligible. Initially it was bad because we got the priorities wrong, but after fixing that everything has been fine.

> With a higher load , the whole process takes much more time.
This is a sign that the priorities are not correct. Try giving either irq_server or the vm a higher priority than the other, or use different budgets/periods if using MCS.

> it will cause maintance irq notification loss when the load of the guest os is high
This sounds like a bug.

Are you running the guest OS on the same CPU core as the VM?

Also,  have you tried with the latest code on git of seL4 and everything else you're using?

**Comment by Makebug** [comment]
@Indanz @gernotheiser thansk for your reply

> Without more information what performance you are measuring it's impossible to say if 70%-80% loss is a lot or not. Are you using DMA or transferring qspi data byte-by-byte? If the qspi is very fast, you may need bigger transactions to improve performance. Or is it just general filesystem performance? What kind of load? Details matter a lot.
> 
> But considering your measurements my guess is that the guest OS takes 40 us per transaction to handle, which seems like a very latency sensitive load to me.

I‘ll review my linux driver code, there may be some problems.

> Are you running the guest OS on the same CPU core as the VM?

Yes, but i try to use one cpu core to run vmm and other cpu core run guest os. they are the same.

> Also, have you tried with the latest code on git of seL4 and everything else you're using?

I'll try with the latest code

I ran cyclictest app on guest os and native os, the tested results varied widely
[https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/cyclictest](url)
![cyclictest](https://user-images.githubusercontent.com/16549608/143800813-98d01480-0371-4538-9b92-bcfaca1b9293.png)

To measure latencies, Cyclictest runs a non real-time master thread (scheduling class SCHED_OTHER) which starts a defined number of measuring threads with a defined real-time priority (scheduling class SCHED_FIFO). The measuring threads are woken up periodically with a defined interval by an expiring timer (cyclic alarm). Subsequently, the difference between the programmed and the effective wake-up time is calculated and handed over to the master thread via shared memory. The master thread tracks the latency values and prints the minimum, maximum, and average latencies.

Maybe the latency is too long in the guest os  :( !. 
Is there any optimization point ?

[native_linux.txt](https://github.com/seL4/seL4/files/7615152/native_linux.txt)
[cyclictest_guestOS.txt](https://github.com/seL4/seL4/files/7615153/cyclictest_guestOS.txt)

**Comment by Makebug** [comment]
@Indanz 

> That said, are those latencies in ms or in us? If ms, something horrible is wrong.

us

**Comment by kent-mcleod** [comment]
- The irq_server could be removed and the IRQ delivered directly to the VMM thread.  This would remove the additional seL4 IPC between the irq_server and VMM thread.
- There's potentially additional seL4 syscalls happening between the vmm thread receiving the IRQ and blocking on the endpoint again which would increase latency.  Also if you are using the MCS configuration, the seL4_SendRecv() syscall can be used to inject the irq and block on the faultep with a single kernel entry.
- Depending on which GIC implementation your platform is using, there's some hardware virtualization mechanisms that the kernel isn't taking advantage of yet which could collapse some context switching via associating virtual interrupts with physical intrerrupts on the ack path.

**Comment by Makebug** [comment]
@kent-mcleod  thanks ! 

> * The irq_server could be removed and the IRQ delivered directly to the VMM thread.  This would remove the additional seL4 IPC between the irq_server and VMM thread.
> * There's potentially additional seL4 syscalls happening between the vmm thread receiving the IRQ and blocking on the endpoint again which would increase latency.  Also if you are using the MCS configuration, the seL4_SendRecv() syscall can be used to inject the irq and block on the faultep with a single kernel entry.

I will try it. 

> * Depending on which GIC implementation your platform is using, there's some hardware virtualization mechanisms that the kernel isn't taking advantage of yet which could collapse some context switching via associating virtual interrupts with physical intrerrupts on the ack path.

what we are use is gic-400(GICv2)

**Comment by ProdigyYanng** [comment]
> @kent-mcleod thanks !
> 
> > * The irq_server could be removed and the IRQ delivered directly to the VMM thread.  This would remove the additional seL4 IPC between the irq_server and VMM thread.
> > * There's potentially additional seL4 syscalls happening between the vmm thread receiving the IRQ and blocking on the endpoint again which would increase latency.  Also if you are using the MCS configuration, the seL4_SendRecv() syscall can be used to inject the irq and block on the faultep with a single kernel entry.
> 
> I will try it.
> 
> > * Depending on which GIC implementation your platform is using, there's some hardware virtualization mechanisms that the kernel isn't taking advantage of yet which could collapse some context switching via associating virtual interrupts with physical intrerrupts on the ack path.
> 
> what we are use is gic-400(GICv2)

I am very interested in how to run a virtual machine on arm, but I have not practiced successfully on my Raspberry Pi 4. Can you please refer to your steps?

**Comment by ProdigyYanng** [comment]
I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.

**Comment by chenwanlei** [comment]
> I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.

[CAmkES ARM VMM](https://docs.sel4.systems/projects/camkes-arm-vm/)
参考这个教程，最下面有介绍如何将seL4 VMM在其他平台跑起来

**Comment by ProdigyYanng** [comment]
> > I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.
> 
> [CAmkES ARM VMM](https://docs.sel4.systems/projects/camkes-arm-vm/) 参考这个教程，最下面有介绍如何将seL4 VMM在其他平台跑起来

Thanks for your reply. But this article seems like it doesn't support my Raspberry Pi 4B , is there any other information?
谢谢你的回答，但是这篇文章好像不支持我的树莓派4B，有其他教程或者说明吗？

**Comment by chenwanlei** [comment]
> > > I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.
> > 
> > 
> > [CAmkES ARM VMM](https://docs.sel4.systems/projects/camkes-arm-vm/) 参考这个教程，最下面有介绍如何将seL4 VMM在其他平台跑起来
> 
> Thanks for your reply. But this article seems like it doesn't support my Raspberry Pi 4B , is there any other information? 谢谢你的回答，但是这篇文章好像不支持我的树莓派4B，有其他教程或者说明吗？

仔细看`How do I update camkes-arm-vm to support platform ‘X’` 这一节，然后对照已有例程，同样ARMv8架构的平台做修改啊

**Comment by ProdigyYanng** [comment]
> 然后

哦哦我明白了，谢谢，我会认真看看的！ 还有一个问题想请教您，我当前已经成功在rpi4上跑起来了selL4微内核，参考了这篇文章https://research.csiro.au/tsblog/sel4-raspberry-pi-3/，得到了"All is well in the universe"的输出（但不能再交互控制），那么下一步我该如何写相关程序运行到微内核上面呢？我该参考什么样的文章呢？


Oh, I understand, thank you, I will take a closer look! There I want to ask you another question. I have successfully run the selL4 microkernel on rpi4. Refer to this article https://research.csiro.au/tsblog/sel4-raspberry -pi-3/ and got it "Everything in the universe is fine" output (but can no longer be controlled interactively, like shell), then how do I write related programs to run on the microkernel? ?

**Comment by ProdigyYanng** [comment]
> > > > I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.
> > > 
> > > 
> > > [CAmkES ARM VMM](https://docs.sel4.systems/projects/camkes-arm-vm/) 参考这个教程，最下面有介绍如何将seL4 VMM在其他平台跑起来
> > 
> > 
> > Thanks for your reply. But this article seems like it doesn't support my Raspberry Pi 4B , is there any other information? 谢谢你的回答，但是这篇文章好像不支持我的树莓派4B，有其他教程或者说明吗？
> 
> 仔细看`How do I update camkes-arm-vm to support platform ‘X’` 这一节，然后对照已有例程，同样ARMv8架构的平台做修改啊

哦哦我明白了，谢谢，我会认真看看的！ 还有一个问题想请教您，我当前已经成功在rpi4上跑起来了selL4微内核，参考了这篇文章https://research.csiro.au/tsblog/sel4-raspberry-pi-3/，得到了"All is well in the universe"的输出（但不能再交互控制），那么下一步我该如何写相关程序运行到微内核上面呢？我该参考什么样的文章呢？

Oh, I understand, thank you, I will take a closer look! There I want to ask you another question. I have successfully run the selL4 microkernel on rpi4. Refer to this article https://research.csiro.au/tsblog/sel4-raspberry -pi-3/ and got it "Everything in the universe is fine" output (but can no longer be controlled interactively, like shell), then how do I write related programs to run on the microkernel? ?

**Comment by chenwanlei** [comment]
> > > > > I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.
> > > > 
> > > > 
> > > > [CAmkES ARM VMM](https://docs.sel4.systems/projects/camkes-arm-vm/) 参考这个教程，最下面有介绍如何将seL4 VMM在其他平台跑起来
> > > 
> > > 
> > > Thanks for your reply. But this article seems like it doesn't support my Raspberry Pi 4B , is there any other information? 谢谢你的回答，但是这篇文章好像不支持我的树莓派4B，有其他教程或者说明吗？
> > 
> > 
> > 仔细看`How do I update camkes-arm-vm to support platform ‘X’` 这一节，然后对照已有例程，同样ARMv8架构的平台做修改啊
> 
> 哦哦我明白了，谢谢，我会认真看看的！ 还有一个问题想请教您，我当前已经成功在rpi4上跑起来了selL4微内核，参考了这篇文章[https://research.csiro.au/tsblog/sel4-raspberry-pi-3/，得到了"All](https://research.csiro.au/tsblog/sel4-raspberry-pi-3/%EF%BC%8C%E5%BE%97%E5%88%B0%E4%BA%86%22All) is well in the universe"的输出（但不能再交互控制），那么下一步我该如何写相关程序运行到微内核上面呢？我该参考什么样的文章呢？
> 
> Oh, I understand, thank you, I will take a closer look! There I want to ask you another question. I have successfully run the selL4 microkernel on rpi4. Refer to this article https://research.csiro.au/tsblog/sel4-raspberry -pi-3/ and got it "Everything in the universe is fine" output (but can no longer be controlled interactively, like shell), then how do I write related programs to run on the microkernel? ?

我也是刚开始学习，目前还只是在qemu上跑过，不太清楚硬件怎么搞，可以加个联系方式一起学习，我的微信：chenwanlei

**Comment by ProdigyYanng** [comment]
> chenwanlei

好的，已经申请了，Thank you

**Comment by wjhtinger** [comment]
> we run a linux system on the hypervisor which use sel4, and we found the guest os performs poorly. The relevant performance data can only reach 70% ~ 80% of the original. Like the read and write rate for qspi every interrupt that occurs,is handled by the sel4 kernel, dispatched to the VMM and then injected into the guest os . Under the normal load condition , the whole process consumes more than 10 subtleties . With a higher load , the whole process takes much more time. ![irq](https://user-images.githubusercontent.com/16549608/143409911-6cbb15ca-3faf-4b24-bd7e-24f7aef9cf8a.png)
> 
> Do we have a better optimization plan ?
> 
> Sorry, it is unknown whether the question can be raised here ! Hope to get a reply thanks!
> 
> hardware platform:armv8 a55

Hi，do you have solved this isssue?

**Comment by Makebug** [comment]
> > we run a linux system on the hypervisor which use sel4, and we found the guest os performs poorly. The relevant performance data can only reach 70% ~ 80% of the original. Like the read and write rate for qspi every interrupt that occurs,is handled by the sel4 kernel, dispatched to the VMM and then injected into the guest os . Under the normal load condition , the whole process consumes more than 10 subtleties . With a higher load , the whole process takes much more time. ![irq](https://user-images.githubusercontent.com/16549608/143409911-6cbb15ca-3faf-4b24-bd7e-24f7aef9cf8a.png)
> > Do we have a better optimization plan ?
> > Sorry, it is unknown whether the question can be raised here ! Hope to get a reply thanks!
> > hardware platform:armv8 a55
> 
> Hi，do you have solved this isssue?

yes,i inject irq to vcpu directly in sel4 kernel

**Comment by wjhtinger** [comment]
> > > we run a linux system on the hypervisor which use sel4, and we found the guest os performs poorly. The relevant performance data can only reach 70% ~ 80% of the original. Like the read and write rate for qspi every interrupt that occurs,is handled by the sel4 kernel, dispatched to the VMM and then injected into the guest os . Under the normal load condition , the whole process consumes more than 10 subtleties . With a higher load , the whole process takes much more time. ![irq](https://user-images.githubusercontent.com/16549608/143409911-6cbb15ca-3faf-4b24-bd7e-24f7aef9cf8a.png)
> > > Do we have a better optimization plan ?
> > > Sorry, it is unknown whether the question can be raised here ! Hope to get a reply thanks!
> > > hardware platform:armv8 a55
> > 
> > 
> > Hi，do you have solved this isssue?
> 
> yes,i inject irq to vcpu directly in sel4 kernel

So，you modified the sel4 kernel source code?
