### ISSUE TITLE
x86 UEFI support by using Multiboot2 with GRUB2

### ISSUE THREAD

**Issue by alex-ab** [seL4/seL4#67]

**Comment by alex-ab** [comment]
I added the current commits as are for the moment.

@AdrianDanis: you meant that the ACPI RSDP information should not be specifically transferred via the bootinfo, instead by the extralen bootinfo mechanism, right ? Should just the ACPI RSDP specific part be copied or the whole multiboot2 data (which contains a copy of ACPI RSDP). I presume I would need a kind of identification for the multiboot2 copy in the seL4_BootInfoHeader ? (to differentiate just ACPI RSDP data or Multiboot2 data or/and Multiboot 1 data?)

**Comment by AdrianDanis** [comment]
I don't think the whole multiboot2 data need be copied (or at least not as whole block). Some header for ACPI/RSDP information seems sufficient, that way it can be filled from any source, mbi2 or otherwise

**Comment by alex-ab** [comment]
I switched to provide the ACPI RSDP via the extra bootinfo page. Please have a look at 55acca4db9416e7b9db1a4243b58be7d5b310b86

**Comment by AdrianDanis** [comment]
@alex-ab Yep that is more what I was imagining with bootinfo

**Comment by alex-ab** [comment]
Ok. Please make suggestions, if any,, to enhance the commit to make it fit for addition to your repository. From my side I'm in principle done for now.

**Comment by AdrianDanis** [comment]
The main issue is the large duplication in the boot code. I don't see any obvious reason this couldn't be refactored

**Comment by alex-ab** [comment]
Adjusted in 7e9694b59e33b7080945dab070a709fc5a99ef1a

**Comment by AdrianDanis** [comment]
You have the choice of mbi1 or mbi2 driving the entire boot path, which I think is a little backwards, and has resulted in a bunch of stuff in a `try_load_boot_module` that doesn't seem to be in any way related to loading a boot module. Rather we just want to pull the information out of the differently structured mbi structures and keep on going. Given that we already put most things into the `boot_state` global I think it'd make more sense to have two versions for initializing that, then calling into the actual general booting in `try_boot_sys`.

**Comment by alex-ab** [comment]
Adjusted in 27bc140865e82bbf3bb8d80c2a58b91d8ae27960.

**Comment by AdrianDanis** [comment]
I was imagining a structure more like

```c
    if (multiboot_magic == MULTIBOOT_MAGIC) {
        result = try_parse_mbi1(mbi);
    } else if (multiboot_magic == MULTIBOOT2_MAGIC) {
        result = try_parse_mbi2(mbi);
    } else {
        printf("Boot loader is not multiboot 1 or 2 compliant %lx\n", multiboot_magic);
    }
    if (result) {
        result = try_boot_sys();
    }
```

Might need to return some additional information from the 'parse' functions, or add more fields to the book state structures to pass the extra data, like the rsdp or module information along.

Also can I encourage you to follow the (admittedly sometimes mixed) existing style in the kernel, or run install astyle and run the 'make style' target in the makefile.

And sorry for the delay in getting back to you.

**Comment by alex-ab** [comment]
Adjusted in fefddf4391d06757db1262a7a751b3ca41ac8dce. Sorry for the delay, main work items moved away from sel4 for now.

**Comment by AdrianDanis** [comment]
@alex-ab looks pretty good now. Similar to your other issues I don't know how to pull arbitrary commits off github, so you'll need to link a branch or PR or something

**Comment by alex-ab** [comment]
@AdrianDanis: we normally just fetch and cherry-pick the commits, but of course I can create pull requests

**Comment by AdrianDanis** [comment]
@alex-ab Well in this case I only need the PR as it tells me the remote/ref of 'alex-ab/seL4.git issue_67_5'. If there's a way to determine that information from the hashes and links in this thread so that I can fetch and cherry-pick without needing the PR then I'd love to know.

**Comment by chelmuth** [comment]
Unfortunately, this information cannot be taken from the plain commit-hash reference. An option is to prepend the hash with the the user that forked the repo, e.g., alex-ab@fefddf4.

**Comment by alex-ab** [comment]
@AdrianDanis: Thanks. I incorporated the current seL4 kernel master branch into Genode and needed a small patch. With 9196023aa6dd2b8433c043cb7b79e7e51ad29887 I got multiboot2 with uefi running. The acpi_init will not find on UEFI machines any RSDP pointer by searching (what the acpi_init does), and according to the comment in try_boot_sys actually the acpi_validate_rsdp is intended to be called. What do you think ?

**Comment by AdrianDanis** [comment]
Argh, yes you are completely correct, that was exactly what I intended to do, but somehow messed it up. Thanks for catching, and sorry for messing that up. Will pull in your commit

**Comment by alex-ab** [comment]
Thanks.
