### ISSUE TITLE
Why does timestamp() on x86 not simply call x86_rdtsc()

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#670]
Why does `include/arch/x86/arch/benchmark.h` do this:
```
static inline uint64_t timestamp(void)
{
    uint32_t low, high;

    asm volatile(
        "movl $0, %%eax \n"
        "movl $0, %%ecx \n"
        "cpuid          \n"
        "rdtsc          \n"
        "movl %%edx, %0 \n"
        "movl %%eax, %1 \n"
        "movl $0, %%eax \n"
        "movl $0, %%ecx \n"
        "cpuid          \n"
        : "=r"(high), "=r"(low)
        : /* no inputs */
        : "eax", "ebx", "ecx", "edx"
    );

    return ((uint64_t) high) << 32llu | (uint64_t) low;
}
```
instead of just calling `x86_rdtsc()` from `include/arch/x86/arch/machine.h` that is implemented as 
```
static inline uint64_t x86_rdtsc(void)
{
    uint32_t hi, lo;
    asm volatile("rdtsc"
                 : "=a"(lo),
                 "=d"(hi)
                );
    return ((uint64_t) hi) << 32llu | (uint64_t) lo;
}
```

**Comment by axel-h** [comment]
According to https://stackoverflow.com/questions/27693145/rdtscp-versus-rdtsc-cpuid this is done as a kind of fence operation. But there are dedicates fence instruction available now that could be used.

**Comment by kent-mcleod** [comment]
It's to ensure that the rdtsc is serialized with respect to all other operations in the instruction stream (not just memory ones).

**Comment by axel-h** [comment]
After reading a bit into the topic this sequence seems a legacy thing. Is changing this to `rdtscp`and/or using dedicated instructions like `mfence` or`lfence` an option?

**Comment by kent-mcleod** [comment]
I believe it would still be different behavior and would mean that you aren't using the same measurement mechanisms across different benchmark version.  rdtscp doesn't serialize in the same way as cpuid, and is also different from mfence and lfence.  I don't think there is one-best-way-to-timestamp here and different benchmarks would have good arguments for using different variants based on the trade-offs they want to make between measurement impact and accuracy.
