### ISSUE TITLE
i want the python modules and libraries that are used to build stand alone system programs based on SeL4 services  please. i have tried the libraries mentioned in the documentation but are not working with me.

### ISSUE THREAD

**Issue by maimuna99** [seL4/seL4#672]

**Comment by lsf37** [comment]
Hi @maimuna99, I'm not sure if you are asking a different question than in #669. The main supported language on top of seL4 is currently C. There are some projects that use Rust, which seems to be working fairly well. Running python on top of seL4 to write system programs is not currently supported.

The seL4 python libraries are build tools that are used to build and compile seL4 itself.

ps: the GitHub UI can be a bit unintuitive. Please use only a short title for issues and put the longer description in the "description" field. GitHub issues are not a good place to ask general questions, though, you will get more audience and potential replies if you try the [seL4 discourse forum](https://sel4.discourse.group) or the [mailing list](https://lists.sel4.systems/postorius/lists/devel.sel4.systems/).

**Comment by maimuna99** [comment]
yes, this is a different question, in which I am willing to make a  stand-alone python system program for SeL4 but without actually incorporating it on top of SeL4.thats why i was asking for the modules . and please excuse my brief knowledge of using Github i'm still new to it

**Comment by axel-h** [comment]
Could you describe in more detail what exactly you want to do and what workflow you want to use. I don't understand for example what you mean by "python system program" that does not run on top of seL4.
