### ISSUE TITLE
sporadic assertion failure for SCHED_CONTEXT_0014

### ISSUE THREAD

**Issue by lsf37** [seL4/seL4#677]
The test case is labelled "Test deleting a scheduling context while it runs out of budget on another core", and is usually passing fine, but [in this case](https://github.com/seL4/seL4/runs/4360776261?check_suite_focus=true#step:4:13090) failed an assertion that should never fail  (config PC99_debug_SMP_MCS_gcc_32):

`seL4 failed assertion 'refill_size(sc) < sc->scRefillMax' at /github/workspace/kernel/src/kernel/sporadic.c:136 in function refill_add_tail`

This issue is to investigate under which circumstances this assertion could fail and fix the cause.

Relevant part of the test log:
```
<testcase classname="sel4test" name="SCHED_CONTEXT_0014">
  Running test SCHED_CONTEXT_0014 (Test deleting a scheduling context while it runs out of budget on another core)
  seL4 failed assertion 'refill_size(sc) < sc->scRefillMax' at /github/workspace/kernel/src/kernel/sporadic.c:136 in function refill_add_tail
  halting...
  Kernel entry via Interrupt, irq 159
  
  [[Timeout]]
  None
  
  console_run returned -1
  Shutting down skylake
  
  Command exited with non-zero status 255
  0.08user 0.02system 10:44.13elapsed 0%CPU (0avgtext+0avgdata 6828maxresident)k
  0inputs+360outputs (0major+8610minor)pagefaults 0swaps
  >>> command failed, aborting.
  +++ mq.sh sem -signal skylake -k 1518282425-hw-run-0
  -----------[ end test PC99_debug_SMP_MCS_gcc_32 ]-----------
PC99_debug_SMP_MCS_gcc_32 FAILED
```

**Comment by lsf37** [comment]
@mktnk3 @michaelmcinerney do we have any invariants/preconditions from the verification that would tell us more about the state at this point in the code?

**Comment by axel-h** [comment]
Look like https://github.com/seL4/seL4/issues/633 from @Indanz and https://github.com/seL4/seL4/pull/636 is the proposed fix.

**Comment by lsf37** [comment]
That's why this sounded so familiar, thanks for making the connection. Yes, it does look very much like that is the same issue.

**Comment by Indanz** [comment]
I wrote that test specifically to trigger this bug. I didn't expect the test to be merged quicker than the fix though.

**Comment by lsf37** [comment]
Yeah, I screwed up on this one. The sel4test PR linked to something that was merged already and I hadn't looked properly thinking it was the fix, but it was not.

I might have to revert the sel4test commit, unless we can merge the proper fix first. It looks like the discussion was almost done.

**Comment by lsf37** [comment]
Ok, closing this as duplicate. Discussion should be on #633 and #636
