### ISSUE TITLE
Invalid syntax.

### ISSUE THREAD

**Issue by Shadowblitz16** [seL4/seL4#682]
I am following the directions directly from https://docs.sel4.systems/projects/buildsystem/host-dependencies.html

And I get this...
```
shadowblitz16@Kubuntu-Node202:~/Documents/src/c/seL4test$ repo init -u https://github.com/seL4/seL4test-manifest.git
warning: gpg (GnuPG) is not available.
warning: Installing it is strongly encouraged.

warning: templates not found /build/git-repo-publish/parts/git/install/usr/share/git-core/templates
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Counting objects: 140, done
remote: Finding sources: 100% (5/5)
remote: Total 5 (delta 0), reused 5 (delta 0)
Unpacking objects: 100% (5/5), done.
From https://gerrit.googlesource.com/git-repo
   4a478ed..2a089cf  main       -> origin/main
  File "/home/shadowblitz16/Documents/src/c/seL4test/.repo/repo/main.py", line 79
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
```

**Comment by axel-h** [comment]
This looks like a python 2 vs. python 3 issue an an old version of `repo`. Try running `python2 repo ...`

**Comment by Shadowblitz16** [comment]
I am using python3 as python and I got the repo from the official instructions so it shouldn't be outdated

**Comment by axel-h** [comment]
Try passing the full path to the repo tool.

**Comment by Shadowblitz16** [comment]
full path?

**Comment by axel-h** [comment]
You must have the tool somewhere locally, try `which repo`

**Comment by axel-h** [comment]
Or get the latest version from https://gerrit.googlesource.com/git-repo

**Comment by Shadowblitz16** [comment]
```
shadowblitz16@Kubuntu-Node202:~/Documents/src/c/seL4test$ python2 /snap/bin/repo init -u https://github.com/seL4/seL4test-manifest.git
```

**Comment by axel-h** [comment]
what does the script `/snap/bin/repo` do?

**Comment by Shadowblitz16** [comment]
idk but when i run cat on it, it spits out a bunch of binary garbage

**Comment by axel-h** [comment]
That might be a precompiled version then. Try cloning the google git repo and then run `<patch-to>/repo init ....`. If this fails try `python2 <patch-to>/repo init ....`

**Comment by kent-mcleod** [comment]
How did you install the repo tool? Normally you would get a text file python script from following the instructions:
```
$ mkdir -p ~/.bin
$ PATH="${HOME}/.bin:${PATH}"
$ curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
$ chmod a+rx ~/.bin/repo
```

It looks like there's now an option to install using a distro package manager. And it looks like that package manager version is using the wrong python version.

**Comment by Shadowblitz16** [comment]
I tried that but that was the part the gpg keys failed when I ran apt update

**Comment by axel-h** [comment]
I'm usually cloning the google repo to bootstrap things an run the first `repo init ...`. Once that succeeded you have local copy in `/.repo/repo/repo` in the manifest repo you a cloning. So from then on you can also run `.repo/repo/repo ...` for each repository unter repo control.

**Comment by kent-mcleod** [comment]
> I tried that but that was the part the gpg keys failed when I ran apt update.
> I spent like a hour trying to remove it.

I don't quite follow sorry.  Do you mean that installing the repo tool using curl was later causing your apt update to fail?

**Comment by Shadowblitz16** [comment]
@kent-mcleod ya

**Comment by Shadowblitz16** [comment]
> That might be a precompiled version then. Try cloning the google git repo and then run `<path-to>/repo init ....`. If this fails try `python <path-to>/repo init ....` (that should use your default python3). If this still fails try forcing python 2 with `python2 <path-to>/repo init ....`

This works as far as I can tell. 
It took me a while to figure out where to run it though.

**Comment by kent-mcleod** [comment]
Maybe the program name `repo` is used for something else on your Ubuntu installation.  So when the curl install instructions above prepend the download location to the front of the path it causes the wrong repo program to be used during apt commands.  
If you don't add the new program to the path (skip: `$ PATH="${HOME}/.bin:${PATH}"`) and then use the full path to it when invoking `repo init` that could work?

**Comment by Shadowblitz16** [comment]
> Maybe the program name `repo` is used for something else on your Ubuntu installation. So when the curl install instructions above prepend the download location to the front of the path it causes the wrong repo program to be used during apt commands. If you don't add the new program to the path (skip: `$ PATH="${HOME}/.bin:${PATH}"`) and then use the full path to it when invoking `repo init` that could work?

Idk but I am scared to try.
repo wasn't installed until I did sudo apt-get install git-repo

**Comment by kent-mcleod** [comment]
Ok that's fine.  What version of Ubuntu are you using in case this comes up again in the future?

**Comment by Shadowblitz16** [comment]
I am on Kubuntu 20.04

**Comment by kent-mcleod** [comment]
It looks like this is the package that apt installed: https://snapcraft.io/install/git-repo/ubuntu
It looks like it's possible for apt to install snap packages if snap is installed: https://askubuntu.com/questions/1345385/how-can-i-stop-apt-from-installing-snap-packages

That git-repo package hasn't been updated since 2017 which explains why it's still running python2 internally.  This breaks because repo always downloads the newest version when it's initializing a new repository and then uses that.  Since 2017 repo has switched from python2 to python3 and so trying to load the newer python3 version from within a python2 exe is what causes the syntax error at the top.

I'm not sure what would have caused key errors when running `apt update` after installing the tool. It looks like the tool itself believes that gpg isn't installed so maybe the system paths were having trouble locating it.
