### ISSUE TITLE
Cannot host container in seL4test folder.

### ISSUE THREAD

**Issue by Shadowblitz16** [seL4/seL4#683]
```bash
shadowblitz16@Kubuntu-Node202:~/Documents/src/c/seL4test$ container
make: Entering directory '/home/shadowblitz16/Documents/src/c/seL4test'
make: *** No rule to make target 'user'.  Stop.
make: Leaving directory '/home/shadowblitz16/Documents/src/c/seL4test'
shadowblitz16@Kubuntu-Node202:~/Documents/src/c/seL4test$ 
```
![image](https://user-images.githubusercontent.com/2453707/144322375-74cef8c9-2edd-4066-9e23-100386901506.png)

**Comment by kent-mcleod** [comment]
It looks like the `container` shell alias is pointing to a different directory from the docker files repository.
What does `type container` give you?

**Comment by Shadowblitz16** [comment]
```
container is aliased to `make -C ./ user HOST_DIR=$(pwd)'
```

**Comment by kent-mcleod** [comment]
When you set the alias, the path to the docker repository needs to be an absolute path.
https://docs.sel4.systems/projects/dockerfiles/#getting-a-build-environment:
```
echo $'alias container=\'make -C /<path>/<to>/seL4-CAmkES-L4v-dockerfiles user HOST_DIR=$(pwd)\'' >> ~/.bashrc
# now open a new terminal, or run `source ~/.bashrc
```

**Comment by Shadowblitz16** [comment]
thankyou.

**Comment by Shadowblitz16** [comment]
@kent-mcleod

**Comment by lsf37** [comment]
Which folder is it that you don't have?

**Comment by Shadowblitz16** [comment]
I got the docker files folder idk how though
