### ISSUE TITLE
Should we break the label 'hw-build' down into ARM, RISC-V and x86

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#693]
Currently we have a generic label `hw-build`. Is there a gain if there are dedicated labels `hw-build-arm`, `hw-build-riscv`, `hw-build-x86` also to reduce the number of build that are done? Some changes only affect one architecture and this could be used to reduce the load a bit while still having some mire Ci coverage.

**Comment by lsf37** [comment]
I don't think that's a good idea:

- they are running in parallel anyway, so we are not saving time if we request a single one
- the label setup is a mess that can't be centralised (has to be duplicated in every workflow)
- the point of the hw-build label is to catch problems we're not expecting, specifically those cases where we think a change should only affect one arch, but does actually affect others.

**Comment by axel-h** [comment]
Main intention here is be reducing consumed CPU time on the github could (or wherever this might run). If this is not (yet) a problem because it's mostly free or withing the throttling limits, then there is no gain spending time on this.

**Comment by lsf37** [comment]
The GitHub limits don't go by CPU time, they are only on the maximum number of concurrent jobs and are fairly generous on the current plan. I don't think we've hit those limits yet (if we start a lot of jobs in multiple repos on multiple PRs we will hit them, but the only effect is that it waits until some other previous job finishes, and there are a lot of very short ones like link checks etc).

The AWS time is billed per CPU time and limited by number of VMs, but those affect only the proof jobs.
