### ISSUE TITLE
Why does CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS exist?

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#716]
I wonder why `CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS` exists - what is/was the usecase? In the current form enforcing this seems to be of limited practical use, as there is no differentiation between device and free memory caps. We stop creating caps when this limit is hit, even is there is still space in the root C-Node. Device caps are created first, then boot code recycling happens and finally memory caps are created from the free memory. Should `CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS` be removed? Or should it be replaced by separate limits for CONFIG_MAX_NUM_BOOTINFO_UNTYPED_MEMORY_CAPS' and CONFIG_MAX_NUM_BOOTINFO_UNTYPED_DEVICE_CAPS'. However, I can see a usecase only for limiting the memory caps. Limiting the device caps by numer does not really make sense. Here it seem more useful to have a dedicated way to configure the overall device caps (see https://github.com/seL4/seL4/issues/714)
Assuming that the only reason `CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS` exists is, that the array size in the boot info must be define somehow and this value can't be computed during kernel compillation, the boot should abort if this number is too small. Currently the boot continues in this case and just provides less caps to the system - which does not really make much sense. See also https://github.com/seL4/seL4/pull/648#issuecomment-997480274.

**Comment by yyshen** [comment]
It exists because the bootinfo structure  is 4KiB (if I read correctly that the extra bi_frame_vptr is only  used when DTB is provided), so there should be an upper bound for the array size.

**Comment by axel-h** [comment]
We could also provide additional descriptors in the extra boot info then if this is ever needed. Currently there is space or 501 descriptors in the boot info page and that seems sufficient on all standard platforms.

**Comment by axel-h** [comment]
As @lsf37 stated in https://github.com/seL4/seL4/pull/721#discussion_r777755358, the constant `CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS` exists because the verification requested this. Using open arrays as final element in structs is not supported, so we have to give something in `seL4_BootInfo` for the `seL4_UntypedDesc untypedList[]`array.
The current default value in the CMake scripts is 230, this is chosen that `sizeof(seL4_BootInfo)` remains within one 4 KiByte page. Since `seL4_UntypedDesc` effectively uses 2 words, that make 16 byte on 64-bit platform and 8 byte on 32-bit platform. 
The value 230 is driven by the limit on 64-bit platforms, on 32-bit platform values up to 500 work.

**Comment by kent-mcleod** [comment]
> As @lsf37 stated in [#721 (comment)](https://github.com/seL4/seL4/pull/721#discussion_r777755358), the constant `CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS` exists because the verification requested this.

It's also there as a configuration option to allow the initial task to create static memory allocations that it can rely on being large enough to hold all the untypeds it will be given.
