### ISSUE TITLE
I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.

### ISSUE THREAD

**Issue by ProdigyYanng** [seL4/seL4#731]
I want to practice running sel4 as a VMM (hypervisor) on my rpi4, and then running a virtual machine on it, but I don’t know how to practice it. I currently just start the microkernel of sel4 on rpi4 and complete the "universal all is well", but I don’t know what to do next.

_Originally posted by @ProdigyYanng in https://github.com/seL4/seL4/issues/299#issuecomment-1002382517_

**Comment by lsf37** [comment]
It looks like your question has been answered on the unrelated issue #663, so I'm closing this here.

**Comment by axel-h** [comment]
There was an attempt to add some documentation in this direction at https://github.com/seL4/docs/pull/38, but this is looking for somebody to continue the work
