### ISSUE TITLE
extra boot info pages should not be executable

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#734]
Currently the boot info frame is mapped non-executable, but the extra boot info pages are mapped executable. There seems no good use case why the extra boot info should be executable by default. The root task could still remap this e.g. for exotic things like passing a firmware binary via a device tree...
Seems the practical reason why the pages are executable is, because `create_frames_of_region()` does not expose a parameter to specify the frames should be executable or not.

**Comment by kent-mcleod** [comment]
The current boot code policy gives the initial task all the initial capabilities to system resources with unrestricted rights.  The bootinfo frame and the ipc frame are mapped non-executable and everything else is executable.  The boot code policy also maps all initial task code and data frames executable at the moment.

**Comment by kent-mcleod** [comment]
The roottask could always remap the extended region non-executable if it wanted to prevent itself from accidentally executing code in there.

**Comment by freddy123098** [comment]
So may I help in this issue?

**Comment by lsf37** [comment]
I agree, the current policy is that init task is fully trusted and must be high assurance or a high assurance system. Making the kernel code more complex to guard against initialiser bugs is the wrong trade-off.

I'm closing this issue for now as wont-do, but feel free to re-open if there is strong disagreement.
