### ISSUE TITLE
There may be a comma missing here.

### ISSUE THREAD

**Issue by s-c-c** [seL4/seL4#743]
https://github.com/seL4/seL4/blob/c3b4df0f30aa4476d6686cc338a0b6a46987dc8c/libsel4/sel4_arch_include/ia32/sel4/sel4_arch/syscalls.h#L147

**Comment by axel-h** [comment]
Indeed, https://godbolt.org/z/qohbW1cY6 says that the comma can't be omiutted at
https://github.com/seL4/seL4/blob/c3b4df0f30aa4476d6686cc338a0b6a46987dc8c/libsel4/sel4_arch_include/ia32/sel4/sel4_arch/syscalls.h#L147-L148

Why does this error not show up anywhere, is this dead code?

**Comment by kent-mcleod** [comment]
> Why does this error not show up anywhere, is this dead code?

It looks like it could be due to essentially dead code.  This file has two definitions of these functions, the error is inside `#if defined(__pic__)`.  `-fno-pic` is usually used for compiling user level which would avoid this error in all of the projects used in CI.

**Comment by lsf37** [comment]
Right, esp for ia32 (vs x64). It'd be nice to have at least compilation covered for this case somewhere. Where would it make most sense to include something like this?

**Comment by kent-mcleod** [comment]
You can reproduce the compilation error when building for sel4test with the following change:
```
diff --git a/cmake-tool/helpers/environment_flags.cmake b/cmake-tool/helpers/environment_flags.cmake
index cb2c912..0675d6b 100644
--- a/cmake-tool/helpers/environment_flags.cmake
+++ b/cmake-tool/helpers/environment_flags.cmake
@@ -29,8 +29,8 @@ macro(add_default_compilation_options)
 
     add_compile_options(
         -nostdinc
-        -fno-pic
-        -fno-pie
+        -fpic
+        -fpie
         -fno-stack-protector
         -fno-asynchronous-unwind-tables
         -ftls-model=local-exec
```

**Comment by kent-mcleod** [comment]
> Right, esp for ia32 (vs x64). It'd be nice to have at least compilation covered for this case somewhere. Where would it make most sense to include something like this?

They were added for Genode in https://github.com/seL4/seL4/commit/fbeb95edb927fa1c7f8cd9b0b33d3db1d7725339 (https://github.com/seL4/seL4/issues/34). Genode still uses 9.01 which doesn't have the MCS changes yet (https://github.com/genodelabs/genode/blob/master/repos/base-sel4/ports/sel4.port#L7).
