### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by hariramm7** [seL4/seL4#75]
Hii
Can anyone please help me how to install sel4 on top of ubuntu?
Like the instructions for installation

Thanks

**Comment by latentPrion** [comment]
Hi, @hariramm7 : Sorry, I have to sort of proceed by assuming you're asking how to get the seL4 build dependencies? If so, you can try following the instructions on this page:

https://research.csiro.au/tsblog/getting-started-sel4-camkes-l4v-dependencies/

If you don't want to do the whole docker thing, which I personally don't like much, you can just look into the dockerfiles and copy out the package names from there and manually enter them into the Ubuntu terminal as `apt-get install` commands:

https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/blob/master/sel4.dockerfile
https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/blob/master/sel4_tests.dockerfile
https://github.com/SEL4PROJ/seL4-CAmkES-L4v-dockerfiles/blob/master/camkes.dockerfile

I think those three are the relevant dockerfiles which list the full set of packages needed to build the seL4 kernel, the seL4Test project, and CAmkES based projects. Let me know how things go~

**Comment by AdrianDanis** [comment]
Closing this as it's not an issue. @hariramm7 feel free to continue discussion and get help on the [mailing list](https://sel4.systems/lists/listinfo/)

**Comment by hariramm7** [comment]
Hello @latentPrion Thanks for helping me. I have tried installing sel4 with whole docker thing. All went well until last step. I have run building sel4 and after that step, only 105 tests are passed out of 202 and not proceeding further. please go through the attachment.
![untitled](https://user-images.githubusercontent.com/32526484/32191781-3637fcf0-bd80-11e7-8fbe-97f6dfd9da24.png)
