### ISSUE TITLE
remove branch rpi4?

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#750]
Is https://github.com/seL4/seL4/commits/rpi4 still an active branch with RasPi4 things or can this be removed (or renamed) because it was for testing only? Currently it's a bit misleading because this is not the place to expect some RasPi4 things.

**Comment by lsf37** [comment]
You're right, this can be removed. I was hoping that I could add the rpi4 board to the test, but it's still not working properly.

**Comment by lsf37** [comment]
Branch deleted.

**Comment by axel-h** [comment]
Thanks
