### ISSUE TITLE
Missing pre-built images for trying it out

### ISSUE THREAD

**Issue by StefanSchroeder** [seL4/seL4#753]
I am unable to locate pre-built images with sel4 for example for QEmu or the Raspberry Pi.
There is a lot of documentation about bulding your own, but these are pretty involved and complex.

I'd like to try out the kernel before spending the time to fiddle with the compiler.

Something like a "sel4-hello-world.img" would be nice. Perhaps it exists somewhere, but I cannot find it.

**Comment by axel-h** [comment]
Unfortunately, the short answer is: Sorry, there are no official pre-build images at the moment

The longer answer with some suggestion what to do:
- The practical idea really is, that one clones the repos locally and then builds things in the docker containers that are provided. Docker allows a "non-invasive" way to try things out, assuming you have docker set up on the host. The whole toolchain (compiler, haskell ....) and even a QEMU simulation environment exists inside the container. This provides a flexible way to standardize toolchain environments across many developers and system.
Note that docker is a bit more lightweight than providing whole VMs, but some people have expressed the wish to get a full VM instead. The GitHub CI actions actually create such a VM on demand, so technically the building blocks exist, but are not exposed. Needs somebody willing to contribute here....
- What you can also do, is use the GitHub CI action to make it build such image. Fork the sel4 repo and then make a dummy PR to your fork using the label "hw-build". This will build sel4test images that you can download. See https://github.com/axel-h/seL4/pull/51 for an exmaple. If you click on "Detail" for one of the "seL4Test HW / HW Build" and then choose "Summay" you can download the images when you click on the number below "Artifacts". The "armv8a" build produces RasPi3 and RasPi4 images. See https://github.com/axel-h/seL4/actions/runs/1752289082 for example. Unfortunately, you have to wait for all hw build jobs to finish before the artifacts appear. Something in the direction of https://github.com/seL4/seL4/issues/693 might be useful if we promote the the GitHUb CI build customization...
![image](https://user-images.githubusercontent.com/12140423/151221373-76dd5844-1237-4729-ab55-cdbba4fac11c.png)

Now, for the "try out the kernel" part I have some doubts that running a pre-built image is really what you want. It will print "hello world" eventually and there is not really much to try out - except that it works. Providing a pre-build "sel4test" and "sel4bench" may make some more sense, as one can easily capture and compare the results then for slightly different board revisions.
If you just want to see what sel4test prints, you can look at the GitHub CI test output for the QEMU simulation job "seL4Test Sim / Simulation", it  runs for every PR even without using the label "hw-build". 

We'd have to come up with a list of demo system that could be provided to show something more. But I wonder how much gain there is compared to the existing example systems that one can build from the sources. Non of them is really interactive or has a shell or GUI. Are you looking for something like "Genode on seL4" (https://genode.org) in the end, that you can actually "play" with?

**Comment by StefanSchroeder** [comment]
Thank you, Axel, for the great and elaborate answer. I will definitely investigate this further.

**Comment by StefanSchroeder** [comment]
See previous comment. With Axel's explanation it becomes clear why there are (currently) no pre-built images.

**Comment by kent-mcleod** [comment]
You can also download images from existing CI runs under the "Actions" tab of various application repositories:
- sel4test: https://github.com/seL4/seL4/actions/workflows/sel4test-hw.yml
- sel4bench: https://github.com/seL4/sel4bench/actions/workflows/sel4bench.yml
