### ISSUE TITLE
seL4test on my Nvidia TX1  Failed.

### ISSUE THREAD

**Issue by Comet959** [seL4/seL4#755]
Help me!
    I am running sel4test on my TX1 according to the official tutorial, but I get a problem again and again. For the newly purchased TX1, I directly connected my Ubuntu host with UART serial port.
   At the same time, I follow this instruction  ( https://docs.sel4.systems/Hardware/jetsontx1.html ), pulled the latest sel4test project code, successfully ran ninja command and built images "sel4test-driver-image-arm-tx1". Everything seemed to be going very smoothly. I use the newly purchased SanDisk 64GB SD card to boot my image, which has been formatted in ext4 format.
    Then I use command `sudo screen / dev / ttyusb0 115200`  to open the UART serial port.  After pressing and holding the power key for 1 second, and TX1 starts. Then I hit the Enter key to make TX1 cancel the auto boot default image and enter the u-boot interactive command line. 
    Then, according to the instruction, under uboot, I typed the following command to load the image and start from the address 0x82000000:

    ext4load mmc 1 0x82000000 sel4test-driver-image-arm-tx1
    go 0x82000000

    Finally, I failed to start sel4test as I wanted. After many repetitions, I got the same error. This is my output：
------------------------------------------------------------------------------------------------------------------------------------------

    Tegra210 (P2371-2180) # ext4load mmc 1 0x82000000 sel4test-driver-image-arm-tx1

    5247256 bytes read in 260 ms (19.2 MiB/s)

    Tegra210 (P2371-2180) # go 0x82000000

    ## Starting application at 0x82000000 ...

ELF-loader started on CPU: ARM Ltd. Cortex-A57 r1p1

  paddr=[80a57000..80f58117]

No DTB passed in from boot loader.

Looking for DTB in CPIO archive...found at 80b825e0.

Loaded DTB from 80b825e0.

   paddr=[8023d000..8024afff]

ELF-loading image 'kernel' to 80000000

  paddr=[80000000..8023cfff]

  vaddr=[ffffff8080000000..ffffff808023cfff]

  virt_entry=ffffff8080000000

ELF-loading image 'sel4test-driver' to 8024b000

  paddr=[8024b000..80661fff]

  vaddr=[400000..816fff]

  virt_entry=40f0b8

Enabling MMU and paging

Jumping to kernel-image entry point...

Warning:  gpt_cntfrq 19200000, expected 12000000

Bootstrapping kernel

available phys memory regions: 2

  [80000000..ff000000]

  [100000000..180000000]

reserved virt address space regions: 3

  [ffffff8080000000..ffffff808023d000]

  [ffffff808023d000..ffffff808024b000]

  [ffffff808024b000..ffffff8080662000]

seL4 failed assertion 'cap_get_capType(destSlot->cap) == cap_null_cap' at /home/yjy/Desktop/sel4-rpi/sel4test_newv2/kernel/src/object/cnode.c:426 in function cteInsert

halting...

Kernel entry via Interrupt, irq 0

**Comment by ProdigyYanng** [comment]
Can someone help me ? I don't know what to do next.

**Comment by ProdigyYanng** [comment]
@berkus @sorear @zhicheng @alistair23

**Comment by yyshen** [comment]
@ProdigyYanng Can you check if the correct physical memory region is supplied to the kernel? Are there any physical memory regions reserved by secure world or other purposes?

**Comment by ProdigyYanng** [comment]
> @ProdigyYanng Can you check if the correct physical memory region is supplied to the kernel? Are there any physical memory regions reserved by secure world or other purposes?

Thank you! But I tried to change the original 0x82000000 load address to 0x8000000, but it didn't work. I use NVIDIA Jetson TX1. How can I check whether the correct kernel address is provided?

**Comment by yyshen** [comment]
> > @ProdigyYanng Can you check if the correct physical memory region is supplied to the kernel? Are there any physical memory regions reserved by secure world or other purposes?
> 
> 
> 
> Thank you! But I tried to change the original 0x82000000 load address to 0x8000000, but it didn't work. I use NVIDIA Jetson TX1. How can I check whether the correct kernel address is provided?

You may take a look at the Linux DTS for the board to confirm if there are any reserved or cutout memory regions.

**Comment by Comet959** [comment]
> > > @ProdigyYanng Can you check if the correct physical memory region is supplied to the kernel? Are there any physical memory regions reserved by secure world or other purposes?
> > 
> > 
> > Thank you! But I tried to change the original 0x82000000 load address to 0x8000000, but it didn't work. I use NVIDIA Jetson TX1. How can I check whether the correct kernel address is provided?
> 
> You may take a look at the Linux DTS for the board to confirm if there are any reserved or cutout memory regions.

Thank you, I'm checking my board, it may take me a lot time. By the way, if there is reserved memory region, the next, should i change the dts file for deleting the reserved region ? Or find the correct dts file to replace?

**Comment by yyshen** [comment]
> > > > @ProdigyYanng Can you check if the correct physical memory region is supplied to the kernel? Are there any physical memory regions reserved by secure world or other purposes?
> > > 
> > > 
> > > Thank you! But I tried to change the original 0x82000000 load address to 0x8000000, but it didn't work. I use NVIDIA Jetson TX1. How can I check whether the correct kernel address is provided?
> > 
> > 
> > You may take a look at the Linux DTS for the board to confirm if there are any reserved or cutout memory regions.
> 
> Thank you, I'm checking my board, it may take me a lot time. By the way, if there is reserved memory region, the next, should i change the dts file for deleting the reserved region ? Or find the correct dts file to replace?

I suggest you try the steps suggested by Peter in the mailing list first, to see if the known-good image works on your board.

**Comment by Comet959** [comment]
> > > > > @ProdigyYanng Can you check if the correct physical memory region is supplied to the kernel? Are there any physical memory regions reserved by secure world or other purposes?
> > > > 
> > > > 
> > > > Thank you! But I tried to change the original 0x82000000 load address to 0x8000000, but it didn't work. I use NVIDIA Jetson TX1. How can I check whether the correct kernel address is provided?
> > > 
> > > 
> > > You may take a look at the Linux DTS for the board to confirm if there are any reserved or cutout memory regions.
> > 
> > 
> > Thank you, I'm checking my board, it may take me a lot time. By the way, if there is reserved memory region, the next, should i change the dts file for deleting the reserved region ? Or find the correct dts file to replace?
> 
> I suggest you try the steps suggested by Peter in the mailing list first, to see if the known-good image works on your board.

Thank you very much for your proposal. I have solved my mistake. I checked my board and eliminated the problem of tool chain and SD card. Then I re brushed the firmware of the board and it can work.

**Comment by yyshen** [comment]
> > > > > > @ProdigyYanng Can you check if the correct physical memory region is supplied to the kernel? Are there any physical memory regions reserved by secure world or other purposes?
> > > > > 
> > > > > 
> > > > > Thank you! But I tried to change the original 0x82000000 load address to 0x8000000, but it didn't work. I use NVIDIA Jetson TX1. How can I check whether the correct kernel address is provided?
> > > > 
> > > > 
> > > > You may take a look at the Linux DTS for the board to confirm if there are any reserved or cutout memory regions.
> > > 
> > > 
> > > Thank you, I'm checking my board, it may take me a lot time. By the way, if there is reserved memory region, the next, should i change the dts file for deleting the reserved region ? Or find the correct dts file to replace?
> > 
> > 
> > I suggest you try the steps suggested by Peter in the mailing list first, to see if the known-good image works on your board.
> 
> Thank you very much for your proposal. I have solved my mistake. I checked my board and eliminated the problem of tool chain and SD card. Then I re brushed the firmware of the board and it can work.

So you think it is a software version issue? You mean you flashed the secure world OS or uboot?

**Comment by Comet959** [comment]
> > > > > > > @ProdigyYanng Can you check if the correct physical memory region is supplied to the kernel? Are there any physical memory regions reserved by secure world or other purposes?
> > > > > > 
> > > > > > 
> > > > > > Thank you! But I tried to change the original 0x82000000 load address to 0x8000000, but it didn't work. I use NVIDIA Jetson TX1. How can I check whether the correct kernel address is provided?
> > > > > 
> > > > > 
> > > > > You may take a look at the Linux DTS for the board to confirm if there are any reserved or cutout memory regions.
> > > > 
> > > > 
> > > > Thank you, I'm checking my board, it may take me a lot time. By the way, if there is reserved memory region, the next, should i change the dts file for deleting the reserved region ? Or find the correct dts file to replace?
> > > 
> > > 
> > > I suggest you try the steps suggested by Peter in the mailing list first, to see if the known-good image works on your board.
> > 
> > 
> > Thank you very much for your proposal. I have solved my mistake. I checked my board and eliminated the problem of tool chain and SD card. Then I re brushed the firmware of the board and it can work.
> 
> So you think it is a software version issue? You mean you flashed the secure world OS or uboot?

I reused NVIDIA jetpack 3.2.1, refreshed my board, and finally got the correct results.But I don't know what the root cause is.

**Comment by yyshen** [comment]
OK, thanks for the update. We can close this one, at least for now.
