### ISSUE TITLE
Insteresting cmake code in gcc.cmake, can' t understand it, is it a bug ?

### ISSUE THREAD

**Issue by ichdream** [seL4/seL4#779]
When I am trying to compile the source code of seL4，i find some interesting code which i can't understand.
Then i search it online, i can't find any sources releated to it.

Can anyone could explain it? Thanks

Below is the source code in gcc.cmake under seL4 folder.
Why add the symbol '@' before and after the variable value in `set` command, such as  `set(sel4_arch @KernelSel4Arch@)`?
```cmake
# When this file is passed to configure_file in cmake, these variables get set to
# the kernel platform configuration.
set(sel4_arch @KernelSel4Arch@)
set(arch @KernelArch@)
set(mode @KernelWordSize@)
set(cross_prefix @cross_prefix@)
```

**Comment by axel-h** [comment]
See https://cmake.org/cmake/help/latest/command/configure_file.html

**Comment by ichdream** [comment]
> See https://cmake.org/cmake/help/latest/command/configure_file.html

thanks, the usage of cmake `config_file` always come up with the `#cmakedefine` such as `#cmakedefine FOO_ENABLE`.
Then i searched the folder seL4，i can't find any usage of cmake `config_file` command.

So, it seems not be used for the cmake command `config_file`.

**Comment by axel-h** [comment]
It's `configure_file()` you have to search for.

**Comment by ichdream** [comment]
> It's `configure_file()` you have to search for.

Thanks, i find it .
Very interesting it coud used without `#cmakedefine` .
 Since it had been solved, I close this issue.
