### ISSUE TITLE
Container on Sel4

### ISSUE THREAD

**Issue by hariramm7** [seL4/seL4#78]
Hello

I installed sel4 on ubuntu o.s. Now I want to install container engine(Docker/kubernetes) on the top of Sel4 microkernel. 
Can anyone please help me with the steps.

Thanks.

**Comment by AdrianDanis** [comment]
@hariramm7 This is not seL4 kernel issue. As per my [comment in your previous issue](https://github.com/seL4/seL4/issues/75#issuecomment-339533601), such questions belong on the [mailing list](https://sel4.systems/lists/listinfo/)

The short answer to your docker question (although I do not understand your previous statement of "I installed sel4 on ubuntu") is that we have not yet built sufficient infrastructure that you can 'just install' something like Docker.

There are a couple of example VMM style applications for [arm](https://github.com/seL4proj/camkes-arm-vm) and [x86](https://github.com/seL4/camkes-vm), which is the closest we have to something like a container.
