### ISSUE TITLE
Any method to support to another board(platform) related to supported one ?

### ISSUE THREAD

**Issue by ichdream** [seL4/seL4#781]
Since now, seL4 support limited number of boards , which list in documentation.([supported platforms](https://docs.sel4.systems/Hardware/))
However, i want to run and test seL4 on my own board which is not in the list.
How should i do some changes to support my board?
The most important one are  dts files, which may could be derived from linux project.

But, i find the dts files in the `tools/dts` folder are not the raw dts file in the linux , they had been processed.
```c
 * This file is derived from an intermediate build stage of the
 * Linux kernel. The licenses of all input files to this process
 * are compatible with GPL-2.0-only.
```

So, how did it? Is there any tool to achieve it ?

Thanks.

**Comment by axel-h** [comment]
> How should i do some changes to support my board?
This depends how different your board is form the currently supported platforms. In the best case general support for the SoC family already exists, so you don't have to write much code actually. Basically you can follow the instructions from https://docs.sel4.systems/projects/sel4/porting.html and add a new folder in `/src/plat/<your-baord>` with your board specific things.

**Comment by ichdream** [comment]
> What do you mean by "processed"? We aim to support unsupported DTS files, so usually these should work. For some platforms, the DTS file in Linux are split up, so we put them together again to have one single file. In the end, you need a DTS file for your platform that describes it well enough, soboth seL4 and your system on top of it find all necessary information.

The word "processed" means the `dts` files have some difference on their contents between linux and seL4.
For example, in the file `am33xx.dtsi` of linux:
``` bash
l4_wkup: interconnect@44c00000 {
			wkup_m3: wkup_m3@100000 {
				compatible = "ti,am3352-wkup-m3";
				reg = <0x100000 0x4000>,
				      <0x180000 0x2000>;
				reg-names = "umem", "dmem";
				ti,hwmods = "wkup_m3";
				ti,pm-firmware = "am335x-pm-firmware.elf";
			};
		};
```
however, in am335x-bone.dts of sel4, it becomes
```bash
l4_wkup@44c00000 {
			compatible = "ti,am3-l4-wkup\0simple-bus";
			#address-cells = < 0x01 >;
			#size-cells = < 0x01 >;
			ranges = < 0x00 0x44c00000 0x280000 >;

			wkup_m3@100000 {
				compatible = "ti,am3352-wkup-m3";
				reg = < 0x100000 0x4000 0x180000 0x2000 >;
				reg-names = "umem\0dmem";
				ti,hwmods = "wkup_m3";
				ti,pm-firmware = "am335x-pm-firmware.elf";
				phandle = < 0x24 >;
			};

			prcm@200000 {
				compatible = "ti,am3-prcm\0simple-bus";
				reg = < 0x200000 0x4000 >;
				#address-cells = < 0x01 >;
				#size-cells = < 0x01 >;
				ranges = < 0x00 0x200000 0x4000 >;

				clocks {
					#address-cells = < 0x01 >;
					#size-cells = < 0x00 >;

					clk_32768_ck {
						#clock-cells = < 0x00 >;
						compatible = "fixed-clock";
						clock-frequency = < 0x8000 >;
						phandle = < 0x17 >;
					};
....
```
they look different ...

So, i wonder it that the `dts` files in Linux should make some changes to be used in seL4.
Or, could i only move the dts file of Linux to seL4 `dts` folder?

**Comment by ichdream** [comment]
> 

I find the `script ` above provided from you, thanks.
I will try it again.

**Comment by axel-h** [comment]
> For example, in the file am33xx.dtsi of linux:
> ...
> they look different ...

This file might come from an older version of the DTS. We do not synchronize the files with the Linux versions regularly. Sometime, the DTS file also differ between the mainline linux and the vendor specific repos or SDKs. Regular updates would be a task for a platform maintainer - volunteers are welcome. Until then, there are no resources for this and they are good enough if things are working.

**Comment by ichdream** [comment]
> > For example, in the file am33xx.dtsi of linux:
> > ...
> > they look different ...
> 
> This file might come from an older version of the DTS. We do not synchronize the files with the Linux versions regularly. Sometime, the DTS file also differ between the mainline linux and the vendor specific repos or SDKs. Regular updates would be a task for a platform maintainer - volunteers are welcome. Until then, there are no resources for this and they are good enough if things are working.

Now, i understand it, thank you very much.

I also find the method to rescue me, and  next i will try it myself, hence, this issue should be closed.
