### ISSUE TITLE
Cannot run x64 image with Qemu

### ISSUE THREAD

**Issue by 130B848** [seL4/seL4#79]
After reading the [Qemu tutorial](https://wiki.sel4.systems/Hardware/Qemu#Compilation) on seL4 wiki, I can run 32-bit version smoothly with following scripts
```bash
make clean
make optiplex9020_defconfig
make silentoldconfig
make
cd images
qemu-system-x86_64  -m 512  -kernel kernel-ia32-pc99 -initrd capdl-loader-experimental-image-ia32-pc99 --enable-kvm  -smp 2 -cpu Nehalem,+vmx -nographic
```
However, I cannot run 64-bit version with error **fsgsbase instructions not supported by the processor** reported using almost the same scripts except x86_64 parameters.
```bash
......
make x64_optiplex9020_defconfig # x64
......
sudo qemu-system-x86_64  -m 512  -kernel kernel-x86_64-pc99 -initrd capdl-loader-experimental-image-x86_64-pc99 --enable-kvm  -smp 2 -cpu Nehalem,+vmx -nographic #x86_64
```
My CPU is i7 6700 (Skylake) and *FSGSBASE* is enabled (checked by *lscpu | grep fsgsbase*).
Can anyone help me, please?

**Comment by 130B848** [comment]
In addition, if I manually comment the **fsgsbase_enable** part in *kernel/src/arch/x86/64/head.S*, similar errors still occurs, such as "Huge page" and "INVPCID".

**Comment by wom-bat** [comment]
You need a later CPU model than Nehalem.  Try -cpu haswell
The Host CPU's capabilities aren't important for this -- it's the CPU that QEMU emulates.

There is a `make x86_64_simulate` target in sel4test that should work.

**Comment by wom-bat** [comment]
Alternatively, as I notice you're using the KVM accelerator under QEMU, use `-cpu host` to pass through all host CPU features.

**Comment by 130B848** [comment]
@wom-bat Thanks! `-cpu host` solves my problem! (Emm...not familiar with QEMU)
