### ISSUE TITLE
Shebang in Python files should use python2.7

### ISSUE THREAD

**Issue by HarveyHunt** [seL4/seL4#8]
When trying to build seL4 on distros where Python 3 is the default python (such as Arch), the build fails when running python files as they are are python2 code, instead of python3.

The shebang should be:

```
#!/usr/bin/env python2.7
```

**Comment by denibertovic** [comment]
/usr/bin/env python should use the default right? And if that's python3 it's going to fail, no?

**Comment by lsf37** [comment]
Sorry, meant to reply to this way earlier: default python is a problem either way. There are systems where there are no `python2` or `python2.7` executables (mostly those that still have a python2 default, which still seems to be more widespread, even though that slowly is changing). This includes some of our internal standard dev platforms, so it would be pretty inconvenient for us to set that.

We use `/usr/bin/env python` precisely to enable use of virtualenv for those platforms that have a python3 default. 

So neither option will work for everyone and we have to make a choice. Currently, that is  `/usr/bin/env python` with python 2 documented as dependency in the build instructions. When things have shifted more towards python 3, we will probably change that default (and/or update the scripts as well).
