### ISSUE TITLE
Cloned functions (-O2) are incompatible with binary verification

### ISSUE THREAD

**Issue by mbrcknl** [seL4/seL4#805]
`gcc -O2` enables various inter-procedural optimisations that can produce cloned or partial functions in the binary. These functions don't directly correspond to any function in the C, and are beyond the current abilities of binary verification.

For example, if GCC determines that part of a function is worth inlining, but the rest of the function is too big, it might split the function into parts, inlining the first, and emitting the second as a separate function with a new name ending in something like `.part.0`.

Adding `-fno-partial-inlining -fno-ipa-cp -fno-ipa-sra` seems to disable enough inter-procedural optimisations to avoid cloned and partial functions, at least with current kernel and compiler versions.

This issue is to discuss how and when these compiler options should be added to the kernel build. My initial suggestion would be to add the following to the bottom of `gcc.cmake`:

```
# Binary verification cannot handle cloned functions.
if(KernelVerificationBuild)
    add_compile_options(-fno-partial-inlining -fno-ipa-cp -fno-ipa-sra)
endif()
```

What do people think?

**Comment by axel-h** [comment]
Is this gcc only or also for llvm/clang?

**Comment by mbrcknl** [comment]
> Is this gcc only or also for llvm/clang?

Currently only considering GCC. I'm sure there would be analogous issues with Clang, but we currently only attempt binary verification with GCC.

**Comment by lsf37** [comment]
It'd be good to figure out the performance impact of this change. I guess we could just run sel4bench with and without and compare. @kent-mcleod is there anything else we care about in terms of performance?

**Comment by mbrcknl** [comment]
Another todo:
- Test these options with a range of GCC versions. I've only tried GCC 10 so far.

**Comment by kent-mcleod** [comment]
I feel this should be placed under it's own config option. There's already `KernelOptimisation` which selects the compiler optimization level. If you added another option, `KernelOptimizationBVMode`, then the CMake script could look at both options and generate a final list of compiler arguments that were then applied.  `KernelFWholeProgram` should probably also be constrained by `KernelOptimizationBVMode` in a similar way.

**Comment by axel-h** [comment]
@mbrcknl given the feedback, do you plan to make a PR for this?

**Comment by mbrcknl** [comment]
Thanks for the reminder, @axel-h! I'll try to get this done in the next day or so.
