### ISSUE TITLE
What level the seL4 run at?

### ISSUE THREAD

**Issue by wjhtinger** [seL4/seL4#810]
As I know, seL4 is a heypervisor besides a OS. And the heypervisor must run at EL2 level，so, seL4 run at EL2 includin the OS part, right?
And the native app run at EL0, this means that the EL1 is not used by sel4 at native app case? 
Dose my above understanding is right?

**Comment by kent-mcleod** [comment]
On AArch64, when seL4 is running at EL2, native threads run at EL0.  When a native thread has a VCPU object bound to it, it can also run at EL1.

seL4 can also be configured to run at EL1 and all threads will run at EL0. This is a non-hypervisor configuration and is also supported.
