### ISSUE TITLE
Remove deprecated libsel4 headers

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#813]
I wonder if we can finally remove some deprecated libsel4 headers:

- `sel4/messages.h`
  - Seems deprecated since 2016 already. 
  - In https://github.com/seL4/seL4_projects_libs/pull/36 another legacy usage has been removed . 
  - The only usage that remains is in `refos`, see also https://github.com/seL4/refos/issues/15

- `sel4/arch/pfIPC.h`, `sel4/arch/exIPC.h`
  - Seems deprecated since 2016 already.
  - https://github.com/seL4/seL4_libs/pull/61 removes usage.
  - no other usage known

Is anybody else still using this?

**Comment by kent-mcleod** [comment]
I think this is fine.  The upcoming release is already API breaking and migration only requires deleting the files.  A more complicated question is whether the old contents of those header files should be removed from sel4/deprecated.h

**Comment by axel-h** [comment]
I was wondering if we can remove the include from `sel4/sel4 h` at least in the next release, so it must be included manually. The next release woul then remove the contents, but could still keep the empty files

**Comment by kent-mcleod** [comment]
I was more specifically meaning removing the definitions such as `EXCEPT_IPC_SYS_MR_R0` which is what sel4/arch/exIPC.h headers used to contain.

**Comment by axel-h** [comment]
Closing, https://github.com/seL4/seL4/pull/814 got merged.
