### ISSUE TITLE
question about header file in kernel/src/arch/riscv/kernel/boot.c

### ISSUE THREAD

**Issue by GooTal** [seL4/seL4#816]
I`m trying to port seL4 to LoongArch and I got confused reading the source code shown below. It seems this file plat/machine/hardware.h is included. But is this file really need to be included in the directory of riscv? Thank you.

![image](https://user-images.githubusercontent.com/40800103/160231948-390c1546-da52-4784-a92a-607220f628ef.png)

**Comment by kent-mcleod** [comment]
It's used to import the generated header files:
`#include <plat/machine/devices_gen.h>` and `#include <plat/platform_gen.h>`.  These files are generated for Arm and RISC-V platforms by the `declare_default_headers()` cmake function and setting a device tree file in `KernelDTSList`.  These headers declare hardware specific definitions and configuration that each kernel architecture uses.  If you don't want to generate these files, then a static file plat/machine/hardware.h would be needed that provides these definitions instead.  It would go in ./include/plat/<platformname/plat/machine/

**Comment by GooTal** [comment]
Thank you, there seem to be no problems anymore.
