### ISSUE TITLE
seL4 as hypervisor for wasm runtime and linux?

### ISSUE THREAD

**Issue by Comet959** [seL4/seL4#835]
Hi,
If I want to run a Linux virtual machine and a wasm runtime based on seL4 hypervisor, how can I implement it?

Can you give me some ideas?

**Comment by kent-mcleod** [comment]
There's a community-led project listed under https://docs.sel4.systems/CommunityProjects.html which I believe is trying to do this.  I've added the links below:
[WasmEdge](https://github.com/WasmEdge/WasmEdge): [porting a Cloud-native WebAssembly Runtime to seL4](https://github.com/second-state/wasmedge-seL4)

**Comment by Comet959** [comment]
Hi @kent-mcleod ,
Thanks for your reply! I have already practiced this project, but It's not exactly what I want. 

I mean take sel4 as hypervisor, and then run a wasm runtime and a VMM component on it (and run a linux on the VMM).

**Comment by kent-mcleod** [comment]
I don't quite follow sorry.  Do you mean a VMM component implemented as a WASM application?  What architecture is Linux in this scenario?

I believe that the WasmEdge project has a VMM that runs Linux using the native platform architecture.  The Linux VM is then able to load native Wasm apps into the Wasm runtime running in a separate seL4 component. (But again, I'm not familiar with the project)
