### ISSUE TITLE
[question]include/arch/riscv/arch/64/mode/hardware.h

### ISSUE THREAD

**Issue by chenyangyy** [seL4/seL4#836]
Where is CONFIG_PT_LEVELS defined？

**Comment by malus-brandywine** [comment]
Please check [https://github.com/seL4/seL4/blob/master/src/arch/riscv/config.cmake](https://github.com/seL4/seL4/blob/master/src/arch/riscv/config.cmake), the first configuration option is the one.

**Comment by axel-h** [comment]
In general, the `CONFIG_` prefix is added automatically to CMake configuration variables when the C defines are created.
