### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by DemiMarie** [seL4/seL4#84]
The roadmap is out of date — for example, it lists tasks as “to-do” with expected completion dates in the past.  This is a feature request that the roadmap be updated to reflect the current situation.

**Comment by pingerino** [comment]
We are working on an updated roadmap. However, this issue isn't for the seL4 repository itself but for the website, so I'm closing it for now. For updates on the roadmap please keep an eye on our [developer mailling list](https://sel4.systems/lists/listinfo/devel).
