### ISSUE TITLE
discoverability of bitfield functions

### ISSUE THREAD

**Issue by ChenYangng** [seL4/seL4#842]
How do functions in structures_gen.h get generated?

**Comment by Indanz** [comment]
They are generated by tools/bitfield_gen.py from structures.bf files, e.g. include/arch/arm/arch/64/mode/object/structures.bf. Search for "_gen.h" in CMakeLists.txt for more details.

**Comment by ratmice** [comment]
It'd perhaps be good to add a comment to the generator/generated code indicating the source.

**Comment by axel-h** [comment]
PRs are always welcome ;)
Otherwise greping through the ninja files and looking at the CMake builtd targets graph often yields such information.

**Comment by Indanz** [comment]
In this case it's far from obvious how it's generated and grepping the source directory doesn't really work (I tried). Grepping the build directory works slightly better.

What CMake build target graph? The one you get with `cmake --graphviz=test.dot .`?

For automatically generated files it is very common to say in the header how they are generated and from which input files. But if I add:

```
diff --git a/tools/bitfield_gen.py b/tools/bitfield_gen.py
index 31da3a92346a..7d2af948598e 100755
--- a/tools/bitfield_gen.py
+++ b/tools/bitfield_gen.py
@@ -3057,6 +3057,8 @@ if __name__ == '__main__':

                 print("end", file=out_file)
     else:
+        if not in_filename is None:
+            print("/* Generated from '%s' */" % in_filename, file=out_file)
         print("#pragma once\n", file=out_file)
         print('\n'.join(map(lambda x: '#include <%s>' % x,
                             INCLUDES[options.environment])), file=out_file)
```
I get `/* Generated from '/home/iz/vmm-mep/build3/kernel/generated/arch/object/structures.bf.pbf' */`, which is the pre-processed output. And this is mentioned in the build.ninja log already: `DESC = Generating from generated/arch/object/structures.bf.pbf`. But there the trails ends, it's hard to find how/why the bf.pbf files get generated. That magic happens at CMakeLists.txt lines 554-555, in the "Bitfield header generation" section. Following the trail all the way back to the correct structures.bf file is almost impossible.

All in all the original question was a very good one.

**Comment by kent-mcleod** [comment]
We could generate a summarized "Generated from " line in CMake and pass it through the script so that the context is preserved?

**Comment by Indanz** [comment]
Sounds good, but that seems far from trivial because of the many layers of indirection.

If all build/%_gen.h files are always generated from a corresponding kernel/%.bpf file perhaps a generic comment would help, though it would be very confusing if this was ever not true.

**Comment by chenyangyy** [comment]
I add some blocks in structures.bf and generate the corresponding struct in structures_gen.h, but how do I use Bitfield to generate the function I need?(just like xxx_new and xxx_ptr_get_xxx)
In other words, does Bitfield have a mannul?

**Comment by pingerino** [comment]
The bitfield generator only generates code for functions that are used. To create new functions you need to pattern match something similar to what you want and it will generate it. It's not ideal. Documentation + improvements welcome :).

**Comment by lsf37** [comment]
yeah, writing documentation for it is on the todo list (#800). For now, it might help grepping for the names of current fields, blocks, and unions in the current sources to get an idea what is being generated. Generally, there should be a constructor for every block, and getter + setter for each field (getters and setters also for pointers to blocks/unions).

**Comment by lsf37** [comment]
> I add some blocks in structures.bf and generate the corresponding struct in structures_gen.h, but how do I use Bitfield to generate the function I need?(just like xxx_new and xxx_ptr_get_xxx)
> In other words, does Bitfield have a mannul?

There now is a proposed manual for the bitfield generator in PR #1009. It describes which functions get generated, but doesn't describe the pruning and preprocessing steps in the seL4 build system yet.

**Comment by lsf37** [comment]
The PR #1010 now adds a comment in the generated `_gen.h` file that points back to the original `.bf` files before preprocessing.
