### ISSUE TITLE
Spectre variant 1 mitigation

### ISSUE THREAD

**Issue by DemiMarie** [seL4/seL4#85]
This is a feature request for mitigating against Spectre variant 1 attacks.

**Comment by AdrianDanis** [comment]
Can you elaborate on which platform you would like this for? This is already done for x86.

**Comment by N8Fear** [comment]
Does x86 include x86_64/amd64/emt64 (or what ever you like to call the 64 Bit version)?

**Comment by AdrianDanis** [comment]
Yes the spectre mitigations are for all x86 variants. Currently meltdown mitigation is only implemented for x86-64 and not ia32 or ARM

**Comment by N8Fear** [comment]
Nice! Thank you for the info!
