### ISSUE TITLE
Do not use cross-node ksCurTime

### ISSUE THREAD

**Issue by Indanz** [seL4/seL4#854]
Replace `NODE_STATE_ON_CORE(ksCurTime)` calls with `NODE_STATE(ksCurTime)`.

The code using ksCurTime assumes that `ksCurTime` is up-to-date, but this assumption is wrong for `ksCurTime` of other CPU cores.

refill_new(), refill_ready(), refill_update() and refill_unblock_check() all use ksCurTime via `NODE_STATE_ON_CORE`.

The implications of using `NODE_STATE(ksCurTime)` is that all clocks must be synchronous:
- Riscv is okay: The specification states: "The real-time clocks of all hardware threads in a single user application should be synchronized to within one tick of the real-time clock."
- x86 okay if not ancient when Invariant TSC is supported. (Constant TSC is probably also good enough for seL4 if cores are not shut off via C/T/P-states.)
- aarch64 is okay.
- arm32: arm_global.h is okay. Exynos timer seems okay. am335x and omap3430 are single-core.

See also issue #844.

**Comment by kent-mcleod** [comment]
This seems like a necessary fix.

**Comment by Indanz** [comment]
Fix is merged.
