### ISSUE TITLE
Is arm64 address space graphic in comment error?

### ISSUE THREAD

**Issue by FinnZhang** [seL4/seL4#868]
I found the misleading comment when I figure out the memory layout of arm64 in seL4. 
https://github.com/seL4/seL4/blob/b8ef00e09a1273d9f436dc67db4761cd4711295f/include/arch/arm/arch/64/mode/hardware.h#L78

`PPTR_BASE` should at Line 
https://github.com/seL4/seL4/blob/b8ef00e09a1273d9f436dc67db4761cd4711295f/include/arch/arm/arch/64/mode/hardware.h#L100

**Comment by axel-h** [comment]
Could you make a PR with the fix?

**Comment by FinnZhang** [comment]
> Could you make a PR with the fix?

Ok. Please check #869
