### ISSUE TITLE
Feature request: epoll-like event polling system

### ISSUE THREAD

**Issue by DemiMarie** [seL4/seL4#87]
This is a feature request for an epoll-like polling system that allows one thread to wait on a message to be sent to any of N different endpoints/notifications, using at most O(log N) time per receive.  Currently, this can be emulated with threads, but threads are relatively expensive, while my hope is that this would not be.

**Comment by AdrianDanis** [comment]
We have never come up with a design for something like this that didn't result in potentially long running kernel operations or other unacceptable design side affects and was amenable to verification. Of course it also has never been a priority either.

**Comment by gernotheiser** [comment]
Furthermore, seL4 adheres to the microkernel principle that nothing should be in the kernel if it can be done safely at user level.

Also, note that notifications already provide a primitive form of polling multiple sources. The main restriction is the size of the Notification bitfield, which is restricted to the word size. I’d be more open to consider generalising Notification semantics, given a convincing use case.

**Comment by DemiMarie** [comment]
Just curious: may I ask why?  It seems like it can be handled using a
balanced binary tree or similar keyed on physical address (which is
guaranteed to be unique).  For a 64-bit system, there obviously cannot be
more than 60 levels in the tree, since a capability is 16 bytes.  A B-tree
would be better, but would be harder to verify.

The idea is that each capability would contain a set of endpoints that
would be signaled when the capability is notified.  The endpoint has a
binary heap of responses, keyed on an in-kernel priority value.  So when
the notification happens, the endpoint receives the notification, plus the
capability of the notification.  Essentially, this would be an seL4 version
of I/O Completion Ports.

Since this can be implemented in userspace, I can see a very good argument
for leaving it out.  That said, I do not see a performant way of doing it
in userspace.

Is there something I am missing here?

**Comment by pingerino** [comment]
This feature will not be included in the kernel any time soon.
