### ISSUE TITLE
Update memory mapping picture

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#873]
_Originally posted by @lsf37 in https://github.com/seL4/seL4/pull/869#pullrequestreview-1002088860_

> I think there might be another error in the picture for hypervisor mode. The picture puts `PPTR_BASE` at `2^48 - 2^39` (`0xFF80_0000_0000`), but the code puts it at `2^39` (`0x80_0000_0000`). @kent-mcleod I assume the code is correct here and the picture should be updated?

See https://github.com/seL4/seL4/blob/master/include/arch/arm/arch/64/mode/hardware.h#L112-L155

**Comment by lsf37** [comment]
#957 is a duplicate, but has more description, so I'll close this one here.
