### ISSUE TITLE
"No user images loaded! abort() called."

### ISSUE THREAD

**Issue by j824737450** [seL4/seL4#88]
Hi,
I want to boot seL4 test on imx6q-sabrelite and I do as https://docs.sel4.systems/Testing.html. Now there is a problem for me like that:
![1](https://user-images.githubusercontent.com/33032927/38726055-a63bbf18-3f3b-11e8-9c5b-4bbb167da29c.png)
Do you have any ideas?
Thank you !

**Comment by N8Fear** [comment]
Since it seems like either no apps were built or not included in the image, it may be helpful to add some build logs/output of the actual build.

**Comment by j824737450** [comment]
The all build logs are shown below:
![1](https://user-images.githubusercontent.com/33032927/38779332-5992c7aa-40f9-11e8-8687-64bcfd7b5e59.jpg)
![2](https://user-images.githubusercontent.com/33032927/38779333-61400b84-40f9-11e8-91b4-f23f6b98dd48.png)
![3](https://user-images.githubusercontent.com/33032927/38779335-66336514-40f9-11e8-8a32-25a3aa320027.jpg)
![4](https://user-images.githubusercontent.com/33032927/38779337-69e96244-40f9-11e8-8b88-5744ad56832e.jpg)
![5](https://user-images.githubusercontent.com/33032927/38779339-6e31a1c2-40f9-11e8-88bd-98399a3514ed.jpg)
![6](https://user-images.githubusercontent.com/33032927/38779342-7231dd28-40f9-11e8-8791-6753abf844f7.jpg)
![7](https://user-images.githubusercontent.com/33032927/38779345-75ff2370-40f9-11e8-88d0-53f33609b328.jpg)
Thank you!

**Comment by j824737450** [comment]
I've solved the problem. Thank you!
