### ISSUE TITLE
ZYNQ7000 How to Virtualize ?Whether it has the capacity?

### ISSUE THREAD

**Issue by jiachengye66** [seL4/seL4#883]
Hi, I recently ported Linux based on SEL4 on Zynq7000 ZC706 platform.  After studying, I saw the official documentation that camkes VM does not support this platform.  Zynq7000 does virtualization support for SEL4?  If not.  How can I port my idea of Linux? 
It would be much appreciated if you could help me.  The problem has puzzled us for a long time .
Thank You!

**Comment by kent-mcleod** [comment]
Hi, the CAmkES VM cannot be run on the ZC706 platform because it uses a Cortex-A9 processor which doesn't implement ARMv7 virtualization extensions. You would need to select a different platform such as one that uses a Cortex-A15 (https://en.wikipedia.org/wiki/ARM_Cortex-A15)
