### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by zhicheng** [seL4/seL4#89]
https://github.com/seL4/seL4/blob/c5184b802b1d523b7c3376729d8cd9b4828430d9/Makefile#L295

**Comment by AdrianDanis** [comment]
This is definitely a typo. Although that code path is deprecated and should be being deleted soon as building the kernel standalone with Make is not supported.

**Comment by lsf37** [comment]
It looks like this has been resolved with the switch to cmake.
