### ISSUE TITLE
Help wanted about Endpoint tcb_queue.

### ISSUE THREAD

**Issue by ghost** [seL4/seL4#891]
When SMP enabled, multi TCBs invoke endpoint Send at the same time and no receiver at the moment. Then the two TCBs should be enqued into Endpoint tcb_queue.  Will the two sender TCBs corrupt the shared Endpoint  tcb_queue when modify the shared queue at the same time? Why we don't  need lock the Endpoint queue pointer using locking mechanism?  Thanks a lot.

**Comment by kent-mcleod** [comment]
When SMP is enabled, there is a locking mechanism on entry to the kernel (`NODE_LOCK_SYS` in the code). This locking mechanism will serialize the two send operations so that they can't happen at the same time.
