### ISSUE TITLE
question about external interrupts of seL4

### ISSUE THREAD

**Issue by GooTal** [seL4/seL4#892]
Hello, we are still trying to port seL4 to LoongArch.

I notice that in `handleInterrupt()` function of `kernel/src/object/interrupt.c`, a valid irq state should be in one of these states: IRQSignal, IRQTimer, IRQIPI, IRQReserved or IRQInactive. Which state should a valid external interrupts be in? Or, should kernel handle external interrupts?

The reason i got this question is that riscv enabled SIE_SEIE in `initLocalIRQController()` function of `kernel/src/arch/riscv/machine/hardware.c`. But i didn`t find the related external interrupt handler for plic interrupts. 

We are trying to add external interrupts support. I already initialized external interrupt controller, and trying to add the external interrupt handler. But i didn`t get any idea while reading the source code.

Thanks for your time.

**Comment by kent-mcleod** [comment]
External interrupts start in IRQInactive.  If the kernel uses the interrupt and doesn't allow it to be delegated to user level, it is set to IRQReserved during boot. If the IRQ is enabled by userLevel it is set to IRQSignal. If the IRQ is un-enabled from user level it is set back to IRQInactive. IRQTimer is special and only for the kernel timer interrupt which could be implemented using an external interrupt. IRQIPI is also special and is for SMP configurations for interrupts from other cores.
