### ISSUE TITLE
Where is the fault handler？

### ISSUE THREAD

**Issue by chenyangyy** [seL4/seL4#905]
> In seL4, when a thread generates a thread fault, the kernel will block the faulting thread’s execution and attempt to deliver a message across a special endpoint associated with that thread, called its “fault handler” endpoint.
> The thread which is listening on the other end of the fault endpoint is called the “fault handler”. 

When an exception occurs,such as a load page fault.I have seen kernel creating a message to “fault handler” endpoint in handleVMFaultEvent.But where is the fault handler thread and its corresponding code?And where is the fault handler configured？

**Comment by lsf37** [comment]
The fault handler is a regular user-level thread that can listen on the fault handler endpoint (which also is a regular endpoint, which can be set as a fault handler endpoint using TCBConfigure). It's up to user-level to set these up.

**Comment by chenyangyy** [comment]
Does this mean that no exceptions can occur in the kernel?

**Comment by lsf37** [comment]
> Does this mean that no exceptions can occur in the kernel?

Yes, no exceptions can occur in the kernel.

> After switching to the user thread,what if an exception occurs before the user-level thread sets the fault handler?

The thread would remain suspended. You'd usually set up the fault handler before starting the thread (as part of setting up the thread with memory and other resources). Any other thread that has a TCB cap to the suspended thread could still set the fault handler and try to restart the thread, which would usually create the fault again, but the usual setup would be to have the fault handler first.

**Comment by chenyangyy** [comment]
Thanks.In addition to this,I don't seem to see that the kernel set Fault Handler for the initial thread(sel4test-driver) when it created it.Is that so?Is the seL4test project currently running to ensure that no exceptions occur?

**Comment by yyshen** [comment]
> Thanks.In addition to this,I don't seem to see that the kernel set Fault Handler for the initial thread(sel4test-driver) when it created it.Is that so?Is the seL4test project currently running to ensure that no exceptions occur?

Since the initial thread has the TCB cap for itself, so it can just set up the fault handler for itself.
