### ISSUE TITLE
build a system with seL4

### ISSUE THREAD

**Issue by chenyangyy** [seL4/seL4#910]
How can I add some components on top of the seL4？Is there an example of adding a file system to seL4？

**Comment by axel-h** [comment]
Have a look into CAmkES (https://docs.sel4.systems/projects/camkes) and the tutorials(https://docs.sel4.systems/Tutorials/#camkes-tutorials). This is a framework for building systems on top of the seL4 kernel. 
I think there is no out-of-the-box solution with a storage and filesysten driver, but at
