### ISSUE TITLE
Does sel4bench SIMULATION=TRUE for qemu?

### ISSUE THREAD

**Issue by mincheolsung** [seL4/seL4#912]
Hi,

I am trying to run ipc benchmark from sel4bench in qemu.
I tried `../init-build.sh -DPLATFORM=x86_64 -DSIMULATION=TRUE` but got error below:

mincheol@in-container:/host/build-qemu$ ../init-build.sh -DPLATFORM=x86_64 -DSIMULATION=TRUE
loading initial cache file /host/projects/sel4bench/settings.cmake
-- Set platform details from PLATFORM=x86_64
--   KernelPlatform: pc99
--   KernelSel4Arch: x86_64
-- Found seL4: /host/kernel
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found elfloader-tool: /host/tools/seL4/elfloader-tool
-- Found musllibc: /host/projects/musllibc
-- Found util_libs: /host/projects/util_libs
-- Found seL4_libs: /host/projects/seL4_libs
-- Found sel4_projects_libs: /host/projects/sel4_projects_libs
-- Found projects_libs: /host/projects/projects_libs
-- Found sel4runtime: /host/projects/sel4runtime
-- Performing Test compiler_arch_test
-- Performing Test compiler_arch_test - Success
-- libmuslc architecture: 'x86_64' (from KernelSel4Arch 'x86_64')
-- Detecting cached version of: musllibc
-- Found Git: /usr/bin/git (found version "2.30.2")
--   Found valid cache entry for musllibc
-- Found Nanopb: /host/nanopb
-- CPIO test cpio_reproducible_flag PASSED
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    SIMULATION

-- Build files have been written to: /host/build-qemu

Does sel4bench not support qemu build?

**Comment by axel-h** [comment]
My understanding is, that sel4bench targets real platform only, as collecting benchmak data on simulation does not make much sense.

**Comment by mincheolsung** [comment]
Why is that? I thought sel4becn was able to measure IPC benchmark in qemu cause rdtsc (read time stamp counter) is emulated.

**Comment by axel-h** [comment]
There might be a good chance to get it running on QEMU also, if you drop the variable CMake complains about. Basically the platform is supported by seL4, so the build system should be able to create a working binary image. You can have a look at what seL4test does there and copy this over.
