### ISSUE TITLE
How to pin a process on a VCPU

### ISSUE THREAD

**Issue by mincheolsung** [seL4/seL4#915]
Hi,

I am trying to pin a process on a VCPU in qemu. I looked up the list of APIs but couldn't find one.
How can I do that?

**Comment by yyshen** [comment]
A VCPU is associated with a TCB. You can use seL4_TCB_SetAffinity with the TCB.

**Comment by Indanz** [comment]
For MCS it's less straightforward: 

CPU affinity is controlled per scheduling context. Each CPU core has it's own scheduling control cap which is passed to the root server. It depends on which one is used in `seL4_SchedControl_Configure` what CPU core the SC will be bound to.

**Comment by mincheolsung** [comment]
Thanks guys!
