### ISSUE TITLE
Question about IPC benchmark

### ISSUE THREAD

**Issue by mincheolsung** [seL4/seL4#920]
Hi, I couldn't understand what the code below is doing.
```
152 #define IPC_CALL_FUNC(name, bench_func, send_func, call_func, send_start_end, length, cache_func) \
153     seL4_Word name(int argc, char *argv[]) { \
154     uint32_t i; \
155     ccnt_t start UNUSED, end UNUSED; \
156     seL4_CPtr ep = atoi(argv[0]);\
157     seL4_CPtr result_ep = atoi(argv[1]);\
158     seL4_MessageInfo_t tag = seL4_MessageInfo_new(0, 0, 0, length); \
159     call_func(ep, tag); \
160     COMPILER_MEMORY_FENCE(); \
161     for (i = 0; i < WARMUPS; i++) { \
162         cache_func(); \
163         READ_COUNTER_BEFORE(start); \
164         bench_func(ep, tag); \
165         READ_COUNTER_AFTER(end); \
166     }\
167     COMPILER_MEMORY_FENCE(); \
168     send_result(result_ep, send_start_end); \
169     send_func(ep, tag); \
170     api_wait(ep, NULL);/* block so we don't run off the stack */ \
171     return 0; \
172 }
```
What does line 161~165 do?

**Comment by Indanz** [comment]
Lines 162-165 are doing whatever is needed to run and measure a benchmark. (`cache_func` may clean cache lines or something, to make sure the test is not slowed down by the write back of pre-existing dirty cache lines. The counter read are probably reading performance monitor counters before and after the test.)

It seems the benchmark itself is done `WARMUPS` times and only the last timing is remembered, to do a cache hot benchmark.

It would be useful if the cache cold case was also measured, but that would require more cache control than what's practical.

**Comment by gernotheiser** [comment]
> It would be useful if the cache cold case was also measured, but that would require more cache control than what's practical

I’ve got a student lined up to measure and improve worst-case (really: bad-case) performance.

**Comment by Indanz** [comment]
> I’ve got a student lined up to measure and improve worst-case (really: bad-case) performance.

Getting really the worst-case performance is very hard, especially on more complex hardware with SMP. It not only would require everything to miss in all caches, it would also involve bank conflicts for all SDRAM accesses and other such conflicts for shared resources.

What I'd really like to know is expected performance for a system under load. For those I want the code and data to miss in L1 and hit in L2 cache. That should give somewhat realistic numbers for system design, unlike the worst or best case numbers.

**Comment by mincheolsung** [comment]
@gernotheiser Thanks for the reply, Dr. Heiser.
I am benchmarking seL4's IPC and finding a performance gap between sel4bench and my own benchmark (I modified the sel4bench IPC benchmark to measure the IPC for my purpose. The preliminary results looked 4x~5x slower).  If you don't mind, I would like to contact you by email and discuss it. Thanks!

**Comment by gernotheiser** [comment]
> I am benchmarking seL4's IPC and finding a performance gap between sel4bench and my own benchmark (I modified the sel4bench IPC benchmark to measure the IPC for my purpose. The preliminary results looked 4x~5x slower). If you don't mind, I would like to contact you by email and discuss it. Thanks!

please don’t contact me personally, use ***@***.*** as I won’t have the time to look your issues myself.

Gernot

**Comment by lsf37** [comment]
> please don’t contact me personally, use ***@***.*** as I won’t have the time to look your issues myself. Gernot

I suspect Gernot means the [developer mailing list](https://lists.sel4.systems/postorius/lists/devel.sel4.systems/) (GitHub masks email addresses).
