### ISSUE TITLE
IPC does not support thread-to-thread P2P communication

### ISSUE THREAD

**Issue by 19900824** [seL4/seL4#934]
For example, if two threads listen to the same terminal (by sel4_recv), but another thread sends a message to the same terminal via sel4_send, the thread that listens first will receive the message. In real time, this message is needed by the thread that listens later. That is to say, I hope IPC can support this mode of P2P, may I ask how to achieve this mode of communication in user mode?

**Comment by Indanz** [comment]
seL4 does not support one-to-many IPC, it only supports P2P. Even with notifications only one task will be woken up. This is done to simplify the kernel and to avoid O(N) operations within the kernel, limiting worst-case execution time.

With that in mind, the usual way of using IPC is to give each listening task its own private endpoint. That way the sender chooses which task to wake up. This would also solve your priority problem.

**Comment by gernotheiser** [comment]
It's the old issue: IPC is (for historic reasons) a misnomer, it's a protected procedure call operation, not a general-purpose communication mechanism. Please see my Summit talk (https://trustworthy.systems/publications/papers/Heiser_22%3Asel4s-o.abstract) and blog (https://microkerneldude.org/2019/03/07/how-to-and-how-not-to-use-sel4-ipc/)
