### ISSUE TITLE
Anyway to print in benchmark_process

### ISSUE THREAD

**Issue by mincheolsung** [seL4/seL4#959]
Hi,

I spawned a process using benchmark_spawn_process.
In the spawned process, is there any way to print a message?
I tried benchmark_write but didn't work.

**Comment by malus-brandywine** [comment]
Hi,

Typical way of logging in applications is to use ZFLOG library:


https://github.com/seL4/util_libs/blob/master/libutils/doc/ZFLOG.md


PS: This issue was better to be posted in benchmarking support project:
https://github.com/seL4/sel4bench

**Comment by mincheolsung** [comment]
I tried ZF_LOG but didn't print messages.

**Comment by Indanz** [comment]
IIRC, spawned processes can't print anything. Last time I needed to do this for debugging purposes, I used `seL4_DebugPutChar()` and the seL4 kernel configured with `CONFIG_PRINTING`/`KernelPrinting` enabled.

**Comment by mincheolsung** [comment]
Thanks!
