### ISSUE TITLE
error: Cannot fetch picotcp.git (GitError: picotcp.git update-ref: fatal: 7f12f2949f44b1de04e9d89407642a9efee878c6^0: not a valid SHA1 )

### ISSUE THREAD

**Issue by HediDlp** [seL4/seL4#99]
Hi,
When running repo sync command this error will occured.
Can anyone help me?

**Comment by pingerino** [comment]
Which project are you trying to build? I'm closing this as irrelevant since pico tcp is only used as part of other projects, not the kernel itself. Please consider getting help from any of the sources [listed here](https://docs.sel4.systems/#Community).
