### ISSUE TITLE
remove irq parameter from mcsPreemptionPoint

### ISSUE THREAD

**Issue by lsf37** [seL4/seL4#991]
Since #327 `mcsPreemptionPoint` no longer uses its `irq` parameter, so the parameter should be removed.

This came out of the [discussion](https://github.com/seL4/seL4/issues/472#issuecomment-1229172341) on #472.

Verification impact should be minimal as long as we do this before CRefine has not progressed too far. @michaelmcinerney do you agree?

**Comment by michaelmcinerney** [comment]
> Verification impact should be minimal as long as we do this before CRefine has not progressed too far. @michaelmcinerney do you agree?

Yes, if this is done relatively soon, this should be very easy for verification
